AgentTestConfiguration:
  description: Dynamic configuration for testing agents.
  properties:
    id:
      type: string
      default: null
      title: id
    providerId:
      type: string
      default: null
      title: providerid
    model:
      type: string
      default: null
      title: model
    instructions:
      title: instructions
      type: string
    systemPrompt:
      type: string
      default: null
      title: systemprompt
    config:
      additionalProperties: true
      title: config
      type: object
    tools:
      items:
        $ref: ToolConfigAgentTestConfiguration.yml#/ToolConfigAgentTestConfiguration
      title: tools
      type: array
  required:
  - instructions
  - config
  - tools
  title: agentTestConfiguration
  type: object
