AlgoliaRecommendToolIndexConfig:
  properties:
    index:
      maxLength: 100
      minLength: 1
      title: index
      type: string
    modelName:
      maxLength: 100
      minLength: 1
      title: modelname
      type: string
    description:
      default: ''
      title: description
      type: string
  required:
  - index
  - modelName
  title: algoliaRecommendToolIndexConfig
  type: object
