AlgoliaSearchToolConfig:
  properties:
    name:
      maxLength: 32
      minLength: 3
      title: name
      type: string
    type:
      const: algolia_search_index
      default: algolia_search_index
      title: type
      type: string
    indices:
      items:
        $ref: AlgoliaSearchToolIndexConfig.yml#/AlgoliaSearchToolIndexConfig
      title: indices
      type: array
    mode:
      $ref: ModeEnum.yml#/ModeEnum
    allowUnlistedIndices:
      default: false
      title: allowunlistedindices
      type: boolean
  required:
  - type
  - name
  - indices
  title: algoliaSearchToolConfig
  type: object
