AlgoliaSearchToolIndexConfig-Input:
  properties:
    index:
      type: string
      maxLength: 100
      minLength: 1
      title: index
    description:
      type: string
      maxLength: 3000
      minLength: 1
      title: description
    enhancedDescription:
      type: string
      title: enhanceddescription
      default: ''
    searchParameters:
      oneOf:
        - $ref: 'SearchParametersInput.yml#/SearchParameters-Input'
        - type: 'null'
    searchControls:
      oneOf:
        - $ref: 'IndexSearchParametersInput.yml#/IndexSearchParameters-Input'
        - type: 'null'
  type: object
  required:
    - index
    - description
  title: algoliaSearchToolIndexConfig
