AlgoliaSearchToolIndexConfig:
  properties:
    index:
      maxLength: 100
      minLength: 1
      title: index
      type: string
    description:
      maxLength: 3000
      minLength: 1
      title: description
      type: string
    enhancedDescription:
      default: ''
      title: enhanceddescription
      type: string
    searchParameters:
      oneOf:
      - $ref: SearchParameters.yml#/SearchParameters
      - type: 'null'
    searchControls:
      oneOf:
      - $ref: IndexSearchParameters.yml#/IndexSearchParameters
      - type: 'null'
  required:
  - index
  - description
  title: algoliaSearchToolIndexConfig
  type: object
