ApplicationConfigPatch:
  properties:
    maxRetentionDays:
      type: integer
      title: maxretentiondays
      description: 'Maximum number of days to retain data. Valid values: [0, 30, 60,
        90].'
      default: 90
  type: object
  title: applicationConfigPatch
