ClientSideToolConfig:
  properties:
    name:
      maxLength: 32
      minLength: 3
      title: name
      type: string
    type:
      const: client_side
      default: client_side
      title: type
      type: string
    description:
      maxLength: 200
      minLength: 1
      title: description
      type: string
    inputSchema:
      $ref: ClientToolsArgsSchema.yml#/ClientToolsArgsSchema
  required:
  - type
  - name
  - description
  - inputSchema
  title: clientSideToolConfig
  type: object
