McpServerToolConfig:
  properties:
    url:
      maxLength: 512
      minLength: 1
      title: url
      type: string
    transport:
      const: streamable_http
      default: streamable_http
      title: transport
      type: string
    headers:
      additionalProperties:
        type: string
      title: headers
      type: object
    name:
      maxLength: 32
      minLength: 3
      title: name
      type: string
    type:
      const: mcp_tools
      default: mcp_tools
      title: type
      type: string
    id:
      oneOf:
      - type: string
      - type: 'null'
      default: null
      description: Stable unique identifier for this MCP tool.
      title: id
    allowedTools:
      $ref: AllowedToolsUnion.yml#/AllowedToolsUnion
  required:
  - type
  - url
  - headers
  - name
  title: mcpServerToolConfig
  type: object
