ToolConfigInput:
  oneOf:
    - $ref: 'ClientSideToolConfig.yml#/ClientSideToolConfig'
    - $ref: 'AlgoliaSearchToolConfig.yml#/AlgoliaSearchToolConfig'
    - $ref: 'AlgoliaRecommendToolConfigInput.yml#/AlgoliaRecommendToolConfig-Input'
    - $ref: 'AlgoliaDisplayResultsToolConfig.yml#/AlgoliaDisplayResultsToolConfig'
    - $ref: 'McpServerToolConfig.yml#/McpServerToolConfig'
    - $ref: 'UnknownToolConfig.yml#/UnknownToolConfig'
  discriminator:
    propertyName: type
    mapping:
      algolia_display_results: AlgoliaDisplayResultsToolConfig.yml#/AlgoliaDisplayResultsToolConfig
      algolia_recommend: AlgoliaRecommendToolConfigInput.yml#/AlgoliaRecommendToolConfig-Input
      algolia_search_index: AlgoliaSearchToolConfig.yml#/AlgoliaSearchToolConfig
      client_side: ClientSideToolConfig.yml#/ClientSideToolConfig
      mcp_tools: McpServerToolConfig.yml#/McpServerToolConfig
      unknown: UnknownToolConfig.yml#/UnknownToolConfig
