ToolConfigOutput:
  oneOf:
    - $ref: 'ClientSideToolConfig.yml#/ClientSideToolConfig'
    - $ref: 'AlgoliaSearchToolConfigOutput.yml#/AlgoliaSearchToolConfig-Output'
    - $ref: 'AlgoliaRecommendToolConfigOutput.yml#/AlgoliaRecommendToolConfig-Output'
    - $ref: 'AlgoliaDisplayResultsToolConfig.yml#/AlgoliaDisplayResultsToolConfig'
    - $ref: 'McpServerToolConfigOutput.yml#/McpServerToolConfig-Output'
    - $ref: 'UnknownToolConfig.yml#/UnknownToolConfig'
  discriminator:
    propertyName: type
    mapping:
      algolia_display_results: AlgoliaDisplayResultsToolConfig.yml#/AlgoliaDisplayResultsToolConfig
      algolia_recommend: AlgoliaRecommendToolConfigOutput.yml#/AlgoliaRecommendToolConfig-Output
      algolia_search_index: AlgoliaSearchToolConfigOutput.yml#/AlgoliaSearchToolConfig-Output
      client_side: ClientSideToolConfig.yml#/ClientSideToolConfig
      mcp_tools: McpServerToolConfigOutput.yml#/McpServerToolConfig-Output
      unknown: UnknownToolConfig.yml#/UnknownToolConfig
