UnknownToolConfig:
  additionalProperties: true
  description: A tool configuration that this version of the API does not recognize.
  properties:
    name:
      maxLength: 32
      minLength: 3
      title: name
      type: string
    type:
      const: unknown
      default: unknown
      title: type
      type: string
  required:
  - type
  - name
  title: unknownToolConfig
  type: object
