UnknownToolConfig:
  additionalProperties: true
  description: Exists only to ensure that when you change branch from toolX to feat/toolY,
    your config stays valid.
  properties:
    name:
      maxLength: 32
      minLength: 3
      title: name
      type: string
    type:
      const: unknown
      default: unknown
      title: type
      type: string
  required:
  - type
  - name
  title: unknownToolConfig
  type: object
