get:
  operationId: listConfigVersions
  summary: List configuration versions.
  description: |
    Lists previous versions of the specified crawler's configuration, including who authored the change.
    Every time you [update the configuration](#tag/config/operation/patchConfig) of a crawler,
    a new version is added.
  tags:
    - config
  parameters:
    - $ref: '../common/parameters.yml#/CrawlerIdParameter'
    - $ref: '../common/parameters.yml#/ItemsPerPage'
    - $ref: '../common/parameters.yml#/Page'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../common/schemas/crawlerConfigVersionsResponse.yml'
    '404':
      description: Not found.
