get:
  operationId: listConfigVersions
  summary: List crawler versions.
  description: List crawler config versions.
  parameters:
    - $ref: '../common/parameters.yml#/CrawlerIdParameter'
    - in: query
      name: itemsPerPage
      schema:
        type: integer
        minimum: 1
        default: 20
        maximum: 100
      description: Change the number of versions per page.
    - in: query
      name: page
      schema:
        type: integer
        minimum: 1
        default: 1
        maximum: 5000
      description: Change the page number.
  responses:
    '200':
      description: A list of crawler versions and pagination information.
      content:
        application/json:
          schema:
            $ref: '../common/schemas/crawlerConfigVersionsResponse.yml'
