/*
 * Search API
 * API powering the Search feature of Algolia.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.algolia.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** RankingInfoMatchedGeoLocation */
@JsonPropertyOrder(
  {
    RankingInfoMatchedGeoLocation.JSON_PROPERTY_LAT,
    RankingInfoMatchedGeoLocation.JSON_PROPERTY_LNG,
    RankingInfoMatchedGeoLocation.JSON_PROPERTY_DISTANCE,
  }
)
@JsonTypeName("rankingInfo_matchedGeoLocation")
public class RankingInfoMatchedGeoLocation {

  public static final String JSON_PROPERTY_LAT = "lat";
  private Double lat;

  public static final String JSON_PROPERTY_LNG = "lng";
  private Double lng;

  public static final String JSON_PROPERTY_DISTANCE = "distance";
  private Integer distance;

  public RankingInfoMatchedGeoLocation lat(Double lat) {
    this.lat = lat;
    return this;
  }

  /**
   * Latitude of the matched location.
   *
   * @return lat
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Latitude of the matched location.")
  @JsonProperty(JSON_PROPERTY_LAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getLat() {
    return lat;
  }

  @JsonProperty(JSON_PROPERTY_LAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLat(Double lat) {
    this.lat = lat;
  }

  public RankingInfoMatchedGeoLocation lng(Double lng) {
    this.lng = lng;
    return this;
  }

  /**
   * Longitude of the matched location.
   *
   * @return lng
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Longitude of the matched location.")
  @JsonProperty(JSON_PROPERTY_LNG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getLng() {
    return lng;
  }

  @JsonProperty(JSON_PROPERTY_LNG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLng(Double lng) {
    this.lng = lng;
  }

  public RankingInfoMatchedGeoLocation distance(Integer distance) {
    this.distance = distance;
    return this;
  }

  /**
   * Distance between the matched location and the search location (in meters).
   *
   * @return distance
   */
  @javax.annotation.Nullable
  @ApiModelProperty(
    value = "Distance between the matched location and the search location (in meters)."
  )
  @JsonProperty(JSON_PROPERTY_DISTANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getDistance() {
    return distance;
  }

  @JsonProperty(JSON_PROPERTY_DISTANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDistance(Integer distance) {
    this.distance = distance;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RankingInfoMatchedGeoLocation rankingInfoMatchedGeoLocation = (RankingInfoMatchedGeoLocation) o;
    return (
      Objects.equals(this.lat, rankingInfoMatchedGeoLocation.lat) &&
      Objects.equals(this.lng, rankingInfoMatchedGeoLocation.lng) &&
      Objects.equals(this.distance, rankingInfoMatchedGeoLocation.distance)
    );
  }

  @Override
  public int hashCode() {
    return Objects.hash(lat, lng, distance);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RankingInfoMatchedGeoLocation {\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    lng: ").append(toIndentedString(lng)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
