// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.
import XCTest

import Utils

@testable import AlgoliaAgentStudio
@testable import AlgoliaCore

final class AgentStudioClientRequestsTests: XCTestCase {
    static let APPLICATION_ID = "my_application_id"
    static let API_KEY = "my_api_key"

    /// createAgent with minimal parameters
    func testCreateAgentTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.createAgentWithHTTPInfo(agentConfigCreate: AgentConfigCreate(
            name: "test-agent",
            instructions: "You are a helpful assistant."
        ))
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{\"name\":\"test-agent\",\"instructions\":\"You are a helpful assistant.\"}"
            .data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/1/agents")
        XCTAssertEqual(echoResponse.method, HTTPMethod.post)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// createAgent with all parameters
    func testCreateAgentTest1() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.createAgentWithHTTPInfo(agentConfigCreate: AgentConfigCreate(
            name: "test-agent",
            description: "A test agent for CTS",
            providerId: "5e33d805-7892-4329-bda7-b524dc3fd04a",
            model: "gpt-4",
            instructions: "You are a helpful assistant.",
            config: ["sendUsage": true, "sendReasoning": true, "temperature": 0.7, "max_tokens": 1500],
            tools: [ItemsUnion.startPart(StartPart(type: "start"))]
        ))
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{\"name\":\"test-agent\",\"description\":\"A test agent for CTS\",\"providerId\":\"5e33d805-7892-4329-bda7-b524dc3fd04a\",\"model\":\"gpt-4\",\"instructions\":\"You are a helpful assistant.\",\"config\":{\"sendUsage\":true,\"sendReasoning\":true,\"temperature\":0.7,\"max_tokens\":1500},\"tools\":[{\"type\":\"start\"}]}"
            .data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/1/agents")
        XCTAssertEqual(echoResponse.method, HTTPMethod.post)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// createAgentCompletion with v4 messages
    func testCreateAgentCompletionTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.createAgentCompletionWithHTTPInfo(
            agentId: "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
            compatibilityMode: CompatibilityMode.aiSdk4,
            agentCompletionRequest: AgentCompletionRequest(messages: MessagesUnion
                .arrayOfMessageV4([MessageV4.userMessageV4(UserMessageV4(
                    role: "user",
                    content: "Hello, how are you?"
                ))]))
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{\"messages\":[{\"role\":\"user\",\"content\":\"Hello, how are you?\"}]}"
            .data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/completions")
        XCTAssertEqual(echoResponse.method, HTTPMethod.post)

        let expectedQueryParameters = try XCTUnwrap("{\"compatibilityMode\":\"ai-sdk-4\"}".data(using: .utf8))
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)
    }

    /// createProvider with OpenAI
    func testCreateProviderTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client
            .createProviderWithHTTPInfo(providerAuthenticationCreate: ProviderAuthenticationCreate(
                name: "My OpenAI Provider",
                providerName: ProviderName.openai,
                input: ProviderInput.openAIProviderInput(OpenAIProviderInput(apiKey: "sk-test-key-1234"))
            ))
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{\"name\":\"My OpenAI Provider\",\"providerName\":\"openai\",\"input\":{\"apiKey\":\"sk-test-key-1234\"}}"
            .data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/1/providers")
        XCTAssertEqual(echoResponse.method, HTTPMethod.post)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// createProvider with Azure OpenAI
    func testCreateProviderTest1() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client
            .createProviderWithHTTPInfo(providerAuthenticationCreate: ProviderAuthenticationCreate(
                name: "My Azure Provider",
                providerName: ProviderName.azureOpenai,
                input: ProviderInput.azureOpenAIProviderInput(AzureOpenAIProviderInput(
                    apiKey: "az-test-key-5678",
                    azureEndpoint: "https://my-resource.openai.azure.com",
                    azureDeployment: "gpt-4o"
                ))
            ))
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{\"name\":\"My Azure Provider\",\"providerName\":\"azure_openai\",\"input\":{\"apiKey\":\"az-test-key-5678\",\"azureEndpoint\":\"https://my-resource.openai.azure.com\",\"azureDeployment\":\"gpt-4o\"}}"
            .data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/1/providers")
        XCTAssertEqual(echoResponse.method, HTTPMethod.post)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// allow del method for a custom path with minimal parameters
    func testCustomDeleteTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.customDeleteWithHTTPInfo(path: "test/minimal")
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/test/minimal")
        XCTAssertEqual(echoResponse.method, HTTPMethod.delete)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// allow del method for a custom path with all parameters
    func testCustomDeleteTest1() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.customDeleteWithHTTPInfo(
            path: "test/all",
            parameters: ["query": AnyCodable("parameters")]
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/test/all")
        XCTAssertEqual(echoResponse.method, HTTPMethod.delete)

        let expectedQueryParameters = try XCTUnwrap("{\"query\":\"parameters\"}".data(using: .utf8))
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)
    }

    /// allow get method for a custom path with minimal parameters
    func testCustomGetTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.customGetWithHTTPInfo(path: "test/minimal")
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/test/minimal")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// allow get method for a custom path with all parameters
    func testCustomGetTest1() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.customGetWithHTTPInfo(
            path: "test/all",
            parameters: ["query": AnyCodable("parameters with space")]
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/test/all")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        let expectedQueryParameters = try XCTUnwrap("{\"query\":\"parameters%20with%20space\"}".data(using: .utf8))
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)
    }

    /// requestOptions should be escaped too
    func testCustomGetTest2() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.customGetWithHTTPInfo(
            path: "test/all",
            parameters: ["query": AnyCodable("to be overridden")],
            requestOptions: RequestOptions(
                headers: ["x-header-1": "spaces are left alone"],
                queryParameters: ["query": "parameters with space", "and an array": ["array", "with spaces"]]
            )
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/test/all")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        let expectedQueryParameters = try XCTUnwrap(
            "{\"query\":\"parameters%20with%20space\",\"and%20an%20array\":\"array%2Cwith%20spaces\"}"
                .data(using: .utf8)
        )
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)

        let expectedHeaders = try XCTUnwrap("{\"x-header-1\":\"spaces are left alone\"}".data(using: .utf8))
        let expectedHeadersMap = try CodableHelper.jsonDecoder.decode([String: String?].self, from: expectedHeaders)

        let echoResponseHeaders = try XCTUnwrap(echoResponse.headers)
        for header in expectedHeadersMap {
            XCTAssertEqual(echoResponseHeaders[header.key.capitalized], header.value)
        }
    }

    /// allow post method for a custom path with minimal parameters
    func testCustomPostTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.customPostWithHTTPInfo(path: "test/minimal")
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{}".data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/test/minimal")
        XCTAssertEqual(echoResponse.method, HTTPMethod.post)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// allow post method for a custom path with all parameters
    func testCustomPostTest1() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.customPostWithHTTPInfo(
            path: "test/all",
            parameters: ["query": AnyCodable("parameters")],
            body: ["body": "parameters"]
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{\"body\":\"parameters\"}".data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/test/all")
        XCTAssertEqual(echoResponse.method, HTTPMethod.post)

        let expectedQueryParameters = try XCTUnwrap("{\"query\":\"parameters\"}".data(using: .utf8))
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)
    }

    /// requestOptions can override default query parameters
    func testCustomPostTest2() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.customPostWithHTTPInfo(
            path: "test/requestOptions",
            parameters: ["query": AnyCodable("parameters")],
            body: ["facet": "filters"],
            requestOptions: RequestOptions(
                queryParameters: ["query": "myQueryParameter"]
            )
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{\"facet\":\"filters\"}".data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/test/requestOptions")
        XCTAssertEqual(echoResponse.method, HTTPMethod.post)

        let expectedQueryParameters = try XCTUnwrap("{\"query\":\"myQueryParameter\"}".data(using: .utf8))
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)
    }

    /// requestOptions merges query parameters with default ones
    func testCustomPostTest3() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.customPostWithHTTPInfo(
            path: "test/requestOptions",
            parameters: ["query": AnyCodable("parameters")],
            body: ["facet": "filters"],
            requestOptions: RequestOptions(
                queryParameters: ["query2": "myQueryParameter"]
            )
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{\"facet\":\"filters\"}".data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/test/requestOptions")
        XCTAssertEqual(echoResponse.method, HTTPMethod.post)

        let expectedQueryParameters = try XCTUnwrap("{\"query\":\"parameters\",\"query2\":\"myQueryParameter\"}"
            .data(using: .utf8))
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)
    }

    /// requestOptions can override default headers
    func testCustomPostTest4() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.customPostWithHTTPInfo(
            path: "test/requestOptions",
            parameters: ["query": AnyCodable("parameters")],
            body: ["facet": "filters"],
            requestOptions: RequestOptions(
                headers: ["x-algolia-api-key": "ALGOLIA_API_KEY"]
            )
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{\"facet\":\"filters\"}".data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/test/requestOptions")
        XCTAssertEqual(echoResponse.method, HTTPMethod.post)

        let expectedQueryParameters = try XCTUnwrap("{\"query\":\"parameters\"}".data(using: .utf8))
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)

        let expectedHeaders = try XCTUnwrap("{\"x-algolia-api-key\":\"ALGOLIA_API_KEY\"}".data(using: .utf8))
        let expectedHeadersMap = try CodableHelper.jsonDecoder.decode([String: String?].self, from: expectedHeaders)

        let echoResponseHeaders = try XCTUnwrap(echoResponse.headers)
        for header in expectedHeadersMap {
            XCTAssertEqual(echoResponseHeaders[header.key.capitalized], header.value)
        }
    }

    /// requestOptions merges headers with default ones
    func testCustomPostTest5() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.customPostWithHTTPInfo(
            path: "test/requestOptions",
            parameters: ["query": AnyCodable("parameters")],
            body: ["facet": "filters"],
            requestOptions: RequestOptions(
                headers: ["x-algolia-api-key": "ALGOLIA_API_KEY"]
            )
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{\"facet\":\"filters\"}".data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/test/requestOptions")
        XCTAssertEqual(echoResponse.method, HTTPMethod.post)

        let expectedQueryParameters = try XCTUnwrap("{\"query\":\"parameters\"}".data(using: .utf8))
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)

        let expectedHeaders = try XCTUnwrap("{\"x-algolia-api-key\":\"ALGOLIA_API_KEY\"}".data(using: .utf8))
        let expectedHeadersMap = try CodableHelper.jsonDecoder.decode([String: String?].self, from: expectedHeaders)

        let echoResponseHeaders = try XCTUnwrap(echoResponse.headers)
        for header in expectedHeadersMap {
            XCTAssertEqual(echoResponseHeaders[header.key.capitalized], header.value)
        }
    }

    /// requestOptions queryParameters accepts booleans
    func testCustomPostTest6() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.customPostWithHTTPInfo(
            path: "test/requestOptions",
            parameters: ["query": AnyCodable("parameters")],
            body: ["facet": "filters"],
            requestOptions: RequestOptions(
                queryParameters: ["isItWorking": true]
            )
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{\"facet\":\"filters\"}".data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/test/requestOptions")
        XCTAssertEqual(echoResponse.method, HTTPMethod.post)

        let expectedQueryParameters = try XCTUnwrap("{\"query\":\"parameters\",\"isItWorking\":\"true\"}"
            .data(using: .utf8))
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)
    }

    /// requestOptions queryParameters accepts integers
    func testCustomPostTest7() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.customPostWithHTTPInfo(
            path: "test/requestOptions",
            parameters: ["query": AnyCodable("parameters")],
            body: ["facet": "filters"],
            requestOptions: RequestOptions(
                queryParameters: ["myParam": 2]
            )
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{\"facet\":\"filters\"}".data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/test/requestOptions")
        XCTAssertEqual(echoResponse.method, HTTPMethod.post)

        let expectedQueryParameters = try XCTUnwrap("{\"query\":\"parameters\",\"myParam\":\"2\"}".data(using: .utf8))
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)
    }

    /// requestOptions queryParameters accepts list of string
    func testCustomPostTest8() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.customPostWithHTTPInfo(
            path: "test/requestOptions",
            parameters: ["query": AnyCodable("parameters")],
            body: ["facet": "filters"],
            requestOptions: RequestOptions(
                queryParameters: ["myParam": ["b and c", "d"]]
            )
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{\"facet\":\"filters\"}".data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/test/requestOptions")
        XCTAssertEqual(echoResponse.method, HTTPMethod.post)

        let expectedQueryParameters = try XCTUnwrap("{\"query\":\"parameters\",\"myParam\":\"b%20and%20c%2Cd\"}"
            .data(using: .utf8))
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)
    }

    /// requestOptions queryParameters accepts list of booleans
    func testCustomPostTest9() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.customPostWithHTTPInfo(
            path: "test/requestOptions",
            parameters: ["query": AnyCodable("parameters")],
            body: ["facet": "filters"],
            requestOptions: RequestOptions(
                queryParameters: ["myParam": [true, true, false]]
            )
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{\"facet\":\"filters\"}".data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/test/requestOptions")
        XCTAssertEqual(echoResponse.method, HTTPMethod.post)

        let expectedQueryParameters = try XCTUnwrap("{\"query\":\"parameters\",\"myParam\":\"true%2Ctrue%2Cfalse\"}"
            .data(using: .utf8))
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)
    }

    /// requestOptions queryParameters accepts list of integers
    func testCustomPostTest10() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.customPostWithHTTPInfo(
            path: "test/requestOptions",
            parameters: ["query": AnyCodable("parameters")],
            body: ["facet": "filters"],
            requestOptions: RequestOptions(
                queryParameters: ["myParam": [1, 2]]
            )
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{\"facet\":\"filters\"}".data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/test/requestOptions")
        XCTAssertEqual(echoResponse.method, HTTPMethod.post)

        let expectedQueryParameters = try XCTUnwrap("{\"query\":\"parameters\",\"myParam\":\"1%2C2\"}"
            .data(using: .utf8))
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)
    }

    /// allow put method for a custom path with minimal parameters
    func testCustomPutTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.customPutWithHTTPInfo(path: "test/minimal")
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{}".data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/test/minimal")
        XCTAssertEqual(echoResponse.method, HTTPMethod.put)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// allow put method for a custom path with all parameters
    func testCustomPutTest1() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.customPutWithHTTPInfo(
            path: "test/all",
            parameters: ["query": AnyCodable("parameters")],
            body: ["body": "parameters"]
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{\"body\":\"parameters\"}".data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/test/all")
        XCTAssertEqual(echoResponse.method, HTTPMethod.put)

        let expectedQueryParameters = try XCTUnwrap("{\"query\":\"parameters\"}".data(using: .utf8))
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)
    }

    /// deleteAgent
    func testDeleteAgentTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.deleteAgentWithHTTPInfo(agentId: "785b14e4-61a8-4c03-8028-bf2ba3ae85ff")
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff")
        XCTAssertEqual(echoResponse.method, HTTPMethod.delete)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// deleteAgentConversations without filters
    func testDeleteAgentConversationsTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client
            .deleteAgentConversationsWithHTTPInfo(agentId: "785b14e4-61a8-4c03-8028-bf2ba3ae85ff")
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations")
        XCTAssertEqual(echoResponse.method, HTTPMethod.delete)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// deleteAgentConversations with date filters
    func testDeleteAgentConversationsTest1() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.deleteAgentConversationsWithHTTPInfo(
            agentId: "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
            startDate: "2024-01-01",
            endDate: "2024-06-30"
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations")
        XCTAssertEqual(echoResponse.method, HTTPMethod.delete)

        let expectedQueryParameters = try XCTUnwrap("{\"startDate\":\"2024-01-01\",\"endDate\":\"2024-06-30\"}"
            .data(using: .utf8))
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)
    }

    /// deleteConversation
    func testDeleteConversationTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.deleteConversationWithHTTPInfo(
            agentId: "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
            conversationId: "test-conversation-id"
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(
            echoResponse.path,
            "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations/test-conversation-id"
        )
        XCTAssertEqual(echoResponse.method, HTTPMethod.delete)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// deleteProvider
    func testDeleteProviderTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.deleteProviderWithHTTPInfo(providerId: "5e33d805-7892-4329-bda7-b524dc3fd04a")
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/providers/5e33d805-7892-4329-bda7-b524dc3fd04a")
        XCTAssertEqual(echoResponse.method, HTTPMethod.delete)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// deleteUserData
    func testDeleteUserDataTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.deleteUserDataWithHTTPInfo(userToken: "test-user-token")
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/user-data/test-user-token")
        XCTAssertEqual(echoResponse.method, HTTPMethod.delete)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// exportConversations without filters
    func testExportConversationsTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.exportConversationsWithHTTPInfo(agentId: "785b14e4-61a8-4c03-8028-bf2ba3ae85ff")
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations/export")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// exportConversations with date filters
    func testExportConversationsTest1() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.exportConversationsWithHTTPInfo(
            agentId: "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
            startDate: "2024-01-01",
            endDate: "2024-12-31"
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations/export")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        let expectedQueryParameters = try XCTUnwrap("{\"startDate\":\"2024-01-01\",\"endDate\":\"2024-12-31\"}"
            .data(using: .utf8))
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)
    }

    /// getAgent
    func testGetAgentTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.getAgentWithHTTPInfo(agentId: "785b14e4-61a8-4c03-8028-bf2ba3ae85ff")
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// e2e get agent
    func testGetAgentTest1() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.getAgentWithHTTPInfo(agentId: "785b14e4-61a8-4c03-8028-bf2ba3ae85ff")
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// getApplicationConfiguration
    func testGetApplicationConfigurationTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.getApplicationConfigurationWithHTTPInfo()
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/configuration")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// e2e getApplicationConfiguration
    func testGetApplicationConfigurationTest1() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.getApplicationConfigurationWithHTTPInfo()
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/configuration")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// getConversation
    func testGetConversationTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.getConversationWithHTTPInfo(
            agentId: "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
            conversationId: "test-conversation-id"
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(
            echoResponse.path,
            "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations/test-conversation-id"
        )
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// getProvider
    func testGetProviderTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.getProviderWithHTTPInfo(providerId: "5e33d805-7892-4329-bda7-b524dc3fd04a")
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/providers/5e33d805-7892-4329-bda7-b524dc3fd04a")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// e2e get provider
    func testGetProviderTest1() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.getProviderWithHTTPInfo(providerId: "5e33d805-7892-4329-bda7-b524dc3fd04a")
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/providers/5e33d805-7892-4329-bda7-b524dc3fd04a")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// getUserData
    func testGetUserDataTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.getUserDataWithHTTPInfo(userToken: "test-user-token")
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/user-data/test-user-token")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// invalidateAgentCache without before
    func testInvalidateAgentCacheTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client
            .invalidateAgentCacheWithHTTPInfo(agentId: "785b14e4-61a8-4c03-8028-bf2ba3ae85ff")
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/cache")
        XCTAssertEqual(echoResponse.method, HTTPMethod.delete)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// invalidateAgentCache with before date
    func testInvalidateAgentCacheTest1() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.invalidateAgentCacheWithHTTPInfo(
            agentId: "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
            before: "2024-12-01"
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/cache")
        XCTAssertEqual(echoResponse.method, HTTPMethod.delete)

        let expectedQueryParameters = try XCTUnwrap("{\"before\":\"2024-12-01\"}".data(using: .utf8))
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)
    }

    /// listAgentConversations with minimal parameters
    func testListAgentConversationsTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client
            .listAgentConversationsWithHTTPInfo(agentId: "785b14e4-61a8-4c03-8028-bf2ba3ae85ff")
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// listAgentConversations with all parameters
    func testListAgentConversationsTest1() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.listAgentConversationsWithHTTPInfo(
            agentId: "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
            startDate: "2024-01-01",
            endDate: "2024-12-31",
            page: 2,
            limit: 10,
            xAlgoliaSecureUserToken: nil
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        let expectedQueryParameters = try XCTUnwrap(
            "{\"startDate\":\"2024-01-01\",\"endDate\":\"2024-12-31\",\"page\":\"2\",\"limit\":\"10\"}"
                .data(using: .utf8)
        )
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)
    }

    /// list agents with no params
    func testListAgentsTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.listAgentsWithHTTPInfo()
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/agents")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// list agents with all parameters
    func testListAgentsTest1() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.listAgentsWithHTTPInfo(
            page: 2,
            limit: 5,
            providerId: "5e33d805-7892-4329-bda7-b524dc3fd04a"
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/agents")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        let expectedQueryParameters = try XCTUnwrap(
            "{\"page\":\"2\",\"limit\":\"5\",\"providerId\":\"5e33d805-7892-4329-bda7-b524dc3fd04a\"}"
                .data(using: .utf8)
        )
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)
    }

    /// e2e list agents
    func testListAgentsTest2() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.listAgentsWithHTTPInfo(page: 1, limit: 2, providerId: nil)
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/agents")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        let expectedQueryParameters = try XCTUnwrap("{\"page\":\"1\",\"limit\":\"2\"}".data(using: .utf8))
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)
    }

    /// listModels
    func testListModelsTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.listModelsWithHTTPInfo()
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/providers/models")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// e2e list models
    func testListModelsTest1() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.listModelsWithHTTPInfo()
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/providers/models")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// listProviderModels
    func testListProviderModelsTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client
            .listProviderModelsWithHTTPInfo(providerId: "5e33d805-7892-4329-bda7-b524dc3fd04a")
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/providers/5e33d805-7892-4329-bda7-b524dc3fd04a/models")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// listProviders with no params
    func testListProvidersTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.listProvidersWithHTTPInfo()
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/providers")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// listProviders with pagination
    func testListProvidersTest1() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.listProvidersWithHTTPInfo(page: 2, limit: 5)
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/providers")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        let expectedQueryParameters = try XCTUnwrap("{\"page\":\"2\",\"limit\":\"5\"}".data(using: .utf8))
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)
    }

    /// e2e list providers
    func testListProvidersTest2() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.listProvidersWithHTTPInfo(page: 1, limit: 2)
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        XCTAssertNil(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponse.path, "/1/providers")
        XCTAssertEqual(echoResponse.method, HTTPMethod.get)

        let expectedQueryParameters = try XCTUnwrap("{\"page\":\"1\",\"limit\":\"2\"}".data(using: .utf8))
        let expectedQueryParametersMap = try CodableHelper.jsonDecoder.decode(
            [String: String?].self,
            from: expectedQueryParameters
        )

        XCTAssertEqual(echoResponse.queryParameters, expectedQueryParametersMap)
    }

    /// publishAgent
    func testPublishAgentTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.publishAgentWithHTTPInfo(agentId: "785b14e4-61a8-4c03-8028-bf2ba3ae85ff")
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponseBodyData, "{}".data(using: .utf8))

        XCTAssertEqual(echoResponse.path, "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/publish")
        XCTAssertEqual(echoResponse.method, HTTPMethod.post)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// unpublishAgent
    func testUnpublishAgentTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.unpublishAgentWithHTTPInfo(agentId: "785b14e4-61a8-4c03-8028-bf2ba3ae85ff")
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)

        XCTAssertEqual(echoResponseBodyData, "{}".data(using: .utf8))

        XCTAssertEqual(echoResponse.path, "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/unpublish")
        XCTAssertEqual(echoResponse.method, HTTPMethod.post)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// updateAgent with minimal parameters
    func testUpdateAgentTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.updateAgentWithHTTPInfo(
            agentId: "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
            agentConfigUpdate: AgentConfigUpdate(name: "updated-agent-name")
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{\"name\":\"updated-agent-name\"}".data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff")
        XCTAssertEqual(echoResponse.method, HTTPMethod.patch)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// updateAgent with all parameters
    func testUpdateAgentTest1() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.updateAgentWithHTTPInfo(
            agentId: "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
            agentConfigUpdate: AgentConfigUpdate(
                name: "updated-agent",
                description: "Updated description",
                providerId: "new-provider-id",
                model: "gpt-4o",
                instructions: "Updated instructions.",
                config: ["temperature": 0.5],
                tools: [ItemsUnion.startPart(StartPart(type: "start"))]
            )
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{\"name\":\"updated-agent\",\"description\":\"Updated description\",\"providerId\":\"new-provider-id\",\"model\":\"gpt-4o\",\"instructions\":\"Updated instructions.\",\"config\":{\"temperature\":0.5},\"tools\":[{\"type\":\"start\"}]}"
            .data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff")
        XCTAssertEqual(echoResponse.method, HTTPMethod.patch)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// updateConfiguration
    func testUpdateConfigurationTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client
            .updateConfigurationWithHTTPInfo(applicationConfigPatch: ApplicationConfigPatch(maxRetentionDays: 30))
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{\"maxRetentionDays\":30}".data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/1/configuration")
        XCTAssertEqual(echoResponse.method, HTTPMethod.patch)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// updateProvider
    func testUpdateProviderTest() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.updateProviderWithHTTPInfo(
            providerId: "5e33d805-7892-4329-bda7-b524dc3fd04a",
            providerAuthenticationPatch: ProviderAuthenticationPatch(name: "Updated Provider Name")
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{\"name\":\"Updated Provider Name\"}".data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/1/providers/5e33d805-7892-4329-bda7-b524dc3fd04a")
        XCTAssertEqual(echoResponse.method, HTTPMethod.patch)

        XCTAssertNil(echoResponse.queryParameters)
    }

    /// updateProvider with input
    func testUpdateProviderTest1() async throws {
        let configuration = try AgentStudioClientConfiguration(
            appID: AgentStudioClientRequestsTests.APPLICATION_ID,
            apiKey: AgentStudioClientRequestsTests.API_KEY,
            region: Region.us
        )
        let transporter = Transporter(configuration: configuration, requestBuilder: EchoRequestBuilder())
        let client = AgentStudioClient(configuration: configuration, transporter: transporter)

        let response = try await client.updateProviderWithHTTPInfo(
            providerId: "5e33d805-7892-4329-bda7-b524dc3fd04a",
            providerAuthenticationPatch: ProviderAuthenticationPatch(
                name: "Updated Provider",
                input: ProviderInput.openAIProviderInput(OpenAIProviderInput(apiKey: "sk-new-key-5678"))
            )
        )
        let responseBodyData = try XCTUnwrap(response.bodyData)
        let echoResponse = try CodableHelper.jsonDecoder.decode(EchoResponse.self, from: responseBodyData)

        let echoResponseBodyData = try XCTUnwrap(echoResponse.originalBodyData)
        let echoResponseBodyJSON = try XCTUnwrap(echoResponseBodyData.jsonString)

        let expectedBodyData = "{\"name\":\"Updated Provider\",\"input\":{\"apiKey\":\"sk-new-key-5678\"}}"
            .data(using: .utf8)
        let expectedBodyJSON = try XCTUnwrap(expectedBodyData?.jsonString)

        XCTAssertEqual(echoResponseBodyJSON, expectedBodyJSON)

        XCTAssertEqual(echoResponse.path, "/1/providers/5e33d805-7892-4329-bda7-b524dc3fd04a")
        XCTAssertEqual(echoResponse.method, HTTPMethod.patch)

        XCTAssertNil(echoResponse.queryParameters)
    }
}
