// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package snippets

// >IMPORT
import "github.com/algolia/algoliasearch-client-go/v4/algolia/analytics"

// IMPORT<

func SnippetForCustomDeleteOfAnalytics() {
	/*
	   Snippet for the customDelete method.

	   allow del method for a custom path with minimal parameters
	*/

	// >SEPARATOR customDelete default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.CustomDelete(client.NewApiCustomDeleteRequest(
		"test/minimal"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForCustomGetOfAnalytics() {
	/*
	   Snippet for the customGet method.

	   allow get method for a custom path with minimal parameters
	*/

	// >SEPARATOR customGet default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.CustomGet(client.NewApiCustomGetRequest(
		"test/minimal"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForCustomPostOfAnalytics() {
	/*
	   Snippet for the customPost method.

	   allow post method for a custom path with minimal parameters
	*/

	// >SEPARATOR customPost default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.CustomPost(client.NewApiCustomPostRequest(
		"test/minimal"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForCustomPutOfAnalytics() {
	/*
	   Snippet for the customPut method.

	   allow put method for a custom path with minimal parameters
	*/

	// >SEPARATOR customPut default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.CustomPut(client.NewApiCustomPutRequest(
		"test/minimal"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForGetAddToCartRateOfAnalytics() {
	/*
	   Snippet for the getAddToCartRate method.

	   get getAddToCartRate with minimal parameters
	*/

	// >SEPARATOR getAddToCartRate default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.GetAddToCartRate(client.NewApiGetAddToCartRateRequest(
		"index"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForGetAverageClickPositionOfAnalytics() {
	/*
	   Snippet for the getAverageClickPosition method.

	   get getAverageClickPosition with minimal parameters
	*/

	// >SEPARATOR getAverageClickPosition default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.GetAverageClickPosition(client.NewApiGetAverageClickPositionRequest(
		"index"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForGetClickPositionsOfAnalytics() {
	/*
	   Snippet for the getClickPositions method.

	   get getClickPositions with minimal parameters
	*/

	// >SEPARATOR getClickPositions default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.GetClickPositions(client.NewApiGetClickPositionsRequest(
		"index"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForGetClickThroughRateOfAnalytics() {
	/*
	   Snippet for the getClickThroughRate method.

	   get getClickThroughRate with minimal parameters
	*/

	// >SEPARATOR getClickThroughRate default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.GetClickThroughRate(client.NewApiGetClickThroughRateRequest(
		"index"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForGetConversionRateOfAnalytics() {
	/*
	   Snippet for the getConversionRate method.

	   get getConversationRate with minimal parameters
	*/

	// >SEPARATOR getConversionRate default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.GetConversionRate(client.NewApiGetConversionRateRequest(
		"index"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForGetNoClickRateOfAnalytics() {
	/*
	   Snippet for the getNoClickRate method.

	   get getNoClickRate with minimal parameters
	*/

	// >SEPARATOR getNoClickRate default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.GetNoClickRate(client.NewApiGetNoClickRateRequest(
		"index"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForGetNoResultsRateOfAnalytics() {
	/*
	   Snippet for the getNoResultsRate method.

	   get getNoResultsRate with minimal parameters
	*/

	// >SEPARATOR getNoResultsRate default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.GetNoResultsRate(client.NewApiGetNoResultsRateRequest(
		"index"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForGetPurchaseRateOfAnalytics() {
	/*
	   Snippet for the getPurchaseRate method.

	   get getPurchaseRate with minimal parameters
	*/

	// >SEPARATOR getPurchaseRate default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.GetPurchaseRate(client.NewApiGetPurchaseRateRequest(
		"index"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForGetRevenueOfAnalytics() {
	/*
	   Snippet for the getRevenue method.

	   get getRevenue with minimal parameters
	*/

	// >SEPARATOR getRevenue default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.GetRevenue(client.NewApiGetRevenueRequest(
		"index"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForGetSearchesCountOfAnalytics() {
	/*
	   Snippet for the getSearchesCount method.

	   get getSearchesCount with minimal parameters
	*/

	// >SEPARATOR getSearchesCount default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.GetSearchesCount(client.NewApiGetSearchesCountRequest(
		"index"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForGetSearchesNoClicksOfAnalytics() {
	/*
	   Snippet for the getSearchesNoClicks method.

	   get getSearchesNoClicks with minimal parameters
	*/

	// >SEPARATOR getSearchesNoClicks default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.GetSearchesNoClicks(client.NewApiGetSearchesNoClicksRequest(
		"index"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForGetSearchesNoResultsOfAnalytics() {
	/*
	   Snippet for the getSearchesNoResults method.

	   get getSearchesNoResults with minimal parameters
	*/

	// >SEPARATOR getSearchesNoResults default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.GetSearchesNoResults(client.NewApiGetSearchesNoResultsRequest(
		"index"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForGetStatusOfAnalytics() {
	/*
	   Snippet for the getStatus method.

	   get getStatus with minimal parameters
	*/

	// >SEPARATOR getStatus default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.GetStatus(client.NewApiGetStatusRequest(
		"index"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForGetTopCountriesOfAnalytics() {
	/*
	   Snippet for the getTopCountries method.

	   get getTopCountries with minimal parameters
	*/

	// >SEPARATOR getTopCountries default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.GetTopCountries(client.NewApiGetTopCountriesRequest(
		"index"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForGetTopFilterAttributesOfAnalytics() {
	/*
	   Snippet for the getTopFilterAttributes method.

	   get getTopFilterAttributes with minimal parameters
	*/

	// >SEPARATOR getTopFilterAttributes default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.GetTopFilterAttributes(client.NewApiGetTopFilterAttributesRequest(
		"index"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForGetTopFilterForAttributeOfAnalytics() {
	/*
	   Snippet for the getTopFilterForAttribute method.

	   get getTopFilterForAttribute with minimal parameters
	*/

	// >SEPARATOR getTopFilterForAttribute default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.GetTopFilterForAttribute(client.NewApiGetTopFilterForAttributeRequest(
		"myAttribute", "index"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForGetTopFiltersNoResultsOfAnalytics() {
	/*
	   Snippet for the getTopFiltersNoResults method.

	   get getTopFiltersNoResults with minimal parameters
	*/

	// >SEPARATOR getTopFiltersNoResults default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.GetTopFiltersNoResults(client.NewApiGetTopFiltersNoResultsRequest(
		"index"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForGetTopHitsOfAnalytics() {
	/*
	   Snippet for the getTopHits method.

	   get getTopHits with minimal parameters
	*/

	// >SEPARATOR getTopHits default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.GetTopHits(client.NewApiGetTopHitsRequest(
		"index"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForGetTopSearchesOfAnalytics() {
	/*
	   Snippet for the getTopSearches method.

	   get getTopSearches with minimal parameters
	*/

	// >SEPARATOR getTopSearches default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.GetTopSearches(client.NewApiGetTopSearchesRequest(
		"index"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForGetUsersCountOfAnalytics() {
	/*
	   Snippet for the getUsersCount method.

	   get getUsersCount with minimal parameters
	*/

	// >SEPARATOR getUsersCount default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	response, err := client.GetUsersCount(client.NewApiGetUsersCountRequest(
		"index"))
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// use the model directly
	print(response)
	// SEPARATOR<
}
func SnippetForSetClientApiKeyOfAnalytics() {
	/*
	   Snippet for the setClientApiKey method.

	   switch API key
	*/

	// >SEPARATOR setClientApiKey default
	// Initialize the client with your application region, eg. analytics.ALGOLIA_APPLICATION_REGION
	client, err := analytics.NewClient("ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", analytics.US)
	if err != nil {
		// The client can fail to initialize if you pass an invalid parameter.
		panic(err)
	}

	// Call the API
	err = client.SetClientApiKey(
		"updated-api-key")
	if err != nil {
		// handle the eventual error
		panic(err)
	}

	// >LOG
	// SEPARATOR<
}
