ClearExistingRules:
  in: query
  name: clearExistingRules
  required: false
  schema:
    type: boolean
  description: When `true`, existing rules are deleted before adding this batch. When `false`, existing rules are retained.
