# path
UserToken:
  name: userToken
  in: path
  required: true
  description: Unique identifier representing a user for which to fetch the personalization profile.
  schema:
    $ref: '../../common/schemas/SearchParams.yml#/userToken'
