openapi: 3.0.2
info:
  title: Composition API
  description: Composition API.
  version: 1.0.0
components:
  securitySchemes:
    appId:
      $ref: '../common/securitySchemes.yml#/appId'
    apiKey:
      $ref: '../common/securitySchemes.yml#/apiKey'
servers:
  - url: https://{appId}.algolia.net
    variables:
      appId:
        default: ALGOLIA_APPLICATION_ID
  - url: https://{appId}-1.algolianet.com
    variables:
      appId:
        default: ALGOLIA_APPLICATION_ID
  - url: https://{appId}-2.algolianet.com
    variables:
      appId:
        default: ALGOLIA_APPLICATION_ID
  - url: https://{appId}-3.algolianet.com
    variables:
      appId:
        default: ALGOLIA_APPLICATION_ID
  - url: https://{appId}-dsn.algolia.net
    variables:
      appId:
        default: ALGOLIA_APPLICATION_ID
security:
  - appId: []
    apiKey: []
tags:
  - name: compositions
    x-displayName: Compositions
    description: |
      Manage your compositions and composition settings.
  - name: rules
    x-displayName: Rules
    description: |
      Manage your compositions rules.
  - name: search
    x-displayName: Search
    description: Search one or more indices for matching records or facet values.
x-tagGroups:
  - name: Compositions
    tags:
      - search
paths:
  # ########################
  # ### Search Endpoints ###
  # ########################
  /1/compositions/{compositionID}/run:
    $ref: '../composition-full/paths/search/search.yml'
  /1/compositions/{compositionID}/facets/{facetName}/query:
    $ref: '../composition-full/paths/search/searchForFacetValues.yml'
