AllCops:
  DisabledByDefault: false
  NewCops: enable

Style/HashSyntax:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
  EnforcedStyle: always

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/Documentation:
  Enabled: false

# This is very low to split the parameters on multiple lines
Layout/LineLength:
  Enabled: true
  Max: 100

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/IndentationWidth:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Layout/FirstArgumentIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/HashAlignment:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/MultilineMethodCallBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/MultilineArrayBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: compact

Layout/ClosingParenthesisIndentation:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Exclude:
    - 'algolia.gemspec'

Gemspec/RequiredRubyVersion:
  Exclude:
    - 'algolia.gemspec'

Lint/DuplicateMethods:
  Enabled: false

Lint/SymbolConversion:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Metrics/BlockNesting:
  Max: 4

Metrics/ParameterLists:
  Max: 7

Security/CompoundHash:
  Enabled: false
