/**
 * Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be
 * lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
 */
package com.algolia.client.model.search

import kotlinx.serialization.*
import kotlinx.serialization.builtins.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Whether NeuralSearch is active for the index. - `inactive`: keyword-only search is returned for
 * live traffic. - `active`: NeuralSearch (keyword + semantic) is returned for live traffic. -
 * `preview`: NeuralSearch runs alongside keyword search for comparison without affecting live
 * results.
 */
@Serializable
public enum class NeuralSearchMode(public val value: kotlin.String) {

  @SerialName(value = "inactive") Inactive("inactive"),
  @SerialName(value = "active") Active("active"),
  @SerialName(value = "preview") Preview("preview");

  override fun toString(): kotlin.String = value
}
