name: Setup

description: Setup CI environment.

outputs:
  TESTS_CHANGED:
    description: 'Determine if the `tests` folder is different on the `main` branch.'
    value: ${{ steps.diff.outputs.TESTS_CHANGED > 0 }}
  SPECS_CHANGED:
    description: 'Determine if the `specs` folder is different on the `main` branch.'
    value: ${{ steps.diff.outputs.SPECS_CHANGED > 0 }}
  SCRIPTS_CHANGED:
    description: 'Determine if the `scripts` folder is different on the `main` branch.'
    value: ${{ steps.diff.outputs.SCRIPTS_CHANGED > 0 }}
  JS_CLIENT_CHANGED:
    description: 'Determine if the `clients/algoliasearch-client-javascript` folder is different on the `main` branch.'
    value: ${{ steps.diff.outputs.JS_CLIENT_CHANGED > 0 }}
  JS_TEMPLATE_CHANGED:
    description: 'Determine if the `templates/javascript` folder is different on the `main` branch.'
    value: ${{ steps.diff.outputs.JS_TEMPLATE_CHANGED > 0 }}
  JAVA_CLIENT_CHANGED:
    description: 'Determine if the `clients/algoliasearch-client-java-2` folder is different on the `main` branch.'
    value: ${{ steps.diff.outputs.JAVA_CLIENT_CHANGED > 0 }}
  JAVA_TEMPLATE_CHANGED:
    description: 'Determine if the `templates/java` folder is different on the `main` branch.'
    value: ${{ steps.diff.outputs.JAVA_TEMPLATE_CHANGED > 0 }}
  RUN_SPECS:
    description: 'Determine if the `specs` job should run'
    value: ${{ steps.diff.outputs.SPECS_CHANGED > 0 }}
  RUN_JS_CLIENT:
    description: 'Determine if the `client_javascript` job should run'
    value: |
      ${{
        steps.diff.outputs.SPECS_CHANGED > 0 ||
        steps.diff.outputs.JS_CLIENT_CHANGED > 0 ||
        steps.diff.outputs.JS_TEMPLATE_CHANGED> 0 
      }}
  RUN_JAVA_CLIENT:
    description: 'Determine if the `client_java` job should run'
    value: |
      ${{
        steps.diff.outputs.SPECS_CHANGED > 0 ||
        steps.diff.outputs.JAVA_CLIENT_CHANGED > 0 ||
        steps.diff.outputs.JAVA_TEMPLATE_CHANGED> 0 
      }}
  RUN_CTS:
    description: 'Determine if the `cts` job should run'
    value: |
      ${{
        steps.diff.outputs.SPECS_CHANGED > 0 ||
        steps.diff.outputs.CTS_CHANGED > 0 ||
        steps.diff.outputs.JAVA_CLIENT_CHANGED > 0 ||
        steps.diff.outputs.JAVA_TEMPLATE_CHANGED> 0 
      }}

runs:
  using: composite
  steps:
    - name: Restore cache
      uses: ./.github/actions/cache

    - name: Install Java
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 11.0.4

    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version-file: .nvmrc

    - name: Install JavaScript Dependencies
      shell: bash
      run: yarn install

    - name: Setting diff outputs variables
      id: diff
      shell: bash
      run: |
        echo "::set-output name=SPECS_CHANGED::$(git diff --shortstat origin/${{ github.base_ref }}..HEAD -- specs | wc -l)"
        echo "::set-output name=TESTS_CHANGED::$(git diff --shortstat origin/${{ github.base_ref }}..HEAD -- tests | wc -l)"
        echo "::set-output name=SCRIPTS_CHANGED::$(git diff --shortstat origin/${{ github.base_ref }}..HEAD -- scripts | wc -l)"
        echo "::set-output name=JS_CLIENT_CHANGED::$(git diff --shortstat origin/${{ github.base_ref }}..HEAD -- clients/algoliasearch-client-javascript | wc -l)"
        echo "::set-output name=JS_TEMPLATE_CHANGED::$(git diff --shortstat origin/${{ github.base_ref }}..HEAD -- templates/javascript | wc -l)"
        echo "::set-output name=JAVA_CLIENT_CHANGED::$(git diff --shortstat origin/${{ github.base_ref }}..HEAD -- clients/algoliasearch-client-java-2 | wc -l)"
        echo "::set-output name=JAVA_TEMPLATE_CHANGED::$(git diff --shortstat origin/${{ github.base_ref }}..HEAD -- templates/java | wc -l)"
