name: Setup

description: Setup CI environment.

inputs:
  type:
    description: Type of setup, `minimal` will only setup the JavaScript monorepo, empty will also install Java.
    required: false
  language:
    description: the language for which to install deps
    required: false

runs:
  using: composite
  steps:
    # Java for code generation
    - name: Install Java
      if: inputs.type != 'minimal'
      uses: actions/setup-java@v4.2.1
      with:
        distribution: zulu
        java-version-file: config/.java-version

    - name: Validate gradle wrapper
      if: inputs.type != 'minimal'
      uses: gradle/wrapper-validation-action@v2

    - name: Setup gradle
      if: inputs.type != 'minimal'
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: false

    - name: Download Java formatter
      if: inputs.type != 'minimal'
      shell: bash
      run: curl --retry 3 -L "https://github.com/google/google-java-format/releases/download/v1.22.0/google-java-format-1.22.0-all-deps.jar" > /tmp/java-formatter.jar

    # JavaScript for monorepo and tooling
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: yarn

    - name: Get yarn cache directory path
      shell: bash
      id: yarn-cache-dir
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Restore Yarn
      uses: actions/cache@v4
      with:
        path: ${{ steps.yarn-cache-dir.outputs.dir || '.yarn/cache' }}
        key: yarn-cache-monorepo-${{ hashFiles('yarn.lock') }}

    - name: Install JavaScript dependencies
      shell: bash
      run: YARN_ENABLE_HARDENED_MODE=0 yarn install

    - name: Build scripts
      shell: bash
      run: yarn workspace scripts build:cli

    - name: Get all languages versions
      id: versions
      shell: bash
      run: |
        # remove patch from php version
        echo "CSHARP_VERSION=$(cat config/.csharp-version)" >> $GITHUB_OUTPUT
        echo "DART_VERSION=$(cat config/.dart-version)" >> $GITHUB_OUTPUT
        echo "GO_VERSION=$(cat config/.go-version)" >> $GITHUB_OUTPUT
        echo "PHP_VERSION=$(cat config/.php-version | cut -d '.' -f 1,2)" >> $GITHUB_OUTPUT
        echo "PYTHON_VERSION=$(cat config/.python-version)" >> $GITHUB_OUTPUT
        echo "RUBY_VERSION=$(cat config/.ruby-version)" >> $GITHUB_OUTPUT
        echo "SWIFT_VERSION=$(cat config/.swift-version)" >> $GITHUB_OUTPUT

    # JavaScript client deps
    - name: Get yarn js-client cache directory path
      if: ${{ inputs.language == 'javascript' }}
      shell: bash
      id: yarn-cache-dir-client
      run: echo "dir=$(cd clients/algoliasearch-client-javascript && yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Restore Yarn js-client
      if: ${{ inputs.language == 'javascript' }}
      uses: actions/cache@v4
      with:
        path: ${{ steps.yarn-cache-dir-client.outputs.dir || 'clients/algoliasearch-client-javascript/.yarn/cache' }}
        key: yarn-cache-clients-${{ hashFiles('clients/algoliasearch-client-javascript/yarn.lock') }}

    - name: Cache js-client node modules
      if: ${{ inputs.language == 'javascript' }}
      uses: actions/cache@v4
      with:
        path: clients/algoliasearch-client-javascript/node_modules
        key: node-modules-clients-${{ hashFiles('clients/algoliasearch-client-javascript/yarn.lock') }}

    - name: Install JavaScript client dependencies
      if: ${{ inputs.language == 'javascript' }}
      shell: bash
      run: cd clients/algoliasearch-client-javascript && YARN_ENABLE_HARDENED_MODE=0 YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install

    # PHP
    - name: Install PHP
      if: ${{ inputs.language == 'php' }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ steps.versions.outputs.PHP_VERSION }}
        tools: composer

    - name: Run composer install
      if: ${{ inputs.language == 'php' }}
      shell: bash
      run: |
        composer install --working-dir=clients/algoliasearch-client-php
        composer dump-autoload --working-dir=clients/algoliasearch-client-php

    # Golang
    - name: Install golang
      if: ${{ inputs.language == 'go' }}
      uses: actions/setup-go@v5
      with:
        cache-dependency-path: clients/algoliasearch-client-go/go.sum
        go-version: ${{ steps.versions.outputs.GO_VERSION }}

    - name: Install golangci-lint
      if: ${{ inputs.language == 'go' }}
      shell: bash
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        go install golang.org/x/tools/cmd/goimports@latest

    - name: Cache golangci-lint analysis
      if: ${{ inputs.language == 'go' }}
      uses: actions/cache@v4
      with:
        path: ~/.cache/golangci-lint
        key: golangci-lint-${{ steps.versions.outputs.GO_VERSION }}-${{ hashFiles('clients/algoliasearch-client-go/go.sum') }}

    # Kotlin
    - name: Cache spotless
      if: ${{ inputs.language == 'kotlin' }}
      uses: actions/cache@v4
      with:
        path: clients/algoliasearch-client-kotlin/client/build/spotless
        key: spotless-${{ hashFiles('clients/algoliasearch-client-kotlin/build.gradle.kts') }}

    # Dart
    - name: Install dart
      if: ${{ inputs.language == 'dart' }}
      uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{ steps.versions.outputs.DART_VERSION }}

    - name: Setup dart tools
      if: ${{ inputs.language == 'dart' }}
      shell: bash
      run: dart pub global activate melos

    # Python
    - name: Install poetry
      if: ${{ inputs.language == 'python' }}
      shell: bash
      run: pipx install poetry

    - uses: actions/setup-python@v5
      if: ${{ inputs.language == 'python' }}
      with:
        python-version: ${{ steps.versions.outputs.PYTHON_VERSION }}
        cache: 'poetry'

    - run: poetry install
      if: ${{ inputs.language == 'python' }}
      working-directory: clients/algoliasearch-client-python
      shell: bash

    # Ruby
    - name: Install Ruby
      if: ${{ inputs.language == 'ruby' }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ steps.versions.outputs.RUBY_VERSION }}
        bundler-cache: true

    # Csharp
    - name: Install dotnet
      if: ${{ inputs.language == 'csharp' }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ steps.versions.outputs.CSHARP_VERSION }}

    # Swift deps
    - name: Install swift
      if: ${{ inputs.language == 'swift' }}
      # WORKAROUND for: https://github.com/swift-actions/setup-swift/issues/591
      # BY GitHub Staff developer: redsun82
      # IN pull request: https://github.com/github/codeql/pull/16153
      # uses: swift-actions/setup-swift@v2
      uses: redsun82/setup-swift@b2b6f77ab14f6a9b136b520dc53ec8eca27d2b99
      with:
        swift-version: ${{ steps.versions.outputs.SWIFT_VERSION }}

    - name: Checkout swiftformat
      if: ${{ inputs.language == 'swift' }}
      uses: actions/checkout@v4
      with:
        repository: nicklockwood/SwiftFormat
        ref: 0.53.0
        path: swiftformat

    - name: Cache the build folder
      id: cache-swiftformat
      if: ${{ inputs.language == 'swift' }}
      uses: actions/cache@v4
      with:
        path: swiftformat/.build
        key: swiftformat-build-0.53.0-${{ runner.os }}

    - name: Build swiftformat
      if: ${{ inputs.language == 'swift' && steps.cache-swiftformat.outputs.cache-hit != 'true' }}
      shell: bash
      run: cd swiftformat && swift build -c release

    - name: Setup the path
      if: ${{ inputs.language == 'swift' }}
      shell: bash
      run: echo "$(pwd)/swiftformat/.build/release" >> $GITHUB_PATH
