name: Setup

description: Setup CI environment.

runs:
  using: composite
  steps:
    # - name: Restore cache
    #   uses: ./.github/actions/cache

    # - name: Install Java
    #   uses: actions/setup-java@v2
    #   with:
    #     distribution: zulu
    #     java-version: 11.0.4

    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version-file: .nvmrc

    # - name: Install JavaScript Dependencies
    #   shell: bash
    #   run: yarn install

    - name: Setting global diff variables
      shell: bash
      run: |
        echo "SPECS_CHANGED=$(git diff --exit-code $GITHUB_BASE_REF -- specs | echo $?)" >> $GITHUB_ENV
        echo "TEMPLATES_CHANGED=$(git diff --exit-code $GITHUB_BASE_REF -- templates | echo $?)" >> $GITHUB_ENV
        echo "TESTS_CHANGED=$(git diff --exit-code $GITHUB_BASE_REF -- tests | echo $?)" >> $GITHUB_ENV
        echo "SCRIPTS_CHANGED=$(git diff --exit-code $GITHUB_BASE_REF -- scripts | echo $?)" >> $GITHUB_ENV

    - name: Setting clients diff variables
      shell: bash
      run: |
        echo "JS_CLIENT_CHANGED=$(git diff --exit-code $GITHUB_BASE_REF -- clients/algoliasearch-client-java-2 | echo $?)" >> $GITHUB_ENV
        echo "JAVA_CLIENT_CHANGED=$(git diff --exit-code $GITHUB_BASE_REF -- clients/algoliasearch-client-javascript | echo $?)" >> $GITHUB_ENV
