get:
  tags:
    - tasks
  x-acl:
    - addObject
    - deleteIndex
    - editSettings
  summary: Retrieve a task
  description: Retrieves a task by its ID.
  operationId: getTask
  parameters:
    - $ref: '../../../common/parameters.yml#/pathTaskID'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../../../common/schemas/task.yml#/Task'
    '400':
      $ref: '../../../../common/responses/BadRequest.yml'

put:
  tags:
    - tasks
  x-acl:
    - addObject
    - deleteIndex
    - editSettings
  summary: Fully update a task
  description: Fully updates a task by its ID, use partialUpdateTask if you only want to update a subset of fields.
  operationId: replaceTask
  parameters:
    - $ref: '../../../common/parameters.yml#/pathTaskID'
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../../../common/schemas/task.yml#/TaskReplace'
    required: true
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../../../common/schemas/task.yml#/TaskUpdateResponse'
    '400':
      $ref: '../../../../common/responses/BadRequest.yml'

# TODO: rename taskUpdate to taskPartialUpdate next major
patch:
  tags:
    - tasks
  x-acl:
    - addObject
    - deleteIndex
    - editSettings
  summary: Partially update a task
  description: Partially updates a task by its ID.
  operationId: updateTask
  parameters:
    - $ref: '../../../common/parameters.yml#/pathTaskID'
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../../../common/schemas/task.yml#/TaskUpdate'
    required: true
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../../../common/schemas/task.yml#/TaskUpdateResponse'
    '400':
      $ref: '../../../../common/responses/BadRequest.yml'

delete:
  tags:
    - tasks
  x-acl:
    - addObject
    - deleteIndex
    - editSettings
  summary: Delete a task
  description: Deletes a task by its ID.
  operationId: deleteTask
  parameters:
    - $ref: '../../../common/parameters.yml#/pathTaskID'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../../../common/schemas/common.yml#/DeleteResponse'
    '400':
      $ref: '../../../../common/responses/BadRequest.yml'
