openapi: 3.0.2
info:
  title: Collections API
  description: |
    The Algolia Collections API lets you create and curate product listings.

    ## Client libraries

    Use Algolia's API clients and libraries to reliably integrate Algolia's APIs with your apps.

    See: [Algolia's ecosystem](https://www.algolia.com/doc/guides/getting-started/how-algolia-works/in-depth/ecosystem/)

    ## Base URLs

    The base URL for requests to the Collections API is:

    - `https://experiences.algolia.com`
    
    **All requests must use HTTPS.**

    ## Availability and authentication

    Access to the Collections API is available as part of the [Premium or Elevate plans](https://www.algolia.com/pricing).

    To authenticate your API requests, add these headers:

    - `x-algolia-application-id`. Your Algolia application ID.
    - `x-algolia-api-key`. An API key with the necessary permissions to make the request.
      The required access control list (ACL) to make a request is listed in each endpoint's reference.

    You can find your application ID and API key in the [Algolia dashboard](https://dashboard.algolia.com/account).

    ## Rate limits

    You can make up to **150 requests per minute per app** to the Collections API.

    ## Request format

    Depending on the endpoint, request bodies are either JSON objects or arrays of JSON objects,

    ## Parameters

    Parameters are passed as query parameters for GET and DELETE requests,
    and in the request body for POST and PUT requests.

    Query parameters must be [URL-encoded](https://developer.mozilla.org/en-US/docs/Glossary/Percent-encoding).
    Non-ASCII characters must be UTF-8 encoded.
    Plus characters (`+`) are interpreted as spaces.
    Arrays as query parameters must be one of:

    - A comma-separated string: `attributesToRetrieve=title,description`
    - A URL-encoded JSON array: `attributesToRetrieve=%5B%22title%22,%22description%22%D`

    ## Response status and errors

    The Collections API returns JSON responses.
    Since JSON doesn't guarantee any specific ordering, don't rely on the order of attributes in the API response.

    Successful responses return a `2xx` status. Client errors return a `4xx` status. Server errors are indicated by a `5xx` status.
    Error responses have a `message` property with more information.

    ## Version

    The current version of the Collections API is version 1, as indicated by the `/1/` in each endpoint's URL.

  version: 1.0.0
components:
  securitySchemes:
    appId:
      $ref: '../common/securitySchemes.yml#/appId'
    apiKey:
      $ref: '../common/securitySchemes.yml#/apiKey'
servers:
  - url: https://experiences.algolia.com
security:
  - appId: []
    apiKey: []
tags: []
x-tagGroups: []
paths:
  # ######################
  # ### Custom request ###
  # ######################
  /{path}:
    $ref: '../common/paths/customRequest.yml'

  # #############################
  # ### Collections Endpoints ###
  # #############################
  /1/collections:
    $ref: 'paths/collections.yml'
  /1/collections/{collectionID}:
    $ref: 'paths/collectionID.yml'
  /1/collections/{collectionID}/commit:
    $ref: 'paths/commitCollection.yml'
