compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.2.cjs

# esbuild use native binaries, we need both to work locally and on the CI.
supportedArchitectures:
  os:
    - darwin
    - linux
