services:
  base:
    image: ${APIC_BASE_TAG:-apic-base:latest}
    build:
      context: .
      dockerfile: scripts/docker/Dockerfile.base
      args:
        - CSHARP_VERSION=${CSHARP_VERSION}
        - DART_VERSION=${DART_VERSION}
        - GO_VERSION=${GO_VERSION}
        - JAVA_VERSION=${JAVA_VERSION}
        - NODE_VERSION=${NODE_VERSION}
        - PHP_VERSION=${PHP_VERSION}
        - PYTHON_VERSION=${PYTHON_VERSION}
    command: tail -f /dev/null
    volumes: [./:/app]
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ruby:
    image: ${APIC_RUBY_TAG:-apic-ruby:latest}
    build:
      context: .
      dockerfile: scripts/docker/Dockerfile.ruby
      args:
        - JAVA_VERSION=${JAVA_VERSION}
        - NODE_VERSION=${NODE_VERSION}
        - RUBY_VERSION=${RUBY_VERSION}
    command: tail -f /dev/null
    volumes: [./:/app]
    extra_hosts:
      - "host.docker.internal:host-gateway"

  swift:
    image: ${APIC_SWIFT_TAG:-apic-swift:latest}
    build:
      context: .
      dockerfile: scripts/docker/Dockerfile.swift
      args:
        - JAVA_VERSION=${JAVA_VERSION}
        - NODE_VERSION=${NODE_VERSION}
        - SWIFT_VERSION=${SWIFT_VERSION}
    command: tail -f /dev/null
    volumes: [./:/app]
    extra_hosts:
      - "host.docker.internal:host-gateway"
