services:
  base:
    container_name: apic_base
    build:
      context: .
      dockerfile: scripts/docker/Dockerfile.base
      args:
        - JAVA_VERSION=${JAVA_VERSION}
    command: tail -f /dev/null
    volumes: [./:/app]
    ports:
      - "5009:5009" # So we can debug the OpenAPI Generator process

  ruby:
    container_name: apic_ruby
    build:
      context: .
      dockerfile: scripts/docker/Dockerfile.ruby
    command: tail -f /dev/null
    volumes: [./:/app]

  swift:
    container_name: apic_swift
    build:
      context: .
      dockerfile: scripts/docker/Dockerfile.swift
    command: tail -f /dev/null
    volumes: [./:/app]
