AllCops:
  DisabledByDefault: false
  NewCops: enable

Style/HashSyntax:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
  EnforcedStyle: always

Style/WordArray:
  Enabled: false

Layout/LineLength:
  Max: 180
