// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element

import 'package:json_annotation/json_annotation.dart';

part 'fetched_index_ab_test_target.g.dart';

@JsonSerializable()
final class FetchedIndexAbTestTarget {
  /// Returns a new [FetchedIndexAbTestTarget] instance.
  const FetchedIndexAbTestTarget({
    required this.indexName,
  });

  /// Index name to match. Use `*` to target the entire application.
  @JsonKey(name: r'indexName')
  final String indexName;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FetchedIndexAbTestTarget && other.indexName == indexName;

  @override
  int get hashCode => indexName.hashCode;

  factory FetchedIndexAbTestTarget.fromJson(Map<String, dynamic> json) =>
      _$FetchedIndexAbTestTargetFromJson(json);

  Map<String, dynamic> toJson() => _$FetchedIndexAbTestTargetToJson(this);

  @override
  String toString() {
    return toJson().toString();
  }
}
