// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element
import 'package:algolia_client_search/src/model/updated_at_response.dart';
import 'package:algolia_client_search/src/model/watch_response.dart';

import 'package:json_annotation/json_annotation.dart';

part 'replace_all_objects_with_transformation_response.g.dart';

@JsonSerializable()
final class ReplaceAllObjectsWithTransformationResponse {
  /// Returns a new [ReplaceAllObjectsWithTransformationResponse] instance.
  const ReplaceAllObjectsWithTransformationResponse({
    required this.copyOperationResponse,
    required this.watchResponses,
    required this.moveOperationResponse,
  });

  @JsonKey(name: r'copyOperationResponse')
  final UpdatedAtResponse copyOperationResponse;

  /// The response of the `push` request(s).
  @JsonKey(name: r'watchResponses')
  final List<WatchResponse> watchResponses;

  @JsonKey(name: r'moveOperationResponse')
  final UpdatedAtResponse moveOperationResponse;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReplaceAllObjectsWithTransformationResponse &&
          other.copyOperationResponse == copyOperationResponse &&
          other.watchResponses == watchResponses &&
          other.moveOperationResponse == moveOperationResponse;

  @override
  int get hashCode =>
      copyOperationResponse.hashCode +
      watchResponses.hashCode +
      moveOperationResponse.hashCode;

  factory ReplaceAllObjectsWithTransformationResponse.fromJson(
          Map<String, dynamic> json) =>
      _$ReplaceAllObjectsWithTransformationResponseFromJson(json);

  Map<String, dynamic> toJson() =>
      _$ReplaceAllObjectsWithTransformationResponseToJson(this);

  @override
  String toString() {
    return toJson().toString();
  }
}
