// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element
import 'package:algolia_client_search/src/model/search_params_object.dart';

import 'package:json_annotation/json_annotation.dart';

part 'secured_api_key_restrictions.g.dart';

@JsonSerializable()
final class SecuredApiKeyRestrictions {
  /// Returns a new [SecuredApiKeyRestrictions] instance.
  const SecuredApiKeyRestrictions({
    this.searchParams,
    this.filters,
    this.validUntil,
    this.restrictIndices,
    this.restrictSources,
    this.userToken,
  });

  @JsonKey(name: r'searchParams')
  final SearchParamsObject? searchParams;

  /// Filters that apply to every search made with the secured API key. Extra filters added at search time will be combined with `AND`. For example, if you set `group:admin` as fixed filter on your generated API key, and add `groups:visitors` to the search query, the complete set of filters will be `group:admin AND groups:visitors`.
  @JsonKey(name: r'filters')
  final String? filters;

  /// Timestamp when the secured API key expires, measured in seconds since the Unix epoch.
  @JsonKey(name: r'validUntil')
  final int? validUntil;

  /// Index names or patterns that this API key can access. By default, an API key can access all indices in the same application.  You can use leading and trailing wildcard characters (`*`):  - `dev_*` matches all indices starting with \"dev_\" - `*_dev` matches all indices ending with \"_dev\" - `*_products_*` matches all indices containing \"_products_\".
  @JsonKey(name: r'restrictIndices')
  final List<String>? restrictIndices;

  /// IP network that are allowed to use this key.  You can only add a single source, but you can provide a range of IP addresses. Use this to protect against API key leaking and reuse.
  @JsonKey(name: r'restrictSources')
  final String? restrictSources;

  /// Pseudonymous user identifier to restrict usage of this API key to specific users.  By default, rate limits are set based on IP addresses. This can be an issue if many users search from the same IP address. To avoid this, add a user token to each generated API key.
  @JsonKey(name: r'userToken')
  final String? userToken;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SecuredApiKeyRestrictions &&
          other.searchParams == searchParams &&
          other.filters == filters &&
          other.validUntil == validUntil &&
          other.restrictIndices == restrictIndices &&
          other.restrictSources == restrictSources &&
          other.userToken == userToken;

  @override
  int get hashCode =>
      searchParams.hashCode +
      filters.hashCode +
      validUntil.hashCode +
      restrictIndices.hashCode +
      restrictSources.hashCode +
      userToken.hashCode;

  factory SecuredApiKeyRestrictions.fromJson(Map<String, dynamic> json) =>
      _$SecuredApiKeyRestrictionsFromJson(json);

  Map<String, dynamic> toJson() => _$SecuredApiKeyRestrictionsToJson(this);

  @override
  String toString() {
    return toJson().toString();
  }
}
