/** Algolia Monitoring API The Monitoring API lets you check the status and performance of your Algolia infrastructure.
  * > **Note**: The Monitoring API is available on [Premium plans](https://www.algolia.com/pricing/) and plans including
  * the Enterprise add-on.
  *
  * The version of the OpenAPI document: 1.0.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package algoliasearch.monitoring

object Metric extends Enumeration {
  type Metric = Metric.Value
  val AvgBuildTime = Value("avg_build_time")
  val SsdUsage = Value("ssd_usage")
  val RamSearchUsage = Value("ram_search_usage")
  val RamIndexingUsage = Value("ram_indexing_usage")
  val CpuUsage = Value("cpu_usage")
  val Star = Value("*")
}
