// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

package com.algolia.model.agentstudio;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.util.Objects;

/** AlgoliaSearchToolIndexConfigInput */
public class AlgoliaSearchToolIndexConfigInput {

  @JsonProperty("index")
  private String index;

  @JsonProperty("description")
  private String description;

  @JsonProperty("enhancedDescription")
  private String enhancedDescription;

  @JsonProperty("searchParameters")
  private SearchParametersInput searchParameters;

  @JsonProperty("searchControls")
  private IndexSearchParametersInput searchControls;

  public AlgoliaSearchToolIndexConfigInput setIndex(String index) {
    this.index = index;
    return this;
  }

  /** Get index */
  @javax.annotation.Nonnull
  public String getIndex() {
    return index;
  }

  public AlgoliaSearchToolIndexConfigInput setDescription(String description) {
    this.description = description;
    return this;
  }

  /** Get description */
  @javax.annotation.Nonnull
  public String getDescription() {
    return description;
  }

  public AlgoliaSearchToolIndexConfigInput setEnhancedDescription(String enhancedDescription) {
    this.enhancedDescription = enhancedDescription;
    return this;
  }

  /** Get enhancedDescription */
  @javax.annotation.Nullable
  public String getEnhancedDescription() {
    return enhancedDescription;
  }

  public AlgoliaSearchToolIndexConfigInput setSearchParameters(SearchParametersInput searchParameters) {
    this.searchParameters = searchParameters;
    return this;
  }

  /** Get searchParameters */
  @javax.annotation.Nullable
  public SearchParametersInput getSearchParameters() {
    return searchParameters;
  }

  public AlgoliaSearchToolIndexConfigInput setSearchControls(IndexSearchParametersInput searchControls) {
    this.searchControls = searchControls;
    return this;
  }

  /** Get searchControls */
  @javax.annotation.Nullable
  public IndexSearchParametersInput getSearchControls() {
    return searchControls;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlgoliaSearchToolIndexConfigInput algoliaSearchToolIndexConfigInput = (AlgoliaSearchToolIndexConfigInput) o;
    return (
      Objects.equals(this.index, algoliaSearchToolIndexConfigInput.index) &&
      Objects.equals(this.description, algoliaSearchToolIndexConfigInput.description) &&
      Objects.equals(this.enhancedDescription, algoliaSearchToolIndexConfigInput.enhancedDescription) &&
      Objects.equals(this.searchParameters, algoliaSearchToolIndexConfigInput.searchParameters) &&
      Objects.equals(this.searchControls, algoliaSearchToolIndexConfigInput.searchControls)
    );
  }

  @Override
  public int hashCode() {
    return Objects.hash(index, description, enhancedDescription, searchParameters, searchControls);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlgoliaSearchToolIndexConfigInput {\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    enhancedDescription: ").append(toIndentedString(enhancedDescription)).append("\n");
    sb.append("    searchParameters: ").append(toIndentedString(searchParameters)).append("\n");
    sb.append("    searchControls: ").append(toIndentedString(searchControls)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
