openapi: 3.1.0
info:
  title: Realtime Personalization API
  description: TODO
  version: 0.0.1
externalDocs:
  # TODO: Update the URL
  url: https://www.algolia.com/doc/guides/personalization/what-is-personalization/
  description: |
    Related guide: Algolia Realtime Personalization.
components:
  securitySchemes:
    appId:
      $ref: '../common/securitySchemes.yml#/appId'
    apiKey:
      $ref: '../common/securitySchemes.yml#/apiKey'
servers:
  - url: https://ai-personalization.{region}.algolia.com
    variables:
      region:
        enum:
          - us
          - eu
        default: us
security:
  - appId: []
    apiKey: []
tags:
  - name: filters
    x-displayName: Filters
    description: |
      Filters are used to personalize the search results for a user.
      They are used to filter the search results based on the user's preferences.
x-tagGroups:
  - name: General
    tags:
      - filters
paths:
  # ######################
  # ### Custom request ###
  # ######################

  /2/realtime/{userToken}:
    $ref: 'paths/getPersonalizationFilters.yml'
