openapi: 3.0.2
info:
  title: Recommend API
  description: |-
    Use the Recommend REST API  to manage your reecommendation and trending models.

    Although Algolia provides a REST API, you should use the official open source API [clients, libraries, and tools](https://www.algolia.com/doc/guides/getting-started/how-algolia-works/in-depth/ecosystem/) instead.
    There's no [SLA](https://www.algolia.com/policies/sla/) if you use the REST API directly.
  version: 1.0.0
components:
  securitySchemes:
    appId:
      $ref: '../common/securitySchemes.yml#/appId'
    apiKey:
      $ref: '../common/securitySchemes.yml#/apiKey'
servers:
  - url: https://{appId}.algolianet.com
    variables:
      appId:
        default: myAppId
  - url: https://{appId}-1.algolianet.com
    variables:
      appId:
        default: myAppId
  - url: https://{appId}-2.algolianet.com
    variables:
      appId:
        default: myAppId
  - url: https://{appId}-3.algolianet.com
    variables:
      appId:
        default: myAppId
  - url: https://{appId}-dsn.algolianet.com
    variables:
      appId:
        default: myAppId
security:
  - appId: []
    apiKey: []
tags:
  - name: recommendations
    x-displayName: Recommendation and trending models
    description: Manage recommendations.
x-tagGroups:
  - name: General
    tags:
      - recommendations
paths:
  # ######################
  # ### Custom request ###
  # ######################
  /1{path}:
    $ref: '../common/paths/customRequest.yml'

  /1/indexes/*/recommendations:
    $ref: 'paths/getRecommendations.yml'
