openapi: 3.0.2
info:
  title: Recommend API
  description: API powering the Recommend feature of Algolia.
  version: 0.0.1
components:
  securitySchemes:
    appId:
      $ref: '../common/securitySchemes/common.yml#/appId'
    apiKey:
      $ref: '../common/securitySchemes/common.yml#/apiKey'
security:
  - appId: []
    apiKey: []
paths:
  /1/indexes/*/recommendations:
    $ref: './paths/getRecommendations.yml'
