openapi: 3.0.2
info:
  title: Crawler API
  description: |
    The Crawler REST API lets your interact directly with your crawlers.

    !> The Crawler REST API is only available if you have access to the Crawler.

  version: 1.0.0
servers:
  - url: https://crawler.algolia.com/api/1
security:
  - BasicAuth: []
tags:
  - name: config
    x-displayName: Config
    description: Manage configuration.
  - name: crawler
    description: API reference.
    x-displayName: API reference
  - name: crawlers
    x-displayName: Crawlers
    description: Manage crawlers.
  - name: domains
    x-displayName: Domains
    description: Manage domains.
  - name: one_crawler
    x-displayName: Crawler
    description: Manage one crawler.
  - name: tasks
    x-displayName: Tasks
    description: Manage tasks.
x-tagGroups:
  - name: Crawlers
    tags:
      - crawlers
  - name: Crawler
    tags:
      - one_crawler
      - config
      - tasks
  - name: Global
    tags:
      - domains
paths:
  /crawlers:
    $ref: 'paths/crawlers/main.yml'

  /crawlers/{id}:
    $ref: 'paths/crawler/main.yml'

  /crawlers/{id}/config:
    $ref: 'paths/crawler/config/patch.yml'

  /crawlers/{id}/run:
    $ref: 'paths/crawler/run.yml'

  /crawlers/{id}/pause:
    $ref: 'paths/crawler/pause.yml'

  /crawlers/{id}/reindex:
    $ref: 'paths/crawler/reindex.yml'

  /crawlers/{id}/stats/urls:
    $ref: 'paths/crawler/stats.yml'

  /crawlers/{id}/test:
    $ref: 'paths/crawler/test.yml'

  /crawlers/{id}/tasks/{tid}:
    $ref: 'paths/crawler/tasks/get.yml'

  /crawlers/{id}/tasks/{tid}/cancel:
    $ref: 'paths/crawler/tasks/cancel.yml'

  /crawlers/{id}/config/versions:
    $ref: 'paths/crawler/config/versions.yml'

  /crawlers/{id}/config/versions/{version}:
    $ref: 'paths/crawler/config/version.yml'

  /crawlers/{id}/urls/crawl:
    $ref: 'paths/crawler/crawl.yml'

  /domains:
    $ref: 'paths/domains/list.yml'

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
