get:
  tags:
    - configurations
  operationId: getConfigStatus
  x-acl:
    - settings
  summary: Retrieve configuration status.
  description: Reports the status of a Query Suggestions index.
  parameters:
    - $ref: '../common/parameters.yml#/IndexName'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              indexName:
                $ref: '../common/schemas/QuerySuggestionsIndexName.yml'
              isRunning:
                type: boolean
                description: Whether the creation or update of the Query Suggestions index is in progress.
                example: false
              lastBuiltAt:
                type: string
                description: Date and time when the Query Suggestions index was last built, in RFC 3339 format.
                example: 2023-07-05T08:03:53Z
              lastSuccessfulBuiltAt:
                type: string
                description: Date and time when the Query Suggestions index was last updated successfully.
                example: 2023-07-05T08:03:53Z
              lastSuccessfulBuildDuration:
                type: string
                description: Duration of the last successful build in seconds.
                example: 28
    '401':
      $ref: '../common/responses/Unauthorized.yml'
    '404':
      $ref: '../common/responses/NotFound.yml'
