get:
  tags:
    - configurations
  operationId: getConfig
  x-acl:
    - settings
  summary: Retrieve a configuration
  description: Retrieves a single Query Suggestions configuration by its index name.
  parameters:
    - $ref: '../common/parameters.yml#/IndexName'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../common/responses/QuerySuggestionsConfigurationResponse.yml#/QuerySuggestionsConfigurationResponse'
    '400':
      $ref: '../common/responses/BadRequest.yml'
    '401':
      $ref: '../common/responses/Unauthorized.yml'
    '404':
      $ref: '../common/responses/NotFound.yml'

put:
  tags:
    - configurations
  operationId: updateConfig
  x-acl:
    - editSettings
  summary: Update a configuration
  description: Updates a QuerySuggestions configuration.
  parameters:
    - $ref: '../common/parameters.yml#/IndexName'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../common/schemas/QuerySuggestionsConfiguration.yml#/QuerySuggestionsConfiguration'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../common/responses/BaseResponse.yml'
          examples:
            Created:
              summary: Configuration created
              value:
                'status': 200
                'message': 'Configuration was updated, and a new indexing job has been scheduled.'

    '401':
      $ref: '../common/responses/Unauthorized.yml'
    '500':
      $ref: '../common/responses/InternalError.yml'

delete:
  tags:
    - configurations
  operationId: deleteConfig
  x-acl:
    - editSettings
  summary: Delete a configuration
  description: |
    Deletes a Query Suggestions configuration.

    Deleting only removes the configuration and stops updates to the Query Suggestions index.
    To delete the Query Suggestions index itself, use the Search API and the [Delete an index](/specs/search#tag/Indices/operation/deleteIndex) operation.
  parameters:
    - $ref: '../common/parameters.yml#/IndexName'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../common/responses/BaseResponse.yml'
          examples:
            Created:
              summary: Configuration created
              value:
                'status': 200
                'message': 'Configuration was deleted with success.'

    '401':
      $ref: '../common/responses/Unauthorized.yml'
    '500':
      $ref: '../common/responses/InternalError.yml'
