openapi: 3.0.2
info:
  title: Usage API
  description: |
    The Usage API gives you access to statistics about all requests made to your Algolia applications.

    ## Base URL

    The base URL for requests to the Usage API is:

    - `https://usage.algolia.com`

    **All requests must use HTTPS.**

    ## Authentication

    To authenticate your API requests, add these headers:

    - `x-algolia-application-id`. Your Algolia application ID.
    - `x-algolia-api-key`. The Usage API key.

    You can find your application ID and Usage API key in the [Algolia dashboard](https://dashboard.algolia.com/account).

    ## Response status and errors

    The Usage API returns JSON responses.
    Since JSON doesn't guarantee any specific ordering, don't rely on the order of attributes in the API response.

    Successful responses return a `2xx` status. Client errors return a `4xx` status. Server errors are indicated by a `5xx` status.
    Error responses have a `message` property with more information.

    ## Version

    The current version of the Usage API is version 1, as indicated by the `/1/` in each endpoint's URL.
  version: 1.0.0
components:
  securitySchemes:
    appId:
      $ref: '../common/securitySchemes.yml#/appId'
    apiKey:
      $ref: '../common/securitySchemes.yml#/apiKey'
servers:
  - url: 'https://usage.algolia.com'
    description: Base URL of the Usage API.
  - url: 'https://usage-dev.algolia.com'
    description: Base URL for the development version of the Usage API (Algolia employees only).
security:
  - appId: []
    apiKey: []
tags:
  - name: usage
    x-displayName: Usage statistics
    description: Get various metrics related to the usage of your Algolia applications.
paths:
  # ######################
  # ### Custom request ###
  # ######################
  /{path}:
    $ref: '../common/paths/customRequest.yml'

  # ##################################
  # ######## Usage  Endpoints ########
  # ##################################
  /1/usage/{statistic}:
    $ref: 'paths/statistic.yml'
  /1/usage/{statistic}/{indexName}:
    $ref: 'paths/statisticIndex.yml'
