name: Setup

description: Setup GitHub Actions environment

runs:
  using: 'composite'
  steps:
    - name: Update ubuntu packages
      shell: bash
      run: apt update

    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'
        cache-dependency-path: 'yarn.lock'

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install Dependencies
      shell: bash
      run: yarn install

    - name: Install spec linter
      shell: bash
      run: apt-get -y install yamllint
