openapi: 3.0.2
info:
  title: Query Suggestions API
  description: API powering the Query Suggestions feature of Algolia.
  version: 0.0.1
components:
  securitySchemes:
    appId:
      type: apiKey
      in: header
      name: X-Algolia-Application-Id
    apiKey:
      type: apiKey
      in: header
      name: X-Algolia-API-Key
security:
  - appId: []
    apiKey: []
paths:
#  /1/configs:
#    $ref: './paths/createConfiguration.yml'
#  /1/configs/{indexName}:
#    $ref: './paths/updateConfiguration.yml'
#  /1/configs/{indexName}:
#    $ref: './paths/deleteConfiguration.yml'
#  /1/configs/{indexName}:
#    $ref: './paths/getConfiguration.yml'
#  /1/configs/{indexName}/status:
#    $ref: './paths/getConfigurationStatus.yml'
#  /1/configs:
#    $ref: './paths/getAllConfigurations.yml'
#  /1/logs/{indexName}:
#    $ref: './paths/getLogFile.yml'
