# path
IndexName:
  name: indexName
  in: path
  description: Index on which to perform the request.
  required: true
  schema:
    type: string
    example: myIndexName

ObjectID:
  name: objectID
  in: path
  description: Unique record (object) identifier.
  required: true
  schema:
    type: string
    example: '123'

# query
Index:
  in: query
  name: index
  description: The index name to target.
  required: true
  schema:
    type: string
    example: myIndexName

StartDate:
  in: query
  name: startDate
  description: Start date of the period to analyze. A date string in the format YYYY-MM-DD.
  schema:
    type: string
    example: 2022-09-19
    pattern: ^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$

EndDate:
  in: query
  name: endDate
  description: Upper bound timestamp (a date string inf the format YYY-MM-DD) of the period to analyze.
  schema:
    type: string
    example: 2023-01-21
    pattern: ^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$

ForwardToReplicas:
  in: query
  name: forwardToReplicas
  description: If `true`, the updated `indexName` settings will be forwarded to its replica indices.
  schema:
    type: boolean

Page:
  in: query
  name: page
  description: >
    Returns the requested page number (the first page is 0). Page size is set by `hitsPerPage`. When null, there's no pagination.
  schema:
    type: integer
    nullable: true
    default: null

PageDefault0:
  in: query
  name: page
  description: >
    Returns the requested page number (the first page is 0). Page size is set by `hitsPerPage`. When null, there's no pagination.
  schema:
    type: integer
    nullable: true
    default: 0

HitsPerPage:
  in: query
  name: hitsPerPage
  description: Maximum number of hits in a page.
  schema:
    type: integer
    default: 100

Offset:
  in: query
  name: offset
  description: Position of the starting record. Used for paging. 0 is the first record.
  schema:
    type: integer
    default: 0

Limit:
  in: query
  name: limit
  description: Number of records to return. Limit is the size of the page.
  schema:
    type: integer
    default: 10

# misc
objectID:
  type: string
  description: Unique object identifier.
  example: '123'

id:
  type: string
  example: '12'
  description: objectID of the inserted synonym object.

indexName:
  type: string
  example: products
  description: Algolia index name.

hitsPerPage:
  type: integer
  default: 20
  description: Maximum number of hits in a page. Minimum is 1, maximum is 1,000.

query:
  type: string
  description: Full-text query.
  default: ''

page:
  type: integer
  default: 0
  description: Requested page (the first page is page 0).

trackedSearchCount:
  type: integer
  example: 2
  description: The number of tracked search click.

count:
  description: The number of occurrences.
  example: 2
  type: integer
