# path
IndexName:
  name: indexName
  in: path
  description: Name of the index on which to perform the operation.
  required: true
  schema:
    type: string
    example: YourIndexName

ObjectID:
  name: objectID
  in: path
  description: Unique record identifier.
  required: true
  schema:
    type: string
    example: '123'

# query
Index:
  in: query
  name: index
  description: Index name.
  required: true
  schema:
    type: string
    example: YourIndexName

StartDate:
  in: query
  name: startDate
  description: Start date (`YYYY-MM-DD`) of the period to analyze.
  schema:
    type: string
    format: date
    example: 2022-09-19

EndDate:
  in: query
  name: endDate
  description: End date (`YYYY-MM-DD`) of the period to analyze.
  schema:
    type: string
    format: date
    example: 2023-01-21

ForwardToReplicas:
  in: query
  name: forwardToReplicas
  description: Whether changes are applied to replica indices.
  schema:
    type: boolean

Page:
  in: query
  name: page
  description: |
    Requested page of the API response.
    If `null`, the API response is not paginated.
  schema:
    oneOf:
      - type: integer
        minimum: 0
      - type: 'null'
    default: null

PageDefault0:
  in: query
  name: page
  description: |
    Requested page of the API response.
    If `null`, the API response is not paginated.
  schema:
    oneOf:
      - type: integer
        minimum: 0
      - type: 'null'
    default: 0

HitsPerPage:
  in: query
  name: hitsPerPage
  description: Number of hits per page.
  schema:
    type: integer
    default: 100

Offset:
  in: query
  name: offset
  description: Position of the first item to return.
  schema:
    type: integer
    default: 0
    minimum: 0

Limit:
  in: query
  name: limit
  description: Number of items to return.
  schema:
    type: integer
    default: 10

# misc
objectID:
  type: string
  description: Unique record identifier.

ruleID:
  title: objectID
  type: string
  description: Unique identifier of a rule object.

id:
  type: string
  example: '12'
  description: Unique identifier of a synonym object.

indexName:
  type: string
  example: products
  description: Index name.

hitsPerPage:
  type: integer
  default: 20
  minimum: 1
  maximum: 1000
  description: Maximum number of hits per page.

query:
  type: string
  description: Search query.
  default: ''

page:
  type: integer
  minimum: 0
  description: Requested page of the API response.

trackedSearchCount:
  oneOf:
    - type: integer
      example: 2
      description: Number of tracked searches. This is the number of search requests where the `clickAnalytics` parameter is `true`.
    - type: 'null'

count:
  description: Number of occurrences.
  example: 2
  type: integer
