# path
IndexName:
  name: indexName
  in: path
  description: Index on which to perform the request.
  required: true
  schema:
    type: string
    example: myIndexName

ObjectID:
  name: objectID
  in: path
  description: Unique identifier of an object.
  required: true
  schema:
    type: string
    example: '123'

# query
Index:
  in: query
  name: index
  description: Index name to target.
  required: true
  schema:
    type: string
    example: 'myIndexName'

StartDate:
  in: query
  name: startDate
  description: Start date of the period to analyze. A date string in the format YYYY-MM-DD.
  schema:
    type: string
    example: 2022-09-19
    pattern: ^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$

EndDate:
  in: query
  name: endDate
  description: End date of the period to analyze. A date string in the format YYYY-MM-DD.
  schema:
    type: string
    example: 2023-01-21
    pattern: ^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$

ForwardToReplicas:
  in: query
  name: forwardToReplicas
  description: When true, changes are also propagated to replicas of the given indexName.
  schema:
    type: boolean

Page:
  in: query
  name: page
  description: Requested page (zero-based). When specified, will retrieve a specific page; the page size is implicitly set to 100. When null, will retrieve all indices (no pagination).
  schema:
    type: integer
    nullable: true
    default: null

PageDefault0:
  in: query
  name: page
  description: Requested page (zero-based). When specified, will retrieve a specific page; the page size is implicitly set to 100. When null, will retrieve all indices (no pagination).
  schema:
    type: integer
    nullable: true
    default: 0

HitsPerPage:
  in: query
  name: hitsPerPage
  description: Maximum number of objects to retrieve.
  schema:
    type: integer
    default: 100

Offset:
  in: query
  name: offset
  description: Position of the starting record. Used for paging. 0 is the first record.
  schema:
    type: integer
    default: 0

Limit:
  in: query
  name: limit
  description: Number of records to return. Limit is the size of the page.
  schema:
    type: integer
    default: 10

# misc
objectID:
  type: string
  description: Unique identifier of the object.

id:
  type: string
  description: objectID of the inserted object.

indexName:
  type: string
  example: products
  description: The Algolia index name.

hitsPerPage:
  type: integer
  default: 20
  description: Maximum number of hits in a page. Minimum is 1, maximum is 1000.

query:
  type: string
  description: Full text query.
  default: ''

page:
  type: integer
  default: 0
  description: Requested page (zero-based).

trackedSearchCount:
  type: integer
  description: Number of tracked search clicks.
  example: 1

count:
  description: The number of occurrences.
  type: integer
