# path
IndexName:
  name: indexName
  in: path
  description: The index in which to perform the request.
  required: true
  schema:
    type: string
    example: 'myIndexName'

# query
ForwardToReplicas:
  in: query
  name: forwardToReplicas
  description: When true, changes are also propagated to replicas of the given indexName.
  schema:
    type: boolean

# misc
taskID:
  type: integer
  description: taskID of the indexing task to wait for.

objectID:
  type: string
  description: Unique identifier of the object.

objectIDs:
  type: array
  items:
    type: string
  description: List of objectID.

queryID:
  type: string
  pattern: '^[a-f0-9]{32}$'
  example: 43b15df305339e827f0ac0bdc5ebcaa7

abTestID:
  type: integer
  description: If a search encounters an index that is being A/B tested, abTestID reports the ongoing A/B test ID.

abTestVariantID:
  type: integer
  description: If a search encounters an index that is being A/B tested, abTestVariantID reports the variant ID of the index used.

updatedAt:
  type: string
  format: date-time
  description: Date of last update (ISO-8601 format).

indexName:
  type: string
  example: products
  description: The Algolia index name.
