# path
IndexName:
  name: indexName
  in: path
  description: Name of the index on which to perform the operation.
  required: true
  schema:
    type: string
    example: ALGOLIA_INDEX_NAME

ObjectID:
  name: objectID
  in: path
  description: Unique record identifier.
  required: true
  schema:
    $ref: '#/objectID'

# query
Index:
  in: query
  name: index
  description: Index name.
  required: true
  schema:
    type: string
    example: ALGOLIA_INDEX_NAME

StartDate:
  in: query
  name: startDate
  description: Start date of the period to analyze, in `YYYY-MM-DD` format.
  schema:
    type: string
    example: 2022-09-19

StartDateRequired:
  in: query
  name: startDate
  description: Start date of the period to analyze, in RFC 3339 format.
  required: true
  schema:
    type: string
    example: 2024-08-30T00:00:00Z

EndDate:
  in: query
  name: endDate
  description: End date of the period to analyze, in `YYYY-MM-DD` format.
  schema:
    type: string
    example: 2023-01-21

EndDateRequired:
  in: query
  name: endDate
  description: End date of the period to analyze, in RFC 3339 format.
  required: true
  schema:
    type: string
    example: 2024-08-30T00:00:00Z

ForwardToReplicas:
  in: query
  name: forwardToReplicas
  required: false
  description: Whether changes are applied to replica indices.
  schema:
    type: boolean

Page:
  in: query
  name: page
  description: |
    Requested page of the API response.
    If `null`, the API response is not paginated.
  required: false
  schema:
    oneOf:
      - type: integer
        minimum: 0
      - type: 'null'
    default: null

PageDefault0:
  in: query
  name: page
  description: |
    Requested page of the API response.
    If `null`, the API response is not paginated.
  schema:
    oneOf:
      - type: integer
        minimum: 0
      - type: 'null'
    default: 0

HitsPerPage:
  in: query
  name: hitsPerPage
  description: Number of hits per page.
  required: false
  schema:
    type: integer
    default: 100

# misc
objectID:
  type: string
  description: Unique record identifier.
  example: test-record-123

ruleID:
  title: objectID
  type: string
  description: Unique identifier of a rule object.

id:
  type: string
  example: '12'
  description: Unique identifier of a synonym object.

indexName:
  type: string
  example: products
  description: Index name (case-sensitive).

hitsPerPage:
  type: integer
  default: 20
  minimum: 1
  maximum: 1000
  description: |
    Maximum number of hits per page.

    Algolia uses `page` and `hitsPerPage` to control how search results are displayed ([paginated](https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/pagination/js/)).

    - `hitsPerPage`: sets the number of search results (_hits_) displayed per page.
    - `page`: specifies the page number of the search results you want to retrieve. Page numbering starts at 0, so the first page is `page=0`, the second is `page=1`, and so on.

    For example, to display 10 results per page starting from the third page, set `hitsPerPage` to 10 and `page` to 2.

query:
  type: string
  description: Search query.
  default: ''

page:
  type: integer
  minimum: 0
  description: |
    Requested page of the API response.

    Algolia uses `page` and `hitsPerPage` to control how search results are displayed ([paginated](https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/pagination/js/)).

    - `hitsPerPage`: sets the number of search results (_hits_) displayed per page.
    - `page`: specifies the page number of the search results you want to retrieve. Page numbering starts at 0, so the first page is `page=0`, the second is `page=1`, and so on.

    For example, to display 10 results per page starting from the third page, set `hitsPerPage` to 10 and `page` to 2.

count:
  description: Number of occurrences.
  example: 2
  type: integer

# analytics
trackedSearchCount:
  type: integer
  example: 2
  default: 0
  description: Number of tracked searches. Tracked searches are search requests where the `clickAnalytics` parameter is true.
