// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package agentStudio

import (
	"encoding/json"
	"fmt"

	"github.com/algolia/algoliasearch-client-go/v4/algolia/utils"
)

// AlgoliaSearchToolIndexConfigOutput struct for AlgoliaSearchToolIndexConfigOutput.
type AlgoliaSearchToolIndexConfigOutput struct {
	Index               string                                      `json:"index"`
	Description         string                                      `json:"description"`
	EnhancedDescription *string                                     `json:"enhancedDescription,omitempty"`
	SearchParameters    utils.Nullable[SearchParametersOutput]      `json:"searchParameters,omitempty"`
	SearchControls      utils.Nullable[IndexSearchParametersOutput] `json:"searchControls,omitempty"`
}

type AlgoliaSearchToolIndexConfigOutputOption func(f *AlgoliaSearchToolIndexConfigOutput)

func WithAlgoliaSearchToolIndexConfigOutputEnhancedDescription(val string) AlgoliaSearchToolIndexConfigOutputOption {
	return func(f *AlgoliaSearchToolIndexConfigOutput) {
		f.EnhancedDescription = &val
	}
}

func WithAlgoliaSearchToolIndexConfigOutputSearchParameters(val utils.Nullable[SearchParametersOutput]) AlgoliaSearchToolIndexConfigOutputOption {
	return func(f *AlgoliaSearchToolIndexConfigOutput) {
		f.SearchParameters = val
	}
}

func WithAlgoliaSearchToolIndexConfigOutputSearchControls(val utils.Nullable[IndexSearchParametersOutput]) AlgoliaSearchToolIndexConfigOutputOption {
	return func(f *AlgoliaSearchToolIndexConfigOutput) {
		f.SearchControls = val
	}
}

// NewAlgoliaSearchToolIndexConfigOutput instantiates a new AlgoliaSearchToolIndexConfigOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed.
func NewAlgoliaSearchToolIndexConfigOutput(
	index string,
	description string,
	opts ...AlgoliaSearchToolIndexConfigOutputOption,
) *AlgoliaSearchToolIndexConfigOutput {
	this := &AlgoliaSearchToolIndexConfigOutput{}
	this.Index = index

	this.Description = description
	for _, opt := range opts {
		opt(this)
	}

	return this
}

// NewEmptyAlgoliaSearchToolIndexConfigOutput return a pointer to an empty AlgoliaSearchToolIndexConfigOutput object.
func NewEmptyAlgoliaSearchToolIndexConfigOutput() *AlgoliaSearchToolIndexConfigOutput {
	return &AlgoliaSearchToolIndexConfigOutput{}
}

// GetIndex returns the Index field value.
func (o *AlgoliaSearchToolIndexConfigOutput) GetIndex() string {
	if o == nil {
		var ret string

		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *AlgoliaSearchToolIndexConfigOutput) GetIndexOk() (*string, bool) {
	if o == nil {
		return nil, false
	}

	return &o.Index, true
}

// SetIndex sets field value.
func (o *AlgoliaSearchToolIndexConfigOutput) SetIndex(v string) *AlgoliaSearchToolIndexConfigOutput {
	o.Index = v

	return o
}

// GetDescription returns the Description field value.
func (o *AlgoliaSearchToolIndexConfigOutput) GetDescription() string {
	if o == nil {
		var ret string

		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *AlgoliaSearchToolIndexConfigOutput) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}

	return &o.Description, true
}

// SetDescription sets field value.
func (o *AlgoliaSearchToolIndexConfigOutput) SetDescription(v string) *AlgoliaSearchToolIndexConfigOutput {
	o.Description = v

	return o
}

// GetEnhancedDescription returns the EnhancedDescription field value if set, zero value otherwise.
func (o *AlgoliaSearchToolIndexConfigOutput) GetEnhancedDescription() string {
	if o == nil || o.EnhancedDescription == nil {
		var ret string

		return ret
	}

	return *o.EnhancedDescription
}

// GetEnhancedDescriptionOk returns a tuple with the EnhancedDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlgoliaSearchToolIndexConfigOutput) GetEnhancedDescriptionOk() (*string, bool) {
	if o == nil || o.EnhancedDescription == nil {
		return nil, false
	}

	return o.EnhancedDescription, true
}

// HasEnhancedDescription returns a boolean if a field has been set.
func (o *AlgoliaSearchToolIndexConfigOutput) HasEnhancedDescription() bool {
	if o != nil && o.EnhancedDescription != nil {
		return true
	}

	return false
}

// SetEnhancedDescription gets a reference to the given string and assigns it to the EnhancedDescription field.
func (o *AlgoliaSearchToolIndexConfigOutput) SetEnhancedDescription(v string) *AlgoliaSearchToolIndexConfigOutput {
	o.EnhancedDescription = &v

	return o
}

// GetSearchParameters returns the SearchParameters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AlgoliaSearchToolIndexConfigOutput) GetSearchParameters() SearchParametersOutput {
	if o == nil || o.SearchParameters.Get() == nil {
		var ret SearchParametersOutput

		return ret
	}

	return *o.SearchParameters.Get()
}

// GetSearchParametersOk returns a tuple with the SearchParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned.
func (o *AlgoliaSearchToolIndexConfigOutput) GetSearchParametersOk() (*SearchParametersOutput, bool) {
	if o == nil {
		return nil, false
	}

	return o.SearchParameters.Get(), o.SearchParameters.IsSet()
}

// HasSearchParameters returns a boolean if a field has been set.
func (o *AlgoliaSearchToolIndexConfigOutput) HasSearchParameters() bool {
	if o != nil && o.SearchParameters.IsSet() {
		return true
	}

	return false
}

// SetSearchParameters gets a reference to the given utils.Nullable[SearchParametersOutput] and assigns it to the SearchParameters field.
func (o *AlgoliaSearchToolIndexConfigOutput) SetSearchParameters(v *SearchParametersOutput) *AlgoliaSearchToolIndexConfigOutput {
	o.SearchParameters.Set(v)

	return o
}

// SetSearchParametersNil sets the value for SearchParameters to be an explicit nil.
func (o *AlgoliaSearchToolIndexConfigOutput) SetSearchParametersNil() {
	o.SearchParameters.Set(nil)
}

// UnsetSearchParameters ensures that no value is present for SearchParameters, not even an explicit nil.
func (o *AlgoliaSearchToolIndexConfigOutput) UnsetSearchParameters() {
	o.SearchParameters.Unset()
}

// GetSearchControls returns the SearchControls field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AlgoliaSearchToolIndexConfigOutput) GetSearchControls() IndexSearchParametersOutput {
	if o == nil || o.SearchControls.Get() == nil {
		var ret IndexSearchParametersOutput

		return ret
	}

	return *o.SearchControls.Get()
}

// GetSearchControlsOk returns a tuple with the SearchControls field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned.
func (o *AlgoliaSearchToolIndexConfigOutput) GetSearchControlsOk() (*IndexSearchParametersOutput, bool) {
	if o == nil {
		return nil, false
	}

	return o.SearchControls.Get(), o.SearchControls.IsSet()
}

// HasSearchControls returns a boolean if a field has been set.
func (o *AlgoliaSearchToolIndexConfigOutput) HasSearchControls() bool {
	if o != nil && o.SearchControls.IsSet() {
		return true
	}

	return false
}

// SetSearchControls gets a reference to the given utils.Nullable[IndexSearchParametersOutput] and assigns it to the SearchControls field.
func (o *AlgoliaSearchToolIndexConfigOutput) SetSearchControls(v *IndexSearchParametersOutput) *AlgoliaSearchToolIndexConfigOutput {
	o.SearchControls.Set(v)

	return o
}

// SetSearchControlsNil sets the value for SearchControls to be an explicit nil.
func (o *AlgoliaSearchToolIndexConfigOutput) SetSearchControlsNil() {
	o.SearchControls.Set(nil)
}

// UnsetSearchControls ensures that no value is present for SearchControls, not even an explicit nil.
func (o *AlgoliaSearchToolIndexConfigOutput) UnsetSearchControls() {
	o.SearchControls.Unset()
}

func (o AlgoliaSearchToolIndexConfigOutput) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]any{}
	toSerialize["index"] = o.Index

	toSerialize["description"] = o.Description
	if o.EnhancedDescription != nil {
		toSerialize["enhancedDescription"] = o.EnhancedDescription
	}

	if o.SearchParameters.IsSet() {
		toSerialize["searchParameters"] = o.SearchParameters.Get()
	}

	if o.SearchControls.IsSet() {
		toSerialize["searchControls"] = o.SearchControls.Get()
	}

	serialized, err := json.Marshal(toSerialize)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal AlgoliaSearchToolIndexConfigOutput: %w", err)
	}

	return serialized, nil
}

func (o AlgoliaSearchToolIndexConfigOutput) String() string {
	out := ""
	out += fmt.Sprintf("  index=%v\n", o.Index)
	out += fmt.Sprintf("  description=%v\n", o.Description)
	out += fmt.Sprintf("  enhancedDescription=%v\n", o.EnhancedDescription)
	out += fmt.Sprintf("  searchParameters=%v\n", o.SearchParameters)
	out += fmt.Sprintf("  searchControls=%v\n", o.SearchControls)

	return fmt.Sprintf("AlgoliaSearchToolIndexConfigOutput {\n%s}", out)
}
