// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package agentStudio

import (
	"encoding/json"
	"fmt"

	"github.com/algolia/algoliasearch-client-go/v4/algolia/utils"
)

// AnthropicProviderInputInput Anthropic-specific provider input.
type AnthropicProviderInputInput struct {
	ApiKey  string                 `json:"apiKey"`
	BaseUrl utils.Nullable[string] `json:"baseUrl,omitempty"`
}

type AnthropicProviderInputInputOption func(f *AnthropicProviderInputInput)

func WithAnthropicProviderInputInputBaseUrl(val utils.Nullable[string]) AnthropicProviderInputInputOption {
	return func(f *AnthropicProviderInputInput) {
		f.BaseUrl = val
	}
}

// NewAnthropicProviderInputInput instantiates a new AnthropicProviderInputInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed.
func NewAnthropicProviderInputInput(apiKey string, opts ...AnthropicProviderInputInputOption) *AnthropicProviderInputInput {
	this := &AnthropicProviderInputInput{}

	this.ApiKey = apiKey
	for _, opt := range opts {
		opt(this)
	}

	return this
}

// NewEmptyAnthropicProviderInputInput return a pointer to an empty AnthropicProviderInputInput object.
func NewEmptyAnthropicProviderInputInput() *AnthropicProviderInputInput {
	return &AnthropicProviderInputInput{}
}

// GetApiKey returns the ApiKey field value.
func (o *AnthropicProviderInputInput) GetApiKey() string {
	if o == nil {
		var ret string

		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *AnthropicProviderInputInput) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}

	return &o.ApiKey, true
}

// SetApiKey sets field value.
func (o *AnthropicProviderInputInput) SetApiKey(v string) *AnthropicProviderInputInput {
	o.ApiKey = v

	return o
}

// GetBaseUrl returns the BaseUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AnthropicProviderInputInput) GetBaseUrl() string {
	if o == nil || o.BaseUrl.Get() == nil {
		var ret string

		return ret
	}

	return *o.BaseUrl.Get()
}

// GetBaseUrlOk returns a tuple with the BaseUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned.
func (o *AnthropicProviderInputInput) GetBaseUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}

	return o.BaseUrl.Get(), o.BaseUrl.IsSet()
}

// HasBaseUrl returns a boolean if a field has been set.
func (o *AnthropicProviderInputInput) HasBaseUrl() bool {
	if o != nil && o.BaseUrl.IsSet() {
		return true
	}

	return false
}

// SetBaseUrl gets a reference to the given utils.Nullable[string] and assigns it to the BaseUrl field.
func (o *AnthropicProviderInputInput) SetBaseUrl(v string) *AnthropicProviderInputInput {
	o.BaseUrl.Set(&v)

	return o
}

// SetBaseUrlNil sets the value for BaseUrl to be an explicit nil.
func (o *AnthropicProviderInputInput) SetBaseUrlNil() {
	o.BaseUrl.Set(nil)
}

// UnsetBaseUrl ensures that no value is present for BaseUrl, not even an explicit nil.
func (o *AnthropicProviderInputInput) UnsetBaseUrl() {
	o.BaseUrl.Unset()
}

func (o AnthropicProviderInputInput) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]any{}

	toSerialize["apiKey"] = o.ApiKey
	if o.BaseUrl.IsSet() {
		toSerialize["baseUrl"] = o.BaseUrl.Get()
	}

	serialized, err := json.Marshal(toSerialize)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal AnthropicProviderInputInput: %w", err)
	}

	return serialized, nil
}

func (o AnthropicProviderInputInput) String() string {
	out := ""
	out += fmt.Sprintf("  apiKey=%v\n", o.ApiKey)
	out += fmt.Sprintf("  baseUrl=%v\n", o.BaseUrl)

	return fmt.Sprintf("AnthropicProviderInputInput {\n%s}", out)
}
