// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package agentStudio

import (
	"encoding/json"
	"fmt"
)

// AgentCompletionResponse - struct for AgentCompletionResponse.
type AgentCompletionResponse struct {
	AssistantMessageV4Response *AssistantMessageV4Response
	AssistantMessageV5Response *AssistantMessageV5Response
}

// AssistantMessageV4ResponseAsAgentCompletionResponse is a convenience function that returns AssistantMessageV4Response wrapped in AgentCompletionResponse.
func AssistantMessageV4ResponseAsAgentCompletionResponse(v *AssistantMessageV4Response) *AgentCompletionResponse {
	return &AgentCompletionResponse{
		AssistantMessageV4Response: v,
	}
}

// AssistantMessageV5ResponseAsAgentCompletionResponse is a convenience function that returns AssistantMessageV5Response wrapped in AgentCompletionResponse.
func AssistantMessageV5ResponseAsAgentCompletionResponse(v *AssistantMessageV5Response) *AgentCompletionResponse {
	return &AgentCompletionResponse{
		AssistantMessageV5Response: v,
	}
}

// Unmarshal JSON data into one or more of the pointers in the struct.
func (dst *AgentCompletionResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal data into AssistantMessageV4Response
	err = json.Unmarshal(data, &dst.AssistantMessageV4Response)
	if err != nil {
		dst.AssistantMessageV4Response = nil
	}
	// try to unmarshal data into AssistantMessageV5Response
	err = json.Unmarshal(data, &dst.AssistantMessageV5Response)
	if err != nil {
		dst.AssistantMessageV5Response = nil
	}

	// check if at least one type was successfully unmarshaled
	if dst.AssistantMessageV4Response != nil {
		return nil
	}

	if dst.AssistantMessageV5Response != nil {
		return nil
	}

	return fmt.Errorf("data failed to match schemas in oneOf(AgentCompletionResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON.
func (src AgentCompletionResponse) MarshalJSON() ([]byte, error) {
	if src.AssistantMessageV4Response != nil {
		serialized, err := json.Marshal(&src.AssistantMessageV4Response)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal one of AssistantMessageV4Response of AgentCompletionResponse: %w", err)
		}

		return serialized, nil
	}

	if src.AssistantMessageV5Response != nil {
		serialized, err := json.Marshal(&src.AssistantMessageV5Response)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal one of AssistantMessageV5Response of AgentCompletionResponse: %w", err)
		}

		return serialized, nil
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance.
func (obj AgentCompletionResponse) GetActualInstance() any {
	if obj.AssistantMessageV4Response != nil {
		return *obj.AssistantMessageV4Response
	}

	if obj.AssistantMessageV5Response != nil {
		return *obj.AssistantMessageV5Response
	}

	// all schemas are nil
	return nil
}
