searchForFacetValuesResponse:
  type: object
  additionalProperties: false
  properties:
    results:
      type: array
      description: Search for facet values results.
      items:
        $ref: '#/searchForFacetValuesResults'

searchForFacetValuesResults:
  type: object
  additionalProperties: false
  required:
    - facetHits
    - exhaustiveFacetsCount
    - indexName
  x-discriminator-fields:
    - facetHits
  properties:
    indexName:
      type: string
    facetHits:
      type: array
      description: Matching facet values.
      items:
        title: facetHits
        type: object
        additionalProperties: false
        required:
          - value
          - highlighted
          - count
        properties:
          value:
            description: Facet value.
            example: 'Mobile phone'
            type: string
          highlighted:
            $ref: '../../../common/schemas/HighlightResult.yml#/highlightedValue'
          count:
            description: Number of records with this facet value. [The count may be approximated](https://support.algolia.com/hc/en-us/articles/4406975248145-Why-are-my-facet-and-hit-counts-not-accurate-).
            type: integer
    exhaustiveFacetsCount:
      type: boolean
      description: |
        Whether the facet count is exhaustive (true) or approximate (false).
        For more information, see [Why are my facet and hit counts not accurate](https://support.algolia.com/hc/en-us/articles/4406975248145-Why-are-my-facet-and-hit-counts-not-accurate-).
    processingTimeMS:
      $ref: '../../../common/schemas/SearchResponse.yml#/processingTimeMS'
