get:
  tags:
    - models
  operationId: getModelInstanceConfig
  summary: Get a model’s instance configuration.
  description: Get the configuration for a model that was activated.
  parameters:
    - $ref: '../../common/parameters.yml#/modelID'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            title: getModelInstanceConfigResponse
            $ref: '../../responses/Models.yml#/modelInstance'
    '401':
      $ref: '../../responses/InvalidCredentials.yml'
    '404':
      $ref: '../../responses/ModelNotFound.yml'
    '422':
      $ref: '../../../common/responses/UnprocessableEntity.yml'
    '500':
      $ref: '../../../common/responses/InternalError.yml'
