Models:
  in: path
  name: model
  required: true
  description: |
    [Recommend model](https://www.algolia.com/doc/guides/algolia-recommend/overview/#recommend-models).
  schema:
    $ref: '#/recommendModels'

# This list excludes `looking-similar` as that can't be used with rules.
recommendModels:
  type: string
  enum: [related-products, bought-together, trending-facets, trending-items]

ObjectID:
  in: path
  name: objectID
  required: true
  description: Unique identifier of a Recommend rule object.
  example: 'a-recommend-rule-id'
  schema:
    $ref: '../../common/parameters.yml#/ruleID'

facetName:
  type: string
  description: |
    Facet attribute. To be used in combination with `facetValue`.
    If specified, only recommendations matching the facet filter will be returned.

facetValue:
  type: string
  description: |
    Facet value. To be used in combination with `facetName`.
    If specified, only recommendations matching the facet filter will be returned.
