Models:
  in: path
  name: model
  description: >
    [Recommend models](https://www.algolia.com/doc/guides/algolia-recommend/overview/#recommend-models).
  schema:
    type: string
    # enum: [related-products, bought-together, trending-facets, trending-items]

ObjectID:
  in: path
  name: objectID
  type: string
  description: Unique Recommend rule identifier.
  example: 'a-recommend-rule-id'