# path
DictionaryName:
  in: path
  name: dictionaryName
  description: Dictionary type in which to search.
  required: true
  schema:
    $ref: '#/dictionaryType'

dictionaryType:
  type: string
  enum: [plurals, stopwords, compounds]

standardEntries:
  type: object
  description: |
    Key-value pairs of [supported language ISO codes](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/handling-natural-languages-nlp/in-depth/supported-languages) and boolean values.
  additionalProperties: false
  properties:
    plurals:
      $ref: '#/standardEntry'
    stopwords:
      $ref: '#/standardEntry'
    compounds:
      $ref: '#/standardEntry'

standardEntry:
  oneOf:
    - type: object
      description: Key-value pair of a language ISO code and a boolean value.
      example:
        fr: false
      additionalProperties:
        x-additionalPropertiesName: language
        type: boolean
    - type: 'null'
