# path
DictionaryName:
  in: path
  name: dictionaryName
  description: Dictionary to search in.
  required: true
  schema:
    $ref: '#/dictionaryType'

dictionaryType:
  type: string
  enum: [plurals, stopwords, compounds]

# misc
language:
  description: >
    [Supported language ISO code](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/handling-natural-languages-nlp/in-depth/supported-languages/) (for example, "en" for English).
  type: string

standardEntries:
  description: >
    Maps a [supported language ISO code](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/handling-natural-languages-nlp/in-depth/supported-languages/) to a boolean value (for example, `"fr": false`). If `true` Algolia's built-in [stop words](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/handling-natural-languages-nlp/how-to/customize-stop-words/) for that language have been turned off.
  additionalProperties: false
  properties:
    plurals:
      $ref: '#/standardEntry'
    stopwords:
      $ref: '#/standardEntry'
    compounds:
      $ref: '#/standardEntry'

standardEntry:
  description: Language ISO code.
  type: object
  nullable: true
  additionalProperties:
    type: boolean
