// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
import { describe, expect, test } from 'vitest';

import { union } from '../helpers.js';

import { compositionClient } from '@algolia/composition';

if (!process.env.METIS_APPLICATION_ID) {
  throw new Error('please provide an `METIS_APPLICATION_ID` env var for e2e tests');
}

if (!process.env.METIS_API_KEY) {
  throw new Error('please provide an `METIS_API_KEY` env var for e2e tests');
}

const client = compositionClient(process.env.METIS_APPLICATION_ID, process.env.METIS_API_KEY);

describe('getComposition', () => {
  test('the Correlation-ID ends with the sent Request-ID', async () => {
    const resp = await client.getComposition(
      { compositionID: 'id1' },
      {
        headers: { 'request-id': 'CtsE2eEcho4' },
      },
    );

    const expectedBody = { objectID: 'id1' };

    expect(expectedBody).toEqual(union(expectedBody, resp));
    const httpResp = await client.transporter.requestWithHttpInfo(
      { method: 'GET', path: '/1/compositions/id1', queryParameters: {}, headers: {} },
      {
        headers: { 'request-id': 'CtsE2eEcho4' },
      },
    );

    expect(httpResp.headers?.['correlation-id']).toBeDefined();
    expect(httpResp.headers?.['correlation-id']?.endsWith('CtsE2eEcho4')).toBe(true);
  });
});

describe('listCompositions', () => {
  test('listCompositions', async () => {
    const resp = await client.listCompositions();

    const expectedBody = {
      items: [
        {
          objectID: 'id1',
          name: 'my first composition',
          description: 'the first ever composition from the client',
          behavior: { injection: { main: { source: { search: { index: 'cts_e2e_small' } } } } },
        },
      ],
      nbPages: 1,
    };

    expect(expectedBody).toEqual(union(expectedBody, resp));
  });
});
