allOf:
  - $ref: '../parameters.yml#/Pagination'
  - type: object
    properties:
      items:
        type: array
        description: Configuration changes.
        items:
          type: object
          properties:
            version:
              $ref: '../parameters.yml#/version'
            createdAt:
              $ref: '../../../common/responses/common.yml#/createdAt'
            authorId:
              $ref: '../parameters.yml#/authorId'
          required:
            - version
            - createdAt
            - authorId
