post:
  tags:
    - tasks
  summary: Push a `batch` request payload through the Pipeline
  description: Push a `batch` request payload through the Pipeline using the v1 endpoint, please use `pushTask` instead. You can check the status of task pushes with the observability endpoints.
  operationId: pushTaskV1
  x-acl:
    - addObject
    - deleteIndex
    - editSettings
  parameters:
    - $ref: '../../../common/parameters.yml#/pathTaskID'
  x-codegen-request-body-name: batchWriteParams
  requestBody:
    description: Request body for creating a task.
    content:
      application/json:
        schema:
          $ref: '../../../../common/schemas/Batch.yml#/batchWriteParams'
    required: true
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../../../common/schemas/run.yml#/RunResponse'
    '400':
      $ref: '../../../../common/responses/BadRequest.yml'
