name: algolia_snippets
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  algoliasearch: ^1.0.0
  algolia_client_search: ^1.0.0
  algolia_client_insights: ^1.0.0
  algolia_client_recommend: ^1.0.0
  dotenv: ^4.1.0

dev_dependencies:
  lints: ^5.0.0
