/** ragApi Algolia's GenAI Toolkit API, building blocks for your dynamic LLM-enabled experiences. Build generative AI
  * experiences with your Algolia data. Combine large language models with Algolia’s Search API using Retrieval
  * Augmented Generation (RAG) techniques.
  *
  * The version of the OpenAPI document: 0.1.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package algoliasearch.agentstudio

/** AgentConfigUpdate
  */
case class AgentConfigUpdate(
    name: Option[String] = scala.None,
    description: Option[String] = scala.None,
    providerId: Option[String] = scala.None,
    model: Option[String] = scala.None,
    instructions: Option[String] = scala.None,
    config: Option[Map[String, Any]] = scala.None,
    tools: Option[Seq[ItemsUnion]] = scala.None
)
