/** ragApi Algolia's GenAI Toolkit API, building blocks for your dynamic LLM-enabled experiences. Build generative AI
  * experiences with your Algolia data. Combine large language models with Algolia’s Search API using Retrieval
  * Augmented Generation (RAG) techniques.
  *
  * The version of the OpenAPI document: 0.1.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech Do not edit the class manually.
  */
package algoliasearch.agentstudio

import org.json4s._

/** InsidePolygonUnion
  */
sealed trait InsidePolygonUnion

object InsidePolygonUnion {

  case class StringValue(value: String) extends InsidePolygonUnion

  case class SeqOfSeqOfDouble(value: Seq[Seq[Double]]) extends InsidePolygonUnion

  def apply(value: String): InsidePolygonUnion = {
    InsidePolygonUnion.StringValue(value)
  }

  def apply(value: Seq[Seq[Double]]): InsidePolygonUnion = {
    InsidePolygonUnion.SeqOfSeqOfDouble(value)
  }

}

object InsidePolygonUnionSerializer extends Serializer[InsidePolygonUnion] {
  override def deserialize(implicit format: Formats): PartialFunction[(TypeInfo, JValue), InsidePolygonUnion] = {

    case (TypeInfo(clazz, _), json) if clazz == classOf[InsidePolygonUnion] =>
      json match {
        case JString(value) => InsidePolygonUnion.StringValue(value)
        case value: JArray  => InsidePolygonUnion.apply(Extraction.extract[Seq[Seq[Double]]](value))
        case _              => throw new MappingException("Can't convert " + json + " to InsidePolygonUnion")
      }
  }

  override def serialize(implicit format: Formats): PartialFunction[Any, JValue] = { case value: InsidePolygonUnion =>
    value match {
      case InsidePolygonUnion.StringValue(value)      => JString(value)
      case InsidePolygonUnion.SeqOfSeqOfDouble(value) => JArray(value.map(Extraction.decompose).toList)
    }
  }
}
