// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element
import 'package:algolia_client_agent_studio/src/model/provider_name.dart';

import 'package:json_annotation/json_annotation.dart';

part 'provider_authentication_create.g.dart';

@JsonSerializable()
final class ProviderAuthenticationCreate {
  /// Returns a new [ProviderAuthenticationCreate] instance.
  const ProviderAuthenticationCreate({
    required this.name,
    required this.providerName,
    required this.input,
  });

  @JsonKey(name: r'name')
  final String name;

  @JsonKey(name: r'providerName')
  final ProviderName providerName;

  /// One of types:
  /// - [AzureOpenAIProviderInput]
  /// - [AnthropicProviderInput]
  /// - [BaseProviderInput]
  /// - [OpenAIProviderInput]
  /// - [OpenAICompatibleProviderInput]
  @JsonKey(name: r'input')
  final dynamic input;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderAuthenticationCreate &&
          other.name == name &&
          other.providerName == providerName &&
          other.input == input;

  @override
  int get hashCode => name.hashCode + providerName.hashCode + input.hashCode;

  factory ProviderAuthenticationCreate.fromJson(Map<String, dynamic> json) =>
      _$ProviderAuthenticationCreateFromJson(json);

  Map<String, dynamic> toJson() => _$ProviderAuthenticationCreateToJson(this);

  @override
  String toString() {
    return toJson().toString();
  }
}
