// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element

import 'package:json_annotation/json_annotation.dart';

part 'step_start_part_v4.g.dart';

@JsonSerializable()
final class StepStartPartV4 {
  /// Returns a new [StepStartPartV4] instance.
  const StepStartPartV4({
    this.type,
  });

  @JsonKey(name: r'type')
  final String? type;

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is StepStartPartV4 && other.type == type;

  @override
  int get hashCode => type.hashCode;

  factory StepStartPartV4.fromJson(Map<String, dynamic> json) =>
      _$StepStartPartV4FromJson(json);

  Map<String, dynamic> toJson() => _$StepStartPartV4ToJson(this);

  @override
  String toString() {
    return toJson().toString();
  }
}
