// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost
// - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package com.algolia.requests

import com.algolia.client.api.AgentStudioClient
import com.algolia.client.configuration.*
import com.algolia.client.model.agentstudio.*
import com.algolia.client.transport.*
import com.algolia.utils.*
import io.ktor.http.*
import kotlin.test.*
import kotlinx.coroutines.test.*
import kotlinx.serialization.json.*

class AgentStudioTest {

  val client = AgentStudioClient(appId = "appId", apiKey = "apiKey", region = "us")

  // createAgent

  @Test
  fun `createAgent with minimal parameters`() = runTest {
    client.runTest(
      call = {
        createAgent(
          agentConfigCreate =
            AgentConfigCreate(name = "test-agent", instructions = "You are a helpful assistant.")
        )
      },
      intercept = {
        assertEquals("/1/agents".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("POST"), it.method)
        assertJsonBody(
          """{"name":"test-agent","instructions":"You are a helpful assistant."}""",
          it.body,
        )
      },
    )
  }

  @Test
  fun `createAgent with all parameters1`() = runTest {
    client.runTest(
      call = {
        createAgent(
          agentConfigCreate =
            AgentConfigCreate(
              name = "test-agent",
              description = "A test agent for CTS",
              providerId = "5e33d805-7892-4329-bda7-b524dc3fd04a",
              model = "gpt-4",
              instructions = "You are a helpful assistant.",
              config =
                buildJsonObject {
                  put("sendUsage", JsonPrimitive(true))
                  put("sendReasoning", JsonPrimitive(true))
                  put("temperature", JsonPrimitive(0.7))
                  put("max_tokens", JsonPrimitive(1500))
                },
              tools = listOf(StartPart(type = "start")),
            )
        )
      },
      intercept = {
        assertEquals("/1/agents".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("POST"), it.method)
        assertJsonBody(
          """{"name":"test-agent","description":"A test agent for CTS","providerId":"5e33d805-7892-4329-bda7-b524dc3fd04a","model":"gpt-4","instructions":"You are a helpful assistant.","config":{"sendUsage":true,"sendReasoning":true,"temperature":0.7,"max_tokens":1500},"tools":[{"type":"start"}]}""",
          it.body,
        )
      },
    )
  }

  // createAgentCompletion

  @Test
  fun `createAgentCompletion with v4 messages`() = runTest {
    client.runTest(
      call = {
        createAgentCompletion(
          agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
          compatibilityMode = CompatibilityMode.entries.first { it.value == "ai-sdk-4" },
          agentCompletionRequest =
            AgentCompletionRequest(
              messages =
                MessagesUnion.ofListOfMessageV4(
                  listOf(UserMessageV4(role = "user", content = "Hello, how are you?"))
                )
            ),
        )
      },
      intercept = {
        assertEquals(
          "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/completions".toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("POST"), it.method)
        assertQueryParams("""{"compatibilityMode":"ai-sdk-4"}""", it.url.encodedParameters)
        assertJsonBody(
          """{"messages":[{"role":"user","content":"Hello, how are you?"}]}""",
          it.body,
        )
      },
    )
  }

  // createProvider

  @Test
  fun `createProvider with OpenAI`() = runTest {
    client.runTest(
      call = {
        createProvider(
          providerAuthenticationCreate =
            ProviderAuthenticationCreate(
              name = "My OpenAI Provider",
              providerName = ProviderName.entries.first { it.value == "openai" },
              input = OpenAIProviderInput(apiKey = "sk-test-key-1234"),
            )
        )
      },
      intercept = {
        assertEquals("/1/providers".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("POST"), it.method)
        assertJsonBody(
          """{"name":"My OpenAI Provider","providerName":"openai","input":{"apiKey":"sk-test-key-1234"}}""",
          it.body,
        )
      },
    )
  }

  @Test
  fun `createProvider with Azure OpenAI1`() = runTest {
    client.runTest(
      call = {
        createProvider(
          providerAuthenticationCreate =
            ProviderAuthenticationCreate(
              name = "My Azure Provider",
              providerName = ProviderName.entries.first { it.value == "azure_openai" },
              input =
                AzureOpenAIProviderInput(
                  apiKey = "az-test-key-5678",
                  azureEndpoint = "https://my-resource.openai.azure.com",
                  azureDeployment = "gpt-4o",
                ),
            )
        )
      },
      intercept = {
        assertEquals("/1/providers".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("POST"), it.method)
        assertJsonBody(
          """{"name":"My Azure Provider","providerName":"azure_openai","input":{"apiKey":"az-test-key-5678","azureEndpoint":"https://my-resource.openai.azure.com","azureDeployment":"gpt-4o"}}""",
          it.body,
        )
      },
    )
  }

  // customDelete

  @Test
  fun `allow del method for a custom path with minimal parameters`() = runTest {
    client.runTest(
      call = { customDelete(path = "test/minimal") },
      intercept = {
        assertEquals("/test/minimal".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("DELETE"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  @Test
  fun `allow del method for a custom path with all parameters1`() = runTest {
    client.runTest(
      call = { customDelete(path = "test/all", parameters = mapOf("query" to "parameters")) },
      intercept = {
        assertEquals("/test/all".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("DELETE"), it.method)
        assertQueryParams("""{"query":"parameters"}""", it.url.encodedParameters)
        assertNoBody(it.body)
      },
    )
  }

  // customGet

  @Test
  fun `allow get method for a custom path with minimal parameters`() = runTest {
    client.runTest(
      call = { customGet(path = "test/minimal") },
      intercept = {
        assertEquals("/test/minimal".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  @Test
  fun `allow get method for a custom path with all parameters1`() = runTest {
    client.runTest(
      call = {
        customGet(path = "test/all", parameters = mapOf("query" to "parameters with space"))
      },
      intercept = {
        assertEquals("/test/all".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertQueryParams("""{"query":"parameters%20with%20space"}""", it.url.encodedParameters)
        assertNoBody(it.body)
      },
    )
  }

  @Test
  fun `requestOptions should be escaped too2`() = runTest {
    client.runTest(
      call = {
        customGet(
          path = "test/all",
          parameters = mapOf("query" to "to be overridden"),
          requestOptions =
            RequestOptions(
              urlParameters =
                buildMap {
                  put("query", "parameters with space")
                  put("and an array", listOf("array", "with spaces"))
                },
              headers = buildMap { put("x-header-1", "spaces are left alone") },
            ),
        )
      },
      intercept = {
        assertEquals("/test/all".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertContainsAll("""{"x-header-1":"spaces are left alone"}""", it.headers)
        assertQueryParams(
          """{"query":"parameters%20with%20space","and%20an%20array":"array%2Cwith%20spaces"}""",
          it.url.encodedParameters,
        )
        assertNoBody(it.body)
      },
    )
  }

  // customPost

  @Test
  fun `allow post method for a custom path with minimal parameters`() = runTest {
    client.runTest(
      call = { customPost(path = "test/minimal") },
      intercept = {
        assertEquals("/test/minimal".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("POST"), it.method)
        assertJsonBody("""{}""", it.body)
      },
    )
  }

  @Test
  fun `allow post method for a custom path with all parameters1`() = runTest {
    client.runTest(
      call = {
        customPost(
          path = "test/all",
          parameters = mapOf("query" to "parameters"),
          body = buildJsonObject { put("body", JsonPrimitive("parameters")) },
        )
      },
      intercept = {
        assertEquals("/test/all".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("POST"), it.method)
        assertQueryParams("""{"query":"parameters"}""", it.url.encodedParameters)
        assertJsonBody("""{"body":"parameters"}""", it.body)
      },
    )
  }

  @Test
  fun `requestOptions can override default query parameters2`() = runTest {
    client.runTest(
      call = {
        customPost(
          path = "test/requestOptions",
          parameters = mapOf("query" to "parameters"),
          body = buildJsonObject { put("facet", JsonPrimitive("filters")) },
          requestOptions =
            RequestOptions(urlParameters = buildMap { put("query", "myQueryParameter") }),
        )
      },
      intercept = {
        assertEquals("/test/requestOptions".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("POST"), it.method)
        assertQueryParams("""{"query":"myQueryParameter"}""", it.url.encodedParameters)
        assertJsonBody("""{"facet":"filters"}""", it.body)
      },
    )
  }

  @Test
  fun `requestOptions merges query parameters with default ones3`() = runTest {
    client.runTest(
      call = {
        customPost(
          path = "test/requestOptions",
          parameters = mapOf("query" to "parameters"),
          body = buildJsonObject { put("facet", JsonPrimitive("filters")) },
          requestOptions =
            RequestOptions(urlParameters = buildMap { put("query2", "myQueryParameter") }),
        )
      },
      intercept = {
        assertEquals("/test/requestOptions".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("POST"), it.method)
        assertQueryParams(
          """{"query":"parameters","query2":"myQueryParameter"}""",
          it.url.encodedParameters,
        )
        assertJsonBody("""{"facet":"filters"}""", it.body)
      },
    )
  }

  @Test
  fun `requestOptions can override default headers4`() = runTest {
    client.runTest(
      call = {
        customPost(
          path = "test/requestOptions",
          parameters = mapOf("query" to "parameters"),
          body = buildJsonObject { put("facet", JsonPrimitive("filters")) },
          requestOptions =
            RequestOptions(headers = buildMap { put("x-algolia-api-key", "ALGOLIA_API_KEY") }),
        )
      },
      intercept = {
        assertEquals("/test/requestOptions".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("POST"), it.method)
        assertContainsAll("""{"x-algolia-api-key":"ALGOLIA_API_KEY"}""", it.headers)
        assertQueryParams("""{"query":"parameters"}""", it.url.encodedParameters)
        assertJsonBody("""{"facet":"filters"}""", it.body)
      },
    )
  }

  @Test
  fun `requestOptions merges headers with default ones5`() = runTest {
    client.runTest(
      call = {
        customPost(
          path = "test/requestOptions",
          parameters = mapOf("query" to "parameters"),
          body = buildJsonObject { put("facet", JsonPrimitive("filters")) },
          requestOptions =
            RequestOptions(headers = buildMap { put("x-algolia-api-key", "ALGOLIA_API_KEY") }),
        )
      },
      intercept = {
        assertEquals("/test/requestOptions".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("POST"), it.method)
        assertContainsAll("""{"x-algolia-api-key":"ALGOLIA_API_KEY"}""", it.headers)
        assertQueryParams("""{"query":"parameters"}""", it.url.encodedParameters)
        assertJsonBody("""{"facet":"filters"}""", it.body)
      },
    )
  }

  @Test
  fun `requestOptions queryParameters accepts booleans6`() = runTest {
    client.runTest(
      call = {
        customPost(
          path = "test/requestOptions",
          parameters = mapOf("query" to "parameters"),
          body = buildJsonObject { put("facet", JsonPrimitive("filters")) },
          requestOptions = RequestOptions(urlParameters = buildMap { put("isItWorking", true) }),
        )
      },
      intercept = {
        assertEquals("/test/requestOptions".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("POST"), it.method)
        assertQueryParams(
          """{"query":"parameters","isItWorking":"true"}""",
          it.url.encodedParameters,
        )
        assertJsonBody("""{"facet":"filters"}""", it.body)
      },
    )
  }

  @Test
  fun `requestOptions queryParameters accepts integers7`() = runTest {
    client.runTest(
      call = {
        customPost(
          path = "test/requestOptions",
          parameters = mapOf("query" to "parameters"),
          body = buildJsonObject { put("facet", JsonPrimitive("filters")) },
          requestOptions = RequestOptions(urlParameters = buildMap { put("myParam", 2) }),
        )
      },
      intercept = {
        assertEquals("/test/requestOptions".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("POST"), it.method)
        assertQueryParams("""{"query":"parameters","myParam":"2"}""", it.url.encodedParameters)
        assertJsonBody("""{"facet":"filters"}""", it.body)
      },
    )
  }

  @Test
  fun `requestOptions queryParameters accepts list of string8`() = runTest {
    client.runTest(
      call = {
        customPost(
          path = "test/requestOptions",
          parameters = mapOf("query" to "parameters"),
          body = buildJsonObject { put("facet", JsonPrimitive("filters")) },
          requestOptions =
            RequestOptions(urlParameters = buildMap { put("myParam", listOf("b and c", "d")) }),
        )
      },
      intercept = {
        assertEquals("/test/requestOptions".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("POST"), it.method)
        assertQueryParams(
          """{"query":"parameters","myParam":"b%20and%20c%2Cd"}""",
          it.url.encodedParameters,
        )
        assertJsonBody("""{"facet":"filters"}""", it.body)
      },
    )
  }

  @Test
  fun `requestOptions queryParameters accepts list of booleans9`() = runTest {
    client.runTest(
      call = {
        customPost(
          path = "test/requestOptions",
          parameters = mapOf("query" to "parameters"),
          body = buildJsonObject { put("facet", JsonPrimitive("filters")) },
          requestOptions =
            RequestOptions(urlParameters = buildMap { put("myParam", listOf(true, true, false)) }),
        )
      },
      intercept = {
        assertEquals("/test/requestOptions".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("POST"), it.method)
        assertQueryParams(
          """{"query":"parameters","myParam":"true%2Ctrue%2Cfalse"}""",
          it.url.encodedParameters,
        )
        assertJsonBody("""{"facet":"filters"}""", it.body)
      },
    )
  }

  @Test
  fun `requestOptions queryParameters accepts list of integers10`() = runTest {
    client.runTest(
      call = {
        customPost(
          path = "test/requestOptions",
          parameters = mapOf("query" to "parameters"),
          body = buildJsonObject { put("facet", JsonPrimitive("filters")) },
          requestOptions = RequestOptions(urlParameters = buildMap { put("myParam", listOf(1, 2)) }),
        )
      },
      intercept = {
        assertEquals("/test/requestOptions".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("POST"), it.method)
        assertQueryParams("""{"query":"parameters","myParam":"1%2C2"}""", it.url.encodedParameters)
        assertJsonBody("""{"facet":"filters"}""", it.body)
      },
    )
  }

  // customPut

  @Test
  fun `allow put method for a custom path with minimal parameters`() = runTest {
    client.runTest(
      call = { customPut(path = "test/minimal") },
      intercept = {
        assertEquals("/test/minimal".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("PUT"), it.method)
        assertJsonBody("""{}""", it.body)
      },
    )
  }

  @Test
  fun `allow put method for a custom path with all parameters1`() = runTest {
    client.runTest(
      call = {
        customPut(
          path = "test/all",
          parameters = mapOf("query" to "parameters"),
          body = buildJsonObject { put("body", JsonPrimitive("parameters")) },
        )
      },
      intercept = {
        assertEquals("/test/all".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("PUT"), it.method)
        assertQueryParams("""{"query":"parameters"}""", it.url.encodedParameters)
        assertJsonBody("""{"body":"parameters"}""", it.body)
      },
    )
  }

  // deleteAgent

  @Test
  fun `deleteAgent`() = runTest {
    client.runTest(
      call = { deleteAgent(agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff") },
      intercept = {
        assertEquals(
          "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff".toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("DELETE"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  // deleteAgentConversations

  @Test
  fun `deleteAgentConversations without filters`() = runTest {
    client.runTest(
      call = { deleteAgentConversations(agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff") },
      intercept = {
        assertEquals(
          "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations".toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("DELETE"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  @Test
  fun `deleteAgentConversations with date filters1`() = runTest {
    client.runTest(
      call = {
        deleteAgentConversations(
          agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
          startDate = "2024-01-01",
          endDate = "2024-06-30",
        )
      },
      intercept = {
        assertEquals(
          "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations".toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("DELETE"), it.method)
        assertQueryParams(
          """{"startDate":"2024-01-01","endDate":"2024-06-30"}""",
          it.url.encodedParameters,
        )
        assertNoBody(it.body)
      },
    )
  }

  // deleteConversation

  @Test
  fun `deleteConversation`() = runTest {
    client.runTest(
      call = {
        deleteConversation(
          agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
          conversationId = "test-conversation-id",
        )
      },
      intercept = {
        assertEquals(
          "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations/test-conversation-id"
            .toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("DELETE"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  // deleteProvider

  @Test
  fun `deleteProvider`() = runTest {
    client.runTest(
      call = { deleteProvider(providerId = "5e33d805-7892-4329-bda7-b524dc3fd04a") },
      intercept = {
        assertEquals(
          "/1/providers/5e33d805-7892-4329-bda7-b524dc3fd04a".toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("DELETE"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  // deleteUserData

  @Test
  fun `deleteUserData`() = runTest {
    client.runTest(
      call = { deleteUserData(userToken = "test-user-token") },
      intercept = {
        assertEquals("/1/user-data/test-user-token".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("DELETE"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  // exportConversations

  @Test
  fun `exportConversations without filters`() = runTest {
    client.runTest(
      call = { exportConversations(agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff") },
      intercept = {
        assertEquals(
          "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations/export".toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  @Test
  fun `exportConversations with date filters1`() = runTest {
    client.runTest(
      call = {
        exportConversations(
          agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
          startDate = "2024-01-01",
          endDate = "2024-12-31",
        )
      },
      intercept = {
        assertEquals(
          "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations/export".toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertQueryParams(
          """{"startDate":"2024-01-01","endDate":"2024-12-31"}""",
          it.url.encodedParameters,
        )
        assertNoBody(it.body)
      },
    )
  }

  // getAgent

  @Test
  fun `getAgent`() = runTest {
    client.runTest(
      call = { getAgent(agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff") },
      intercept = {
        assertEquals(
          "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff".toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  @Test
  fun `e2e get agent1`() = runTest {
    client.runTest(
      call = { getAgent(agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff") },
      intercept = {
        assertEquals(
          "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff".toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  // getApplicationConfiguration

  @Test
  fun `getApplicationConfiguration`() = runTest {
    client.runTest(
      call = { getApplicationConfiguration() },
      intercept = {
        assertEquals("/1/configuration".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  @Test
  fun `e2e getApplicationConfiguration1`() = runTest {
    client.runTest(
      call = { getApplicationConfiguration() },
      intercept = {
        assertEquals("/1/configuration".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  // getConversation

  @Test
  fun `getConversation`() = runTest {
    client.runTest(
      call = {
        getConversation(
          agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
          conversationId = "test-conversation-id",
        )
      },
      intercept = {
        assertEquals(
          "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations/test-conversation-id"
            .toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  // getProvider

  @Test
  fun `getProvider`() = runTest {
    client.runTest(
      call = { getProvider(providerId = "5e33d805-7892-4329-bda7-b524dc3fd04a") },
      intercept = {
        assertEquals(
          "/1/providers/5e33d805-7892-4329-bda7-b524dc3fd04a".toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  @Test
  fun `e2e get provider1`() = runTest {
    client.runTest(
      call = { getProvider(providerId = "5e33d805-7892-4329-bda7-b524dc3fd04a") },
      intercept = {
        assertEquals(
          "/1/providers/5e33d805-7892-4329-bda7-b524dc3fd04a".toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  // getUserData

  @Test
  fun `getUserData`() = runTest {
    client.runTest(
      call = { getUserData(userToken = "test-user-token") },
      intercept = {
        assertEquals("/1/user-data/test-user-token".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  // invalidateAgentCache

  @Test
  fun `invalidateAgentCache without before`() = runTest {
    client.runTest(
      call = { invalidateAgentCache(agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff") },
      intercept = {
        assertEquals(
          "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/cache".toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("DELETE"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  @Test
  fun `invalidateAgentCache with before date1`() = runTest {
    client.runTest(
      call = {
        invalidateAgentCache(
          agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
          before = "2024-12-01",
        )
      },
      intercept = {
        assertEquals(
          "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/cache".toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("DELETE"), it.method)
        assertQueryParams("""{"before":"2024-12-01"}""", it.url.encodedParameters)
        assertNoBody(it.body)
      },
    )
  }

  // listAgentConversations

  @Test
  fun `listAgentConversations with minimal parameters`() = runTest {
    client.runTest(
      call = { listAgentConversations(agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff") },
      intercept = {
        assertEquals(
          "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations".toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  @Test
  fun `listAgentConversations with all parameters1`() = runTest {
    client.runTest(
      call = {
        listAgentConversations(
          agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
          startDate = "2024-01-01",
          endDate = "2024-12-31",
          page = 2,
          limit = 10,
        )
      },
      intercept = {
        assertEquals(
          "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations".toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertQueryParams(
          """{"startDate":"2024-01-01","endDate":"2024-12-31","page":"2","limit":"10"}""",
          it.url.encodedParameters,
        )
        assertNoBody(it.body)
      },
    )
  }

  // listAgents

  @Test
  fun `list agents with no params`() = runTest {
    client.runTest(
      call = { listAgents() },
      intercept = {
        assertEquals("/1/agents".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  @Test
  fun `list agents with all parameters1`() = runTest {
    client.runTest(
      call = {
        listAgents(page = 2, limit = 5, providerId = "5e33d805-7892-4329-bda7-b524dc3fd04a")
      },
      intercept = {
        assertEquals("/1/agents".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertQueryParams(
          """{"page":"2","limit":"5","providerId":"5e33d805-7892-4329-bda7-b524dc3fd04a"}""",
          it.url.encodedParameters,
        )
        assertNoBody(it.body)
      },
    )
  }

  @Test
  fun `e2e list agents2`() = runTest {
    client.runTest(
      call = { listAgents(page = 1, limit = 2) },
      intercept = {
        assertEquals("/1/agents".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertQueryParams("""{"page":"1","limit":"2"}""", it.url.encodedParameters)
        assertNoBody(it.body)
      },
    )
  }

  // listModels

  @Test
  fun `listModels`() = runTest {
    client.runTest(
      call = { listModels() },
      intercept = {
        assertEquals("/1/providers/models".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  @Test
  fun `e2e list models1`() = runTest {
    client.runTest(
      call = { listModels() },
      intercept = {
        assertEquals("/1/providers/models".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  // listProviderModels

  @Test
  fun `listProviderModels`() = runTest {
    client.runTest(
      call = { listProviderModels(providerId = "5e33d805-7892-4329-bda7-b524dc3fd04a") },
      intercept = {
        assertEquals(
          "/1/providers/5e33d805-7892-4329-bda7-b524dc3fd04a/models".toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  // listProviders

  @Test
  fun `listProviders with no params`() = runTest {
    client.runTest(
      call = { listProviders() },
      intercept = {
        assertEquals("/1/providers".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertNoBody(it.body)
      },
    )
  }

  @Test
  fun `listProviders with pagination1`() = runTest {
    client.runTest(
      call = { listProviders(page = 2, limit = 5) },
      intercept = {
        assertEquals("/1/providers".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertQueryParams("""{"page":"2","limit":"5"}""", it.url.encodedParameters)
        assertNoBody(it.body)
      },
    )
  }

  @Test
  fun `e2e list providers2`() = runTest {
    client.runTest(
      call = { listProviders(page = 1, limit = 2) },
      intercept = {
        assertEquals("/1/providers".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("GET"), it.method)
        assertQueryParams("""{"page":"1","limit":"2"}""", it.url.encodedParameters)
        assertNoBody(it.body)
      },
    )
  }

  // publishAgent

  @Test
  fun `publishAgent`() = runTest {
    client.runTest(
      call = { publishAgent(agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff") },
      intercept = {
        assertEquals(
          "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/publish".toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("POST"), it.method)
        assertEmptyBody(it.body)
      },
    )
  }

  // unpublishAgent

  @Test
  fun `unpublishAgent`() = runTest {
    client.runTest(
      call = { unpublishAgent(agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff") },
      intercept = {
        assertEquals(
          "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/unpublish".toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("POST"), it.method)
        assertEmptyBody(it.body)
      },
    )
  }

  // updateAgent

  @Test
  fun `updateAgent with minimal parameters`() = runTest {
    client.runTest(
      call = {
        updateAgent(
          agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
          agentConfigUpdate = AgentConfigUpdate(name = "updated-agent-name"),
        )
      },
      intercept = {
        assertEquals(
          "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff".toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("PATCH"), it.method)
        assertJsonBody("""{"name":"updated-agent-name"}""", it.body)
      },
    )
  }

  @Test
  fun `updateAgent with all parameters1`() = runTest {
    client.runTest(
      call = {
        updateAgent(
          agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
          agentConfigUpdate =
            AgentConfigUpdate(
              name = "updated-agent",
              description = "Updated description",
              providerId = "new-provider-id",
              model = "gpt-4o",
              instructions = "Updated instructions.",
              config = buildJsonObject { put("temperature", JsonPrimitive(0.5)) },
              tools = listOf(StartPart(type = "start")),
            ),
        )
      },
      intercept = {
        assertEquals(
          "/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff".toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("PATCH"), it.method)
        assertJsonBody(
          """{"name":"updated-agent","description":"Updated description","providerId":"new-provider-id","model":"gpt-4o","instructions":"Updated instructions.","config":{"temperature":0.5},"tools":[{"type":"start"}]}""",
          it.body,
        )
      },
    )
  }

  // updateConfiguration

  @Test
  fun `updateConfiguration`() = runTest {
    client.runTest(
      call = {
        updateConfiguration(applicationConfigPatch = ApplicationConfigPatch(maxRetentionDays = 30))
      },
      intercept = {
        assertEquals("/1/configuration".toPathSegments(), it.url.pathSegments)
        assertEquals(HttpMethod.parse("PATCH"), it.method)
        assertJsonBody("""{"maxRetentionDays":30}""", it.body)
      },
    )
  }

  // updateProvider

  @Test
  fun `updateProvider`() = runTest {
    client.runTest(
      call = {
        updateProvider(
          providerId = "5e33d805-7892-4329-bda7-b524dc3fd04a",
          providerAuthenticationPatch = ProviderAuthenticationPatch(name = "Updated Provider Name"),
        )
      },
      intercept = {
        assertEquals(
          "/1/providers/5e33d805-7892-4329-bda7-b524dc3fd04a".toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("PATCH"), it.method)
        assertJsonBody("""{"name":"Updated Provider Name"}""", it.body)
      },
    )
  }

  @Test
  fun `updateProvider with input1`() = runTest {
    client.runTest(
      call = {
        updateProvider(
          providerId = "5e33d805-7892-4329-bda7-b524dc3fd04a",
          providerAuthenticationPatch =
            ProviderAuthenticationPatch(
              name = "Updated Provider",
              input = OpenAIProviderInput(apiKey = "sk-new-key-5678"),
            ),
        )
      },
      intercept = {
        assertEquals(
          "/1/providers/5e33d805-7892-4329-bda7-b524dc3fd04a".toPathSegments(),
          it.url.pathSegments,
        )
        assertEquals(HttpMethod.parse("PATCH"), it.method)
        assertJsonBody(
          """{"name":"Updated Provider","input":{"apiKey":"sk-new-key-5678"}}""",
          it.body,
        )
      },
    )
  }
}
