# frozen_string_literal: true

require 'rake/testtask'

task test: %w[test:client test:requests test:e2e]

namespace :test do
  Rake::TestTask.new(:client) do |t|
    t.libs << 'test'
    t.test_files = FileList['test/client/*_test.rb', 'test/manual/*_test.rb']
    t.verbose    = true
    t.warning    = false
  end

  Rake::TestTask.new(:requests) do |t|
    t.libs << 'test'
    t.test_files = FileList['test/requests/*_test.rb']
    t.verbose    = true
    t.warning    = false
  end

  Rake::TestTask.new(:e2e) do |t|
    t.libs << 'test'
    t.test_files = FileList['test/e2e/*_test.rb']
    t.verbose    = true
    t.warning    = false
  end

  Rake::TestTask.new(:benchmark) do |t|
    t.libs << 'test'
    t.test_files = FileList['test/benchmark/*_test.rb']
    t.verbose    = true
    t.warning    = false
  end
end
