# frozen_string_literal: true

require 'rake/testtask'

task test: 'test:unit'

namespace :test do
  Rake::TestTask.new(:unit) do |t|
    t.libs << 'test'
    t.test_files = FileList['test/**/*_test.rb']
    t.verbose    = true
    t.warning    = false
  end
end
