// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package recommend

import (
	"encoding/json"
	"fmt"
	"slices"
)

// TrendingFacetsModel Trending facet values model.  This model recommends trending facet values for the specified facet attribute.
type TrendingFacetsModel string

// List of trendingFacetsModel.
const (
	TRENDING_FACETS_MODEL_TRENDING_FACETS TrendingFacetsModel = "trending-facets"
)

// All allowed values of TrendingFacetsModel enum.
var AllowedTrendingFacetsModelEnumValues = []TrendingFacetsModel{
	"trending-facets",
}

// NewTrendingFacetsModelFromValue returns a pointer to a valid TrendingFacetsModel.
// for the value passed as argument, or an error if the value passed is not allowed by the enum.
func NewTrendingFacetsModelFromValue(v string) (*TrendingFacetsModel, error) {
	ev := TrendingFacetsModel(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TrendingFacetsModel: valid values are %v", v, AllowedTrendingFacetsModelEnumValues)
	}
}

func (v *TrendingFacetsModel) UnmarshalJSON(src []byte) error {
	var value string

	err := json.Unmarshal(src, &value)
	if err != nil {
		return fmt.Errorf("failed to unmarshal value '%s' for enum 'TrendingFacetsModel': %w", string(src), err)
	}

	enumTypeValue := TrendingFacetsModel(value)
	if slices.Contains(AllowedTrendingFacetsModelEnumValues, enumTypeValue) {
		*v = enumTypeValue

		return nil
	}

	return fmt.Errorf("%+v is not a valid TrendingFacetsModel", value)
}

// IsValid return true if the value is valid for the enum, false otherwise.
func (v TrendingFacetsModel) IsValid() bool {
	return slices.Contains(AllowedTrendingFacetsModelEnumValues, v)
}

// Ptr returns reference to trendingFacetsModel value.
func (v TrendingFacetsModel) Ptr() *TrendingFacetsModel {
	return &v
}
