get:
  summary: Get a specific version of the configuration of a crawler
  parameters:
    - $ref: ../../../common/parameters.yml#/parameters/crawlerIdParam
    - $ref: ../../../common/parameters.yml#/parameters/crawlerVersionParam
  responses:
    '200':
      description: A specific revision of the crawler
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              version:
                type: integer
                minimum: 1
              config:
                $ref: ../../../common/schemas/Config.yml#/Config
              createdAt:
                type: string
                # format: dateTime
              authorId:
                type: string
            required:
              - version
              - config
              - createdAt
