get:
  summary: List crawler versions
  parameters:
    - $ref: ../../../common/parameters.yml#/parameters/crawlerIdParam
    - in: query
      name: itemsPerPage
      schema:
        type: integer
        minimum: 1
        default: 20
        maximum: 100
      description: Change the number of versions per page
    - in: query
      name: page
      schema:
        type: integer
        minimum: 1
        default: 1
        maximum: 5000
      description: Change the page number
  responses:
    '200':
      description: A list of crawler versions and pagination information
      content:
        application/json:
          schema:
            allOf:
              - $ref: ../../../common/schemas/Pagination.yml
              - type: object
                additionalProperties: false
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      additionalProperties: false
                      properties:
                        version:
                          type: integer
                          minimum: 1
                        createdAt:
                          type: string
                          # format: dateTime
                        authorId:
                          type: string
                      required:
                        - version
                        - createdAt
