get:
  tags:
    - crawler
  summary: Get a specific version of the configuration of a crawler.
  operationId: listConfigVersions
  description: |-
    TODO: complete.
  parameters:
    - $ref: ../../../common/parameters.yml#/crawlerIdPath
  responses:
    '200':
      description: A specific revision of the crawler.
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              version:
                type: integer
                minimum: 1
              config:
                $ref: ../../../common/schemas/Config.yml#/Config
              createdAt:
                type: string
                # format: dateTime
              authorId:
                type: string
            required:
              - version
              - config
              - createdAt
    '400':
      $ref: ../../../responses/400InvalidRequest.yml
    '401':
      $ref: ../../../responses/401MissingAuthorization.yml
    '403':
      $ref: ../../../responses/403NoRightsOnCrawler.yml
