openapi: 3.0.2
info:
  title: Insights API
  description: API powering the Insights feature of Algolia.
  version: 0.0.1
components:
  securitySchemes:
    appId:
      type: apiKey
      in: header
      name: X-Algolia-Application-Id
    apiKey:
      type: apiKey
      in: header
      name: X-Algolia-API-Key
security:
  - appId: []
    apiKey: []
paths:
#  /1/events:
#    $ref: './paths/pushEvents.yml'
