openapi: 3.0.2
info:
  title: Insights API
  description: API powering the Insights feature of Algolia.
  version: 0.0.1
components:
  securitySchemes:
    appId:
      $ref: '../common/securitySchemes/common.yml#/appId'
    apiKey:
      $ref: '../common/securitySchemes/common.yml#/apiKey'
security:
  - appId: []
    apiKey: []
paths:
  /1/events:
    $ref: './paths/pushEvents.yml'
