indexSettings:
  description: The Algolia index settings.
  allOf:
    - $ref: '#/baseIndexSettings'
    - $ref: '#/indexSettingsAsSearchParams'

baseIndexSettings:
  type: object
  additionalProperties: false
  properties:
    replicas:
      type: array
      items:
        type: string
      description: Creates replicas, exact copies of an index.
      default: []
      x-categories:
        - Ranking
    paginationLimitedTo:
      type: integer
      description: Set the maximum number of hits accessible via pagination.
      default: 1000
    unretrievableAttributes:
      type: array
      items:
        type: string
      description: List of attributes that can't be retrieved at query time.
      default: []
      x-categories:
        - Attributes
    disableTypoToleranceOnWords:
      type: array
      items:
        type: string
      description: A list of words for which you want to turn off typo tolerance.
      default: []
      x-categories:
        - Typos
    attributesToTransliterate:
      description: Specify on which attributes in your index Algolia should apply Japanese transliteration to make words indexed in Katakana or Kanji searchable in Hiragana.
      type: array
      items:
        type: string
      x-categories:
        - Languages
    camelCaseAttributes:
      type: array
      items:
        type: string
      description: List of attributes on which to do a decomposition of camel case words.
      default: []
      x-categories:
        - Languages
    decompoundedAttributes:
      type: object
      description: Specify on which attributes in your index Algolia should apply word segmentation, also known as decompounding.
      default: {}
      x-categories:
        - Languages
    indexLanguages:
      type: array
      items:
        type: string
      description: Sets the languages at the index level for language-specific processing such as tokenization and normalization.
      default: []
      x-categories:
        - Languages
    disablePrefixOnAttributes:
      type: array
      items:
        type: string
      description: List of attributes on which you want to disable prefix matching.
      default: []
      x-categories:
        - Query strategy
    allowCompressionOfIntegerArray:
      type: boolean
      description: Enables compression of large integer arrays.
      default: false
      x-categories:
        - Performance
    numericAttributesForFiltering:
      type: array
      items:
        type: string
      description: List of numeric attributes that can be used as numerical filters.
      default: []
      x-categories:
        - Performance
    separatorsToIndex:
      type: string
      description: Control which separators are indexed.
      default: ''
      x-categories:
        - Typos
    searchableAttributes:
      type: array
      items:
        type: string
      description: The complete list of attributes used for searching.
      default: []
      x-categories:
        - Attributes
    userData:
      $ref: '#/userData'
    customNormalization:
      description: Overrides Algolia's default normalization.
      type: object
      additionalProperties:
        type: object
        additionalProperties:
          type: string
      x-categories:
        - Languages

indexSettingsAsSearchParams:
  type: object
  additionalProperties: false
  properties:
    attributesForFaceting:
      type: array
      items:
        type: string
      example: ['author','filterOnly(isbn)','searchable(edition)','afterDistinct(category)','afterDistinct(searchable(publisher))']
      description: Attributes used for [faceting](https://www.algolia.com/doc/guides/managing-results/refine-results/faceting/).
      default: []
      x-categories:
        - Faceting
    attributesToRetrieve:
      type: array
      items:
        type: string
      example: ['author','title','content']
      description: Attributes to retrieve.
      default: ['*']
      x-categories:
        - Attributes
    restrictSearchableAttributes:
      type: array
      items:
        type: string
      example: ['title','author']
      description: Restricts a query to only look at a subset of your [searchable attributes](https://www.algolia.com/doc/guides/managing-results/must-do/searchable-attributes/).
      default: []
      x-categories:
        - Attributes
    ranking:
      type: array
      items:
        type: string
      description: >
        [How Algolia sorts your results](https://www.algolia.com/doc/guides/managing-results/relevance-overview/in-depth/ranking-criteria/).
      default:
        - typo
        - geo
        - words
        - filters
        - proximity
        - attribute
        - exact
        - custom
      x-categories:
        - Ranking
    customRanking:
      type: array
      items:
        type: string
      example: ['desc(popularity)','asc(price)']
      description: Specifies the [custom ranking criterion](https://www.algolia.com/doc/guides/managing-results/must-do/custom-ranking/).
      default: []
      x-categories:
        - Ranking
    relevancyStrictness:
      type: integer
      example: 90
      description: Relevancy threshold below which less relevant results aren't included in the results.
      default: 100
      x-categories:
        - Ranking
    attributesToHighlight:
      type: array
      items:
        type: string
      example: ['author','title','content']
      description: Attributes to highlight.
      x-categories:
        - Highlighting and Snippeting
    attributesToSnippet:
      type: array
      items:
        type: string
      example: ['content:80','description']
      description: Attributes to snippet. You can also set each snippet's size to a specific number of words.
      default: []
      x-categories:
        - Highlighting and Snippeting
    highlightPreTag:
      type: string
      description: HTML string to insert before the highlighted parts in all highlight and snippet results.
      default: <em>
      x-categories:
        - Highlighting and Snippeting
    highlightPostTag:
      type: string
      description: HTML string to insert after the highlighted parts in all highlight and snippet results.
      default: </em>
      x-categories:
        - Highlighting and Snippeting
    snippetEllipsisText:
      type: string
      description: String used as an ellipsis indicator when a snippet is truncated.
      default: …
      x-categories:
        - Highlighting and Snippeting
    restrictHighlightAndSnippetArrays:
      type: boolean
      description: Restrict highlighting and snippeting to items that matched the query.
      default: false
      x-categories:
        - Highlighting and Snippeting
    hitsPerPage:
      $ref: '#/hitsPerPage'
    minWordSizefor1Typo:
      type: integer
      description: Minimum number of characters a word in the query string must contain to accept matches with [one typo](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/typo-tolerance/in-depth/configuring-typo-tolerance/#configuring-word-length-for-typos).
      default: 4
      x-categories:
        - Typos
    minWordSizefor2Typos:
      type: integer
      description: Minimum number of characters a word in the query string must contain to accept matches with [two typos](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/typo-tolerance/in-depth/configuring-typo-tolerance/#configuring-word-length-for-typos).
      default: 8
      x-categories:
        - Typos
    typoTolerance:
      $ref: '#/typoTolerance'
    allowTyposOnNumericTokens:
      type: boolean
      description: Whether to allow typos on numbers ("numeric tokens") in the query string.
      default: true
      x-categories:
        - Typos
    disableTypoToleranceOnAttributes:
      type: array
      items:
        type: string
      example: ['sku']
      description: Attributes for which you want to turn off [typo tolerance](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/typo-tolerance/).
      default: []
      x-categories:
        - Typos
    ignorePlurals:
      $ref: '#/ignorePlurals'
    removeStopWords:
      $ref: '#/removeStopWords'
    keepDiacriticsOnCharacters:
      type: string
      example: øé
      description: Characters that the engine shouldn't automatically [normalize](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/handling-natural-languages-nlp/in-depth/normalization/).
      default: ''
      x-categories:
        - Languages
    queryLanguages:
      type: array
      items:
        type: string
      example: ['es']
      description: Languages to be used by language-specific settings and features such as `ignorePlurals`, `removeStopWords`, and [CJK](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/handling-natural-languages-nlp/in-depth/normalization/#normalization-for-logogram-based-languages-cjk) word detection.
      default: []
      x-categories:
        - Languages
    decompoundQuery:
      type: boolean
      description: >
        [Splits compound words](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/handling-natural-languages-nlp/in-depth/language-specific-configurations/#splitting-compound-words) into their composing atoms in the query.
      default: true
      x-categories:
        - Languages
    enableRules:
      type: boolean
      description: Whether [Rules](https://www.algolia.com/doc/guides/managing-results/rules/rules-overview/) should be globally enabled.
      default: true
      x-categories:
        - Rules
    enablePersonalization:
      type: boolean
      description: Enable the [Personalization feature](https://www.algolia.com/doc/guides/personalization/what-is-personalization/).
      default: false
      x-categories:
        - Personalization
    queryType:
      $ref: '#/queryType'
    removeWordsIfNoResults:
      $ref: '#/removeWordsIfNoResults'
    mode:
      $ref: '#/mode'
    semanticSearch:
      type: object
      description: >
        Settings for semantic search engine configuration.
        Only used when `mode` is _neuralSearch_.
      properties:
        eventSources:
          description: If null, the current index and replica group will be used as the event source.
          nullable: true
          type: array
          items:
            type: string

    advancedSyntax:
      type: boolean
      description: Enables the advanced query syntax.
      default: false
      x-categories:
        - Query strategy
    optionalWords:
      type: array
      items:
        type: string
      description: A list of words that should be considered as optional when found in the query.
      default: []
      x-categories:
        - Query strategy
    disableExactOnAttributes:
      type: array
      items:
        type: string
      description: List of attributes on which you want to disable the exact ranking criterion.
      default: []
      x-categories:
        - Query strategy
    exactOnSingleWordQuery:
      $ref: '#/exactOnSingleWordQuery'
    alternativesAsExact:
      type: array
      items:
        $ref: '#/alternativesAsExact'
      description: List of alternatives that should be considered an exact match by the exact ranking criterion.
      default: [ignorePlurals, singleWordSynonym]
      x-categories:
        - Query strategy
    advancedSyntaxFeatures:
      type: array
      items:
        $ref: '#/advancedSyntaxFeatures'
      description: Allows you to specify which advanced syntax features are active when ‘advancedSyntax' is enabled.
      default: [exactPhrase, excludeWords]
      x-categories:
        - Query strategy
    explain:
      type: array
      items:
        type: string
      description: Enriches the API’s response with meta-information as to how the query was processed.
      default: []
      x-categories:
        - Query strategy
    distinct:
      $ref: '#/distinct'
    attributeForDistinct:
      description: Name of the de-duplication attribute to be used with the distinct feature.
      type: string
    synonyms:
      type: boolean
      description: Whether to take into account an index's synonyms for a particular search.
      default: true
      x-categories:
        - Advanced
    replaceSynonymsInHighlight:
      type: boolean
      description: Whether to highlight and snippet the original word that matches the synonym or the synonym itself.
      default: false
      x-categories:
        - Highlighting and Snippeting
    minProximity:
      type: integer
      minimum: 1
      maximum: 7
      description: Precision of the proximity ranking criterion.
      default: 1
      x-categories:
        - Advanced
    responseFields:
      type: array
      items:
        type: string
      description: Choose which fields to return in the API response. This parameters applies to search and browse queries.
      default: []
      x-categories:
        - Advanced
    maxFacetHits:
      $ref: '#/maxFacetHits'
    attributeCriteriaComputedByMinProximity:
      type: boolean
      description: When attribute is ranked above proximity in your ranking formula, proximity is used to select which searchable attribute is matched in the attribute ranking stage.
      default: false
      x-categories:
        - Advanced
    renderingContent:
      $ref: '#/renderingContent'

maxFacetHits:
  type: integer
  description: Maximum number of facet hits to return during a search for facet values. For performance reasons, the maximum allowed number of returned values is 100.
  maximum: 100
  default: 10
  x-categories:
    - Advanced

hitsPerPage:
  type: integer
  description: Number of hits per page (1 to 1000).
  default: 20
  x-categories:
    - Pagination

userData:
  type: object
  example: {'settingID': 'f2a7b51e3503acc6a39b3784ffb84300','pluginVersion': '1.6.0'}
  description: Lets you store custom data in your indices.
  default: {}
  x-categories:
    - Advanced

queryType:
  type: string
  enum: [prefixLast, prefixAll, prefixNone]
  description: >
    [How query words are interpreted as prefixes](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/override-search-engine-defaults/in-depth/prefix-searching/).
  default: prefixLast
  x-categories:
    - Query strategy

mode:
  type: string
  enum: ['neuralSearch', 'keywordSearch']
  description: Search mode the index will use to query for results.
  default: keywordSearch
  x-categories:
    - Query strategy

removeWordsIfNoResults:
  type: string
  enum: [none, lastWords, firstWords, allOptional]
  description: Selects a strategy to [remove words](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/empty-or-insufficient-results/in-depth/why-use-remove-words-if-no-results/) from the query when it doesn't match any hits.
  default: none
  x-categories:
    - Query strategy

exactOnSingleWordQuery:
  type: string
  enum: [attribute, none, word]
  description: Controls how the exact ranking criterion is computed when the query contains only one word.
  default: attribute
  x-categories:
    - Query strategy

alternativesAsExact:
  type: string
  enum: [ignorePlurals, singleWordSynonym, multiWordsSynonym]
  x-categories:
    - Query strategy

advancedSyntaxFeatures:
  type: string
  enum: [exactPhrase, excludeWords]
  x-categories:
    - Query strategy

distinct:
  description: Enables de-duplication or grouping of results.
  oneOf:
    - type: boolean
    - type: integer
      minimum: 0
      maximum: 4
      default: 0
  x-categories:
    - Advanced

typoTolerance:
  description: Controls whether typo tolerance is enabled and how it is applied.
  oneOf:
    - type: boolean
      default: true
    - $ref: '#/typoToleranceEnum'
  x-categories:
    - Typos

typoToleranceEnum:
  type: string
  enum: [min, strict]

ignorePlurals:
  description: >
    Treats singular, plurals, and other forms of declensions as matching terms.

    `ignorePlurals` is used in conjunction with the `queryLanguages` setting.

    _list_: language ISO codes for which ignoring plurals should be enabled. This list will override any values that you may have set in `queryLanguages`.
    _true_: enables the ignore plurals feature, where singulars and plurals are considered equivalent ("foot" = "feet"). The languages supported here are either [every language](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/handling-natural-languages-nlp/in-depth/supported-languages/) (this is the default) or those set by `queryLanguages`.
    _false_: turns off the ignore plurals feature, so that singulars and plurals aren't considered to be the same ("foot" will not find "feet").
  example: ['ca','es']
  oneOf:
    - type: array
      items:
        type: string
    - type: boolean
      default: false
  x-categories:
    - Languages

removeStopWords:
  description: >
    Removes stop (common) words from the query before executing it.

    `removeStopWords` is used in conjunction with the `queryLanguages` setting.

    _list_: language ISO codes for which stop words should be enabled. This list will override any values that you may have set in `queryLanguages`.
    _true_: enables the stop words feature, ensuring that stop words are removed from consideration in a search. The languages supported here are either [every language](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/handling-natural-languages-nlp/in-depth/supported-languages/) (this is the default) or those set by `queryLanguages`.
    _false_: turns off the stop words feature, allowing stop words to be taken into account in a search.
  example: ['ca','es']
  oneOf:
    - type: array
      items:
        type: string
    - type: boolean
      default: false
  x-categories:
    - Languages

renderingContent:
  description: >
    [How the search interface should be rendered](https://www.algolia.com/doc/guides/managing-results/rules/merchandising-and-promoting/how-to/merchandising-facets/#merchandise-facets-and-their-values-in-the-manual-editor). You can set a default value but this can be overridden with [Rules](https://www.algolia.com/doc/guides/managing-results/rules/rules-overview/).
  type: object
  additionalProperties: false
  properties:
    facetOrdering:
      $ref: '#/facetOrdering'
  x-categories:
    - Advanced

facetOrdering:
  description: How facets should be ordered.
  type: object
  additionalProperties: false
  properties:
    facets:
      $ref: '#/facets'
    values:
      $ref: '#/values'

facets:
  description: Ordering of facets (widgets).
  type: object
  additionalProperties: false
  properties:
    order:
      $ref: '#/order'

values:
  description: Ordering of facet values within an individual list.
  type: object
  additionalProperties:
    $ref: '#/value'

value:
  type: object
  additionalProperties: false
  properties:
    order:
      $ref: '#/order'
    sortRemainingBy:
      $ref: '#/sortRemainingBy'

order:
  description: Pinned order of facet lists.
  type: array
  items:
    type: string

sortRemainingBy:
  description: >
    How to display the remaining items.
      - `count`: facet count (descending).
      - `alpha`: alphabetical (ascending).
      - `hidden`: show only pinned values.
  type: string
  enum: [count, alpha, hidden]
