// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element

import 'package:json_annotation/json_annotation.dart';

part 'decision.g.dart';

@JsonSerializable()
final class Decision {
  /// Returns a new [Decision] instance.
  const Decision({
    required this.winnerVariantId,
    required this.declaredAt,
  });

  /// Identifier of the declared winning variant. The control variant is 1.
  @JsonKey(name: r'winnerVariantId')
  final int winnerVariantId;

  /// Date and time when the winning variant was declared, in RFC 3339 format.
  @JsonKey(name: r'declaredAt')
  final String declaredAt;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Decision &&
          other.winnerVariantId == winnerVariantId &&
          other.declaredAt == declaredAt;

  @override
  int get hashCode => winnerVariantId.hashCode + declaredAt.hashCode;

  factory Decision.fromJson(Map<String, dynamic> json) =>
      _$DecisionFromJson(json);

  Map<String, dynamic> toJson() => _$DecisionToJson(this);

  @override
  String toString() {
    return toJson().toString();
  }
}
