// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element
import 'package:algolia_client_abtesting_v3/src/model/estimate_configuration.dart';

import 'package:json_annotation/json_annotation.dart';

part 'estimate_ab_test_request.g.dart';

@JsonSerializable()
final class EstimateABTestRequest {
  /// Returns a new [EstimateABTestRequest] instance.
  const EstimateABTestRequest({
    required this.configuration,
    required this.variants,
  });

  @JsonKey(name: r'configuration')
  final EstimateConfiguration configuration;

  /// A/B test variants.
  /// One of types:
  /// - [AbTestsVariantSearchParams]
  /// - [AbTestsVariant]
  @JsonKey(name: r'variants')
  final Iterable<dynamic> variants;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EstimateABTestRequest &&
          other.configuration == configuration &&
          other.variants == variants;

  @override
  int get hashCode => configuration.hashCode + variants.hashCode;

  factory EstimateABTestRequest.fromJson(Map<String, dynamic> json) =>
      _$EstimateABTestRequestFromJson(json);

  Map<String, dynamic> toJson() => _$EstimateABTestRequestToJson(this);

  @override
  String toString() {
    return toJson().toString();
  }
}
