// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
// ignore_for_file: unused_element
import 'package:algolia_client_abtesting_v3/src/model/timeseries_variant.dart';

import 'package:json_annotation/json_annotation.dart';

part 'timeseries.g.dart';

@JsonSerializable()
final class Timeseries {
  /// Returns a new [Timeseries] instance.
  const Timeseries({
    required this.abTestID,
    required this.variants,
  });

  /// Unique A/B test identifier.
  @JsonKey(name: r'abTestID')
  final int abTestID;

  /// A/B test timeseries variants.  The first variant is your _control_ index, typically your production index. All of the additional variants are indexes with changed settings that you want to test against the control.
  @JsonKey(name: r'variants')
  final List<TimeseriesVariant> variants;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Timeseries &&
          other.abTestID == abTestID &&
          other.variants == variants;

  @override
  int get hashCode => abTestID.hashCode + variants.hashCode;

  factory Timeseries.fromJson(Map<String, dynamic> json) =>
      _$TimeseriesFromJson(json);

  Map<String, dynamic> toJson() => _$TimeseriesToJson(this);

  @override
  String toString() {
    return toJson().toString();
  }
}
