# coding: utf-8

"""
Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
"""

from __future__ import annotations

from enum import Enum
from json import loads
from sys import version_info

if version_info >= (3, 11):
    from typing import Self
else:
    from typing_extensions import Self


class CompatibilityMode(str, Enum):
    """
    Compatibility mode for the completion API. `ai-sdk-4` uses a proprietary response format that is incompatible with server-sent events (SSE). Streaming isn't supported for this mode. `ai-sdk-5` supports both `application/json` and `text/event-stream` responses.
    """

    """
    allowed enum values
    """
    AI_SDK_4 = "ai-sdk-4"

    AI_SDK_5 = "ai-sdk-5"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CompatibilityMode from a JSON string"""
        return cls(loads(json_str))
