name: Release packages

on:
  push:
    branches:
      - next

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'chore: release')"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Create Nugget package
        run: dotnet pack --configuration Release --output nugget

      - name: Publish NuGet package
        run: dotnet nuget push "nugget/*.nupkg" --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
