agentId:
  name: agentId
  in: path
  required: true
  description: Unique identifier of the agent.
  schema:
    type: string
    format: uuid
conversationId:
  name: conversationId
  in: path
  required: true
  description: Unique identifier of the conversation.
  schema:
    type: string
    format: uuid
providerId:
  name: providerId
  in: path
  required: true
  description: Unique identifier of the provider authentication.
  schema:
    type: string
    format: uuid
userToken:
  name: userToken
  in: path
  required: true
  description: Unique token identifying the user.
  schema:
    type: string
page:
  name: page
  in: query
  required: false
  description: Page number for pagination (0-indexed).
  schema:
    type: integer
    minimum: 0
    default: 0
hitsPerPage:
  name: hitsPerPage
  in: query
  required: false
  description: Number of items per page.
  schema:
    type: integer
    minimum: 1
    maximum: 100
    default: 20
stream:
  name: stream
  in: query
  required: false
  description: Whether to stream the response using Server-Sent Events.
  schema:
    type: boolean
    default: false
