// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

/// Whether NeuralSearch is active for the index. - `inactive`: keyword-only search is returned for live traffic. -
/// `active`: NeuralSearch (keyword + semantic) is returned for live traffic. - `preview`: NeuralSearch runs alongside
/// keyword search for comparison without affecting live results.
public enum NeuralSearchMode: String, Codable, CaseIterable {
    case inactive
    case active
    case preview
}

extension NeuralSearchMode: Hashable {}
