// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { ToolConfigInput } from './toolConfigInput';

export type AgentConfigCreate = {
  name: string;

  description?: string | null | undefined;

  providerId?: string | null | undefined;

  model?: string | null | undefined;

  /**
   * The agent prompt: defines the agent\'s role, tone, and goals. Guides how it answers using the provided context. Corresponds to the \'Agent prompt\' field in the dashboard.
   */
  instructions: string;

  systemPrompt?: string | null | undefined;

  templateType?: string | null | undefined;

  config?: { [key: string]: any } | undefined;

  tools?: Array<ToolConfigInput> | undefined;
};
