<?php
/**
 * AutomaticFacetFilterTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Algolia\AlgoliaSearch
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Search API
 *
 * API powering the Search feature of Algolia.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Algolia\AlgoliaSearch\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AutomaticFacetFilterTest Class Doc Comment
 *
 * @category    Class
 * @description Automatic facet Filter.
 * @package     Algolia\AlgoliaSearch
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AutomaticFacetFilterTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AutomaticFacetFilter"
     */
    public function testAutomaticFacetFilter()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "facet"
     */
    public function testPropertyFacet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "score"
     */
    public function testPropertyScore()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "disjunctive"
     */
    public function testPropertyDisjunctive()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
