# path
ID:
  in: path
  name: id
  description: Unique A/B test identifier.
  required: true
  schema:
    $ref: '#/abTestID'

# misc
index:
  type: string
  description: Index name of the A/B test variant (case-sensitive).
  example: 'delcourt_production'

abTestID:
  type: integer
  description: Unique A/B test identifier.
  example: 224

endAt:
  type: string
  description: End date and time of the A/B test, in RFC 3339 format.
  example: 2023-06-17T00:00:00Z

createdAt:
  type: string
  description: Date and time when the A/B test was created, in RFC 3339 format.
  example: 2023-06-15T15:06:04.249906Z

updatedAt:
  type: string
  description: Date and time when the A/B test was last updated, in RFC 3339 format.
  example: 2023-06-15T15:06:44.400601Z

stoppedAt:
  type: string
  description: Date and time when the A/B test was stopped, in RFC 3339 format.
  example: 2023-06-15T15:06:44.400601Z
  nullable: true

name:
  type: string
  description: A/B test name.
  example: Custom ranking sales rank test

description:
  type: string
  description: Description for this variant.
  example: Current production index

trafficPercentage:
  type: integer
  description: Percentage of search requests each variant receives.
  minimum: 0
  maximum: 100
  example: 60

currencies:
  type: object
  description: A/B test currencies.
  example:
    USD:
      currency: USD
      revenue: 120.0
      mean: 53.7
      standardDeviation: 12.3
      winsorizedAmount: 23.0
    EUR:
      currency: EUR
      revenue: 100.0
      mean: 43.7
      standardDeviation: 10.3
      winsorizedAmount: 10.0
  additionalProperties:
    $ref: '#/currency'
    x-additionalPropertiesName: currency code

currency:
  type: object
  properties:
    currency:
      type: string
      description: Currency code.
      example: 'USD'
    revenue:
      type: number
      format: double
      description: Revenue for this currency.
      example: 120.0
    mean:
      type: number
      format: double
      description: Mean for this currency.
      example: 53.7
    standardDeviation:
      type: number
      format: double
      description: Standard deviation for this currency.
      example: 12.3
    winsorizedAmount:
      type: number
      format: double
      description: The amount of revenue for this currency that was removed after capping purchase amounts to the 95th percentile.
      example: 23.0

filterEffects:
  type: object
  description: A/B test filter effects resulting from configuration settings.
  properties:
    outliers:
      title: outliersFilter
      type: object
      description: Outliers removed from the A/B test as a result of configuration settings.
      example:
        usersCount: 1
        trackedSearchesCount: 237
      properties:
        usersCount:
          type: integer
          description: Number of users removed from the A/B test.
          example: 1
        trackedSearchesCount:
          type: integer
          description: Number of tracked searches removed from the A/B test.
          example: 237
    emptySearch:
      title: emptySearchFilter
      type: object
      description: Empty searches removed from the A/B test as a result of configuration settings.
      example:
        usersCount: 1
        trackedSearchesCount: 237
      properties:
        usersCount:
          type: integer
          description: Number of users removed from the A/B test.
          example: 1
        trackedSearchesCount:
          type: integer
          description: Number of tracked searches removed from the A/B test.
          example: 237
