// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

export type AgentStudioClient = ReturnType<typeof createAgentStudioClient>;

import { createMemoryCache, createNullCache, createNullLogger } from '@algolia/client-common';
import { createFetchRequester } from '@algolia/requester-fetch';

import type { ClientOptions } from '@algolia/client-common';

import { createAgentStudioClient } from '../src/agentStudioClient';

import type { Region } from '../src/agentStudioClient';
import { REGIONS } from '../src/agentStudioClient';

export type { Region, RegionOptions } from '../src/agentStudioClient';

export { apiClientVersion } from '../src/agentStudioClient';

export * from '../model';

export function agentStudioClient(
  appId: string,
  apiKey: string,
  region: Region,
  options?: ClientOptions | undefined,
): AgentStudioClient {
  if (!appId || typeof appId !== 'string') {
    throw new Error('`appId` is missing.');
  }

  if (!apiKey || typeof apiKey !== 'string') {
    throw new Error('`apiKey` is missing.');
  }

  if (!region || (region && (typeof region !== 'string' || !REGIONS.includes(region)))) {
    throw new Error(`\`region\` is required and must be one of the following: ${REGIONS.join(', ')}`);
  }

  return {
    ...createAgentStudioClient({
      appId,
      apiKey,
      region,
      timeouts: {
        connect: 30000,
        read: 30000,
        write: 30000,
      },
      logger: createNullLogger(),
      requester: createFetchRequester(),
      algoliaAgents: [{ segment: 'Fetch' }],
      responsesCache: createNullCache(),
      requestsCache: createNullCache(),
      hostsCache: createMemoryCache(),
      ...options,
    }),
  };
}
