name: algolia_search
version: 1.0.0-dev.1
description: Dart search API client to interact with Algolia
homepage: https://www.algolia.com/doc/
repository: https://github.com/algolia/algoliasearch-client-dart/packages/algolia_search

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  algolia_client_core: '^0.1.0'
  dio: '^5.0.0'
  one_of: '>=1.5.0 <2.0.0'
  one_of_serializer: '>=1.5.0 <2.0.0'
  built_value: '>=8.4.0 <9.0.0'
  built_collection: '>=5.1.1 <6.0.0'

dev_dependencies:
  built_value_generator: '>=8.4.0 <9.0.0'
  build_runner: any
  test: ^1.16.0
