ReplaceExistingSynonyms:
  in: query
  name: replaceExistingSynonyms
  schema:
    type: boolean
  description: If `true`, delete all synonyms in the index and then add the ones sent with this request.

Query:
  in: query
  name: query
  description: Search for synonyms that match this string.
  schema:
    type: string
    default: ''

Type:
  in: query
  name: type
  description: Search for specific [types of synonym](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/adding-synonyms/#the-different-types-of-synonyms).
  schema:
    $ref: '#/SynonymType'

SynonymType:
  type: string
  description: Synonym type.
  example: onewaysynonym
  enum:
    - synonym
    - onewaysynonym
    - altcorrection1
    - altcorrection2
    - placeholder
