openapi: 3.0.2
info:
  title: Personalization API
  description: API powering the Personalization feature of Algolia.
  version: 0.0.1
components:
  securitySchemes:
    appId:
      type: apiKey
      in: header
      name: X-Algolia-Application-Id
    apiKey:
      type: apiKey
      in: header
      name: X-Algolia-API-Key
security:
  - appId: []
    apiKey: []
paths:
#  /1/profiles/personalization/{userToken}:
#    $ref: './paths/personalization_client/getUserTokenProfile.yml'
#  /1/profiles/{userToken}:
#    $ref: './paths/personalization_client/deleteUserProfile.yml'
#  /1/strategies/personalization:
#    $ref: './paths/personalization_client/getPersonalizationStrategy.yml'
#  /1/strategies/personalization:
#    $ref: './paths/personalization_client/setPersonalizationStrategy.yml'
