openapi: 3.0.2
info:
  title: A/B Testing API
  description: API powering the A/B Testing feature of Algolia.
  version: 0.0.1
components:
  securitySchemes:
    appId:
      type: apiKey
      in: header
      name: X-Algolia-Application-Id
    apiKey:
      type: apiKey
      in: header
      name: X-Algolia-API-Key
security:
  - appId: []
    apiKey: []
paths:
#  /2/abtests:
#    $ref: './paths/abtesting_client/addAbTest.yml'
#  /2/abtests/{id}:
#    $ref: './paths/abtesting_client/getAbTest.yml'
#  /2/abtests:
#    $ref: './paths/abtesting_client/listAbTests.yml'
#  /2/abtests/{id}/stop:
#    $ref: './paths/abtesting_client/stopAbTest.yml'
#  /2/abtests/{id}:
#    $ref: './paths/abtesting_client/deleteAbTest.yml'
