openapi: 3.0.2
info:
  title: Search API
  description: API powering the Search feature of Algolia.
  version: 0.1.0
servers:
  - url: https://{appId}-1.algolianet.com
    variables:
      appId:
        default: test
  - url: https://{appId}-2.algolianet.com
    variables:
      appId:
        default: test
  - url: https://{appId}-3.algolianet.com
    variables:
      appId:
        default: test
  - url: https://{appId}-dsn.algolianet.com
    variables:
      appId:
        default: test
components:
  securitySchemes:
    appId:
      type: apiKey
      in: header
      name: X-Algolia-Application-Id
    apiKey:
      type: apiKey
      in: header
      name: X-Algolia-API-Key
security:
  - appId: []
    apiKey: []
paths:
  # ########################
  # ### Search Endpoints ###
  # ########################
  /1/indexes/{indexName}/query:
    $ref: './paths/search_client/search/search.yml'
  /1/indexes/*/queries:
    $ref: './paths/search_client/search/multipleQueries.yml'
  #/1/indexes/{indexName}/facets/{facetName}/query:
  #  $ref: './paths/search_client/search/searchForFacetValues.yml'
  #/1/indexes/{indexName}/browse:
  #  $ref: './paths/search_client/search/browse.yml'
  #
  # #########################
  # ### Objects Endpoints ###
  # #########################
  /1/indexes/{indexName}:
    $ref: './paths/search_client/objects/saveObject.yml'
  # /1/indexes/{indexName}/{objectID}:
  #   $ref: './paths/search_client/objects/updateObject.yml'
  # /1/indexes/{indexName}/{objectID}:
  #   $ref: './paths/search_client/objects/deleteObject.yml'
  # /1/indexes/{indexName}/deleteByQuery:
  #   $ref: './paths/search_client/objects/deleteBy.yml'
  # /1/indexes/{indexName}/clear:
  #   $ref: './paths/search_client/objects/clearObjects.yml'
  # /1/indexes/{indexName}/{objectID}/partial:
  #   $ref: './paths/search_client/objects/partialUpdate.yml'
  /1/indexes/{indexName}/batch:
    $ref: './paths/search_client/objects/batch.yml'
  # /1/indexes/*/batch:
  #   $ref: './paths/search_client/objects/multipleBatch.yml'
  # /1/indexes/*/objects:
  #   $ref: './paths/search_client/objects/multipleGetObjects.yml'
  # /1/indexes/{indexName}/{objectID}:
  #   $ref: './paths/search_client/objects/getObject.yml'
  #
  # ##########################
  # ### Settings Endpoints ###
  # ##########################
  # /1/indexes/{indexName}/settings:
  #   $ref: './paths/search_client/settings/getSettings.yml'
  # /1/indexes/{indexName}/settings:
  #   $ref: './paths/search_client/settings/setSettings.yml'
  #
  # ################################
  # ### Manage Indices Endpoints ###
  # ################################
  # /1/indexes/{indexName}:
  #   $ref: './paths/search_client/manage_indices/deleteIndex.yml'
  # /1/indexes/{indexName}/operation:
  #   $ref: './paths/search_client/manage_indices/copyIndex.yml'
  # /1/indexes:
  #   $ref: './paths/search_client/manage_indices/listIndices.yml'
  #
  # ##########################
  # ### Synonyms Endpoints ###
  # ##########################
  # /1/indexes/{indexName}/synonyms/{objectID}:
  #   $ref: './paths/search_client/synonyms/saveSynonym.yml'
  # /1/indexes/{indexName}/synonyms/batch:
  #   $ref: './paths/search_client/synonyms/batchSynonyms.yml'
  # /1/indexes/{indexName}/synonyms/{objectID}:
  #   $ref: './paths/search_client/synonyms/getSynonym.yml'
  # /1/indexes/{indexName}/synonyms/clear:
  #   $ref: './paths/search_client/synonyms/clearAllSynonyms.yml'
  # /1/indexes/{indexName}/synonyms/{objectID}:
  #   $ref: './paths/search_client/synonyms/deleteSynonym.yml'
  # /1/indexes/{indexName}/synonyms/search:
  #   $ref: './paths/search_client/synonyms/searchSynonyms.yml'
  #
  # ######################
  # ### Keys Endpoints ###
  # ######################
  # /1/keys:
  #   $ref: './paths/search_client/keys/addApiKey.yml'
  # /1/keys/{key}:
  #   $ref: './paths/search_client/keys/updateApiKey.yml'
  # /1/keys:
  #   $ref: './paths/search_client/keys/listApiKeys.yml'
  # /1/keys/{key}:
  #   $ref: './paths/search_client/keys/getApiKey.yml'
  # /1/keys/{key}:
  #   $ref: './paths/search_client/keys/deleteApiKey.yml'
  # /1/keys/{key}/restore:
  #   $ref: './paths/search_client/keys/restoreApiKey.yml'
  #
  # #######################
  # ### Rules Endpoints ###
  # #######################
  # /1/indexes/{indexName}/rules/{objectID}:
  #   $ref: './paths/search_client/rules/saveRule.yml'
  # /1/indexes/{indexName}/rules/batch:
  #   $ref: './paths/search_client/rules/batchRules.yml'
  # /1/indexes/{indexName}/rules/{objectID}:
  #   $ref: './paths/search_client/rules/getRule.yml'
  # /1/indexes/{indexName}/rules/{objectID}:
  #   $ref: './paths/search_client/rules/deleteRule.yml'
  # /1/indexes/{indexName}/rules/clear:
  #   $ref: './paths/search_client/rules/clearRules.yml'
  # /1/indexes/{indexName}/rules/search:
  #   $ref: './paths/search_client/rules/searchRules.yml'
  #
  # ##############################
  # ### Dictionaries Endpoints ###
  # ##############################
  # /1/dictionaries/{dictionaryName}/batch:
  #   $ref: './paths/search_client/dictionaries/batchDictionaryEntries.yml'
  # /1/dictionaries/{dictionaryName}/search:
  #   $ref: './paths/search_client/dictionaries/searchDictionaryEntries.yml'
  # /1/dictionaries/*/settings:
  #   $ref: './paths/search_client/dictionaries/setDictionarySettings.yml'
  # /1/dictionaries/*/settings:
  #   $ref: './paths/search_client/dictionaries/getDictionarySettings.yml'
  # /1/dictionaries/*/languages:
  #   $ref: './paths/search_client/dictionaries/getDictionaryLanguages.yml'
  #
  # ###############################
  # ### MultiClusters Endpoints ###
  # ###############################
  # /1/clusters/mapping:
  #   $ref: './paths/search_client/multiclusters/assignUserId.yml'
  # /1/clusters/mapping/batch:
  #   $ref: './paths/search_client/multiclusters/batchAssignUserIds.yml'
  # /1/clusters/mapping/top:
  #   $ref: './paths/search_client/multiclusters/getTopUserIds.yml'
  # /1/clusters/mapping/${userID}:
  #   $ref: './paths/search_client/multiclusters/getUserId.yml'
  # /1/clusters:
  #   $ref: './paths/search_client/multiclusters/listClusters.yml'
  # /1/clusters/mapping:
  #   $ref: './paths/search_client/multiclusters/listUserIds.yml'
  # /1/clusters/mapping/${userID}:
  #   $ref: './paths/search_client/multiclusters/removeUserId.yml'
  # /1/clusters/mapping/search:
  #   $ref: './paths/search_client/multiclusters/searchUserIds.yml'
  # /1/clusters/mapping/pending:
  #   $ref: './paths/search_client/multiclusters/hasPendingMappings.yml'
  #
  # #######################
  # ### Vault Endpoints ###
  # #######################
  # /1/security/sources:
  #   $ref: './paths/search_client/vault/listSources.yml'
  # /1/security/sources:
  #   $ref: './paths/search_client/vault/replaceSources.yml'
  # /1/security/sources/append:
  #   $ref: './paths/search_client/vault/appendSource.yml'
  # /1/security/sources/{source}:
  #   $ref: './paths/search_client/vault/deleteSource.yml'
  #
  # ##########################
  # ### Advanced Endpoints ###
  # ##########################
  # /1/logs:
  #   $ref: './paths/search_client/advanced/getLogs.yml'
  # /1/indexes/{indexName}/task/{taskID}:
  #   $ref: './paths/search_client/advanced/getTask.yml'
  # /1/isalive:
  #   $ref: './paths/search_client/advanced/isAlive.yml'
