openapi: 3.0.2
info:
  title: Query Suggestions API
  description: API powering the Query Suggestions feature of Algolia.
  version: 0.0.1
servers:
  - url: https://{appId}-1.algolianet.com
    variables:
      appId:
        default: test
  - url: https://{appId}-2.algolianet.com
    variables:
      appId:
        default: test
  - url: https://{appId}-3.algolianet.com
    variables:
      appId:
        default: test
  - url: https://{appId}-dsn.algolianet.com
    variables:
      appId:
        default: test
components:
  securitySchemes:
    appId:
      type: apiKey
      in: header
      name: X-Algolia-Application-Id
    apiKey:
      type: apiKey
      in: header
      name: X-Algolia-API-Key
security:
  - appId: []
    apiKey: []
paths:
#  /1/configs:
#    $ref: './paths/query_suggestions_client/createConfiguration.yml'
#  /1/configs/{indexName}:
#    $ref: './paths/query_suggestions_client/updateConfiguration.yml'
#  /1/configs/{indexName}:
#    $ref: './paths/query_suggestions_client/deleteConfiguration.yml'
#  /1/configs/{indexName}:
#    $ref: './paths/query_suggestions_client/getConfiguration.yml'
#  /1/configs/{indexName}/status:
#    $ref: './paths/query_suggestions_client/getConfigurationStatus.yml'
#  /1/configs:
#    $ref: './paths/query_suggestions_client/getAllConfigurations.yml'
#  /1/logs/{indexName}:
#    $ref: './paths/query_suggestions_client/getLogFile.yml'
