openapi: 3.0.2
info:
  title: Event & Records Connection API
  description: API powering the ingestion of Events and Records
  version: 0.1.0
components:
  securitySchemes:
    appId:
      $ref: ../common/securitySchemes.yml#/appId
    apiKey:
      $ref: ../common/securitySchemes.yml#/apiKey
security:
  - appId: []
    apiKey: []
paths:
  /1/ingest/url:
    $ref: paths/ingest/postUrl.yml
