name: clientgen
description: Run the code generation
author: algolia
inputs:
  milliseconds: # change this
    required: true
    description: test
runs:
  using: 'node16'
  main: './builddir/index.js'
