type: object
description: Query Suggestions configuration.
additionalProperties: false
required:
  - sourceIndices
properties:
  sourceIndices:
    $ref: './SourceIndices.yml'
  languages:
    $ref: './Languages.yml'
  exclude:
    type: array
    nullable: true
    description: Patterns or words to exclude from the suggestions.
    items:
      type: string
      description: Word or regular expression to exclude from the suggestions.
  enablePersonalization:
    type: boolean
    default: false
    description: Whether to turn on personalized query suggestions.
  allowSpecialCharacters:
    type: boolean
    default: false
    description: Whether to include suggestions with special characters.
