QuerySuggestionsConfigurationResponse:
  type: object
  allOf:
    - $ref: '#/baseQuerySuggestionsConfigurationResponse'
    - $ref: './QuerySuggestionsConfigurationWithIndex.yml#/QuerySuggestionsConfigurationWithIndex'

baseQuerySuggestionsConfigurationResponse:
  type: object
  additionalProperties: false
  properties:
    sourceIndicesAPIKey:
      type: string
      description: API key used to read from your source index.
    suggestionsIndicesAPIKey:
      type: string
      description: API key used to write and configure your Query Suggestions index.
    externalIndicesAPIKey:
      type: string
      default: ''
      description: API key used to read from external Algolia indices.
