QuerySuggestionsConfigurationWithIndex:
  type: object
  description: Query Suggestions configuration.
  required:
    - indexName
    - sourceIndices
  allOf:
    - type: object
      properties:
        indexName:
          $ref: './QuerySuggestionsIndexName.yml'
    - $ref: './QuerySuggestionsConfiguration.yml'
