QuerySuggestionsConfigurationWithIndex:
  type: object
  description: Query Suggestions configuration.
  required:
    - indexName
    - sourceIndices
  allOf:
    - type: object
      properties:
        indexName:
          $ref: './QuerySuggestionsIndexName.yml'
    - $ref: '#/QuerySuggestionsConfiguration'

QuerySuggestionsConfiguration:
  type: object
  description: Query Suggestions configuration.
  required:
    - sourceIndices
  properties:
    sourceIndices:
      type: array
      description: Algolia indices from which to get the popular searches for query suggestions.
      minItems: 1
      items:
        $ref: '#/SourceIndex'
    languages:
      $ref: '#/Languages'
    exclude:
      type: array
      nullable: true
      default: null
      description: Patterns or words to exclude from the suggestions.
      items:
        type: string
        description: Word or regular expression to exclude from the suggestions.
    enablePersonalization:
      type: boolean
      default: false
      description: Whether to turn on personalized query suggestions.
    allowSpecialCharacters:
      type: boolean
      default: false
      description: Whether to include suggestions with special characters.

Languages:
  title: languages
  description: |
    Language for deduplicating singular and plural suggestions.
    If specified, only the more popular form is included.
  default: false
  oneOf:
    - type: array
      description: Languages for which to deduplicate singular and plural forms.
      items:
        type: string
        description: Two-letter country code.
    - type: boolean
      description: If true, deduplication is enabled for all suggestions.

SourceIndex:
  type: object
  description: Configuration of an Algolia index for Query Suggestions.
  required:
    - indexName
  properties:
    indexName:
      type: string
      description: Name of the Algolia index to use as source for query suggestions.
      example: products
    replicas:
      type: boolean
      default: false
      description: |
        If true, Query Suggestions uses all replica indices to find popular searches.
        If false, only the primary index is used.
      example: false
    analyticsTags:
      type: array
      nullable: true
      default: null
      description: |
        Analytics tags for filtering the popular searches.
        For more information, see [Segment your analytics data](https://www.algolia.com/doc/guides/search-analytics/guides/segments/).
      items:
        type: string
    facets:
      type: array
      nullable: true
      default: null
      items:
        $ref: '#/Facet'
      description: |
        Facets to use as top categories with your suggestions.

        If provided, Query Suggestions adds the top facet values to each suggestion.
      example:
        - attribute: category
          amount: 3
        - attribute: brand
          amount: 2
    minHits:
      type: integer
      minimum: 0
      default: 5
      description: |
        Minimum number of hits required to be included as a suggestion.

        A search query must at least generate `minHits` search results to be included in the Query Suggestions index.
    minLetters:
      type: integer
      minimum: 0
      default: 4
      description: |
        Minimum letters required to be included as a suggestion.

        A search query must be at least `minLetters` long to be included in the Query Suggestions index.
    generate:
      type: array
      nullable: true
      default: null
      description: |
        Facets used for generating query suggestions from facet values.

        For example, if you set `generate: ["color", "brand"]`, combinations from the facet values are added as query suggestions,
        such as "blue adidas", "red adidas", "blue nike", "red nike", etc.

        You can include nested lists.
      example:
        - [color, brand]
      items:
        type: array
        items:
          type: string
    external:
      type: array
      nullable: true
      default: null
      items:
        type: string
      description: |
        Algolia indices with popular searches to use as query suggestions.

        Records of these indices must have these attributes:

        - `query`: search query which will be added as a suggestion
        - `count`: measure of popularity of that search query

        For example, you can export popular searches from an external analytics provider, such as Google Analytics or Adobe Analytics,
        and feed this data into an Algolia index.
        You can use this index to generate query suggestions until your Algolia Analytics has collected enough data.

Facet:
  description: Facet to use as category.
  type: object
  properties:
    attribute:
      type: string
      description: Facet name.
    amount:
      type: integer
      description: Number of suggestions.
