type: object
description: Query Suggestions configuration.
additionalProperties: false
required:
  - sourceIndices
properties:
  sourceIndices:
    $ref: './SourceIndices.yml'
  languages:
    $ref: './Languages.yml'
  exclude:
    oneOf:
      - type: array
        description: Patterns to exclude from query suggestions.
        items:
          type: string
      - type: 'null'
  enablePersonalization:
    type: boolean
    default: false
    description: Turn on personalized query suggestions.
  allowSpecialCharacters:
    type: boolean
    default: false
    description: Allow suggestions with special characters.
