//
// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Algolia.Search.Serializer;

namespace Algolia.Search.Models.AbtestingV3;

/// <summary>
/// Metric that determines the A/B test's end-test recommendation.
/// </summary>
/// <value>Metric that determines the A/B test's end-test recommendation.</value>
[JsonConverter(typeof(Serializer.JsonStringEnumConverter<PrimaryMetric>))]
public enum PrimaryMetric
{
  /// <summary>
  /// Enum AddToCartRate for value: add_to_cart_rate
  /// </summary>
  [JsonPropertyName("add_to_cart_rate")]
  AddToCartRate = 1,

  /// <summary>
  /// Enum ClickThroughRate for value: click_through_rate
  /// </summary>
  [JsonPropertyName("click_through_rate")]
  ClickThroughRate = 2,

  /// <summary>
  /// Enum ConversionRate for value: conversion_rate
  /// </summary>
  [JsonPropertyName("conversion_rate")]
  ConversionRate = 3,

  /// <summary>
  /// Enum PurchaseRate for value: purchase_rate
  /// </summary>
  [JsonPropertyName("purchase_rate")]
  PurchaseRate = 4,

  /// <summary>
  /// Enum NoResultsRate for value: no_results_rate
  /// </summary>
  [JsonPropertyName("no_results_rate")]
  NoResultsRate = 5,
}
