compositionID:
  in: path
  name: compositionID
  description: Unique Composition ObjectID.
  required: true
  schema:
    $ref: '#/compositionObjectID'

compositionObjectID:
  type: string
  description: Unique Composition ObjectID.
