# path
UserToken:
  name: userToken
  in: path
  required: true
  description: userToken representing the user for which to fetch the Personalization profile.
  schema:
    type: string

# misc
userToken:
  type: string
  description: userToken representing the user for which to fetch the Personalization profile.
