authenticationID:
  name: authenticationID
  in: path
  description: The authentication uuid.
  required: true
  schema:
    type: string
    example: 6c02aeb1-775e-418e-870b-1faccd4b2c0f

destinationID:
  name: destinationID
  in: path
  description: The destination uuid.
  required: true
  schema:
    type: string
    example: 6c02aeb1-775e-418e-870b-1faccd4b2c0f

sourceID:
  name: sourceID
  in: path
  description: The source uuid.
  required: true
  schema:
    type: string
    example: 6c02aeb1-775e-418e-870b-1faccd4b2c0f

taskID:
  name: taskID
  in: path
  description: The task uuid.
  required: true
  schema:
    type: string
    example: 6c02aeb1-775e-418e-870b-1faccd4b2c0f
