pathAuthenticationID:
  name: authenticationID
  in: path
  required: true
  description: Unique identifier of an authentication resource.
  schema:
    $ref: './schemas/common.yml#/authenticationID'

pathDestinationID:
  name: destinationID
  in: path
  required: true
  description: Unique identifier of a destination.
  schema:
    $ref: './schemas/common.yml#/destinationID'

pathSourceID:
  name: sourceID
  in: path
  required: true
  description: Unique identifier of a source.
  schema:
    $ref: './schemas/common.yml#/sourceID'

pathTaskID:
  name: taskID
  in: path
  required: true
  description: Unique identifier of a task.
  schema:
    $ref: './schemas/common.yml#/taskID'

pathRunID:
  name: runID
  in: path
  required: true
  description: Unique identifier of a task run.
  schema:
    $ref: './schemas/common.yml#/runID'

pathEventID:
  name: eventID
  in: path
  required: true
  description: Unique identifier of an event.
  schema:
    $ref: './schemas/common.yml#/eventID'

itemsPerPage:
  name: itemsPerPage
  in: query
  description: Number of items per page.
  required: false
  schema:
    $ref: './schemas/pagination.yml#/itemsPerPage'

page:
  name: page
  in: query
  description: Page number of the paginated API response.
  required: false
  schema:
    $ref: './schemas/pagination.yml#/page'

order:
  name: order
  in: query
  description: Sort order of the response, ascending or descending.
  required: false
  schema:
    $ref: '#/orderKeys'

orderKeys:
  type: string
  description: Ascending or descending sort order.
  default: desc
  enum: [asc, desc]
