userID:
  name: userID
  in: path
  required: true
  schema:
    type: string
  description: User ID for authenticated users or cookie ID for non-authenticated repeated users (visitors).
segmentID:
  name: segmentID
  in: path
  required: true
  schema:
    type: string
  description: The ID of the Segment to retrieve.
