userID:
  name: userID
  in: path
  required: true
  schema:
    type: string
  description: |
    This parameter can have different values:
    * An user ID for authenticated users.
    * A cookie ID for non-authenticated repeated users (visitors)
