// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package algoliasearch.requests

import algoliasearch.EchoInterceptor
import algoliasearch.api.AgentStudioClient
import algoliasearch.config.*
import algoliasearch.agentstudio.*
import org.json4s.*
import org.json4s.native.JsonParser.*
import org.scalatest.funsuite.AnyFunSuite

import java.util.concurrent.TimeUnit
import scala.concurrent.duration.Duration
import scala.concurrent.{Await, ExecutionContextExecutor}

class AgentStudioTest extends AnyFunSuite {
  implicit val ec: ExecutionContextExecutor = scala.concurrent.ExecutionContext.global
  implicit val formats: Formats = JsonSupport.format

  def testClient(): (AgentStudioClient, EchoInterceptor) = {
    val echo = EchoInterceptor()
    (
      AgentStudioClient(
        appId = "appId",
        apiKey = "apiKey",
        clientOptions = ClientOptions
          .builder()
          .withRequesterConfig(requester => requester.withInterceptor(echo))
          .build()
      ),
      echo
    )
  }

  test("bulkCreateAllowedDomains") {
    val (client, echo) = testClient()
    val future = client.bulkCreateAllowedDomains(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
      allowedDomainBulkInsert = AllowedDomainBulkInsert(
        domains = Seq("https://app.example.com", "*.example.org")
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/allowed-domains/bulk")
    assert(res.method == "POST")
    val expectedBody = parse("""{"domains":["https://app.example.com","*.example.org"]}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
  }

  test("bulkDeleteAllowedDomains") {
    val (client, echo) = testClient()
    val future = client.bulkDeleteAllowedDomains(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
      allowedDomainBulkDelete = AllowedDomainBulkDelete(
        domainIds = Seq("a1b2c3d4-5678-90ab-cdef-123456789abc", "b2c3d4e5-6789-01ab-cdef-234567890abc")
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/allowed-domains/bulk")
    assert(res.method == "DELETE")
    val expectedBody =
      parse("""{"domainIds":["a1b2c3d4-5678-90ab-cdef-123456789abc","b2c3d4e5-6789-01ab-cdef-234567890abc"]}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
  }

  test("createAgent with minimal parameters") {
    val (client, echo) = testClient()
    val future = client.createAgent(
      agentConfigCreate = AgentConfigCreate(
        name = "test-agent",
        instructions = "You are a helpful assistant."
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents")
    assert(res.method == "POST")
    val expectedBody = parse("""{"name":"test-agent","instructions":"You are a helpful assistant."}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
  }

  test("createAgent with all parameters1") {
    val (client, echo) = testClient()
    val future = client.createAgent(
      agentConfigCreate = AgentConfigCreate(
        name = "test-agent",
        description = Some("A test agent for CTS"),
        providerId = Some("5e33d805-7892-4329-bda7-b524dc3fd04a"),
        model = Some("gpt-4"),
        instructions = "You are a helpful assistant.",
        config = Some(Map("sendUsage" -> true, "sendReasoning" -> true, "temperature" -> 0.7, "max_tokens" -> 1500)),
        tools = Some(
          Seq(
            AlgoliaDisplayResultsToolConfig(
              `type` = "start"
            )
          )
        )
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents")
    assert(res.method == "POST")
    val expectedBody = parse(
      """{"name":"test-agent","description":"A test agent for CTS","providerId":"5e33d805-7892-4329-bda7-b524dc3fd04a","model":"gpt-4","instructions":"You are a helpful assistant.","config":{"sendUsage":true,"sendReasoning":true,"temperature":0.7,"max_tokens":1500},"tools":[{"type":"start"}]}"""
    )
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
  }

  test("createAgentAllowedDomain") {
    val (client, echo) = testClient()
    val future = client.createAgentAllowedDomain(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
      allowedDomainCreate = AllowedDomainCreate(
        domain = "https://app.example.com"
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/allowed-domains")
    assert(res.method == "POST")
    val expectedBody = parse("""{"domain":"https://app.example.com"}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
  }

  test("createAgentCompletion with v4 messages") {
    val (client, echo) = testClient()
    val future = client.createAgentCompletion(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
      compatibilityMode = CompatibilityMode.withName("ai-sdk-4"),
      agentCompletionRequest = AgentCompletionRequest(
        messages = Some(
          MessagesNullableUnionUnion(
            Seq(
              UserMessageV4(
                role = "user",
                content = "Hello, how are you?"
              )
            )
          )
        )
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/completions")
    assert(res.method == "POST")
    val expectedBody = parse("""{"messages":[{"role":"user","content":"Hello, how are you?"}]}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
    val expectedQuery = parse("""{"compatibilityMode":"ai-sdk-4"}""").asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
  }

  test("createFeedback with required parameters") {
    val (client, echo) = testClient()
    val future = client.createFeedback(
      feedbackCreationRequest = FeedbackCreationRequest(
        messageId = "msg-abc123",
        agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
        vote = VoteEnum.withName("1")
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/feedback")
    assert(res.method == "POST")
    val expectedBody = parse("""{"messageId":"msg-abc123","agentId":"785b14e4-61a8-4c03-8028-bf2ba3ae85ff","vote":1}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
  }

  test("createFeedback with all parameters1") {
    val (client, echo) = testClient()
    val future = client.createFeedback(
      feedbackCreationRequest = FeedbackCreationRequest(
        messageId = "msg-abc123",
        agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
        vote = VoteEnum.withName("0"),
        tags = Some(Seq("unhelpful", "off-topic")),
        notes = Some("The response did not address my question.")
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/feedback")
    assert(res.method == "POST")
    val expectedBody = parse(
      """{"messageId":"msg-abc123","agentId":"785b14e4-61a8-4c03-8028-bf2ba3ae85ff","vote":0,"tags":["unhelpful","off-topic"],"notes":"The response did not address my question."}"""
    )
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
  }

  test("createProvider with OpenAI") {
    val (client, echo) = testClient()
    val future = client.createProvider(
      providerAuthenticationCreate = ProviderAuthenticationCreate(
        name = "My OpenAI Provider",
        providerName = ProviderName.withName("openai"),
        input = OpenAIProviderInputInput(
          apiKey = "sk-test-key-1234"
        )
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/providers")
    assert(res.method == "POST")
    val expectedBody =
      parse("""{"name":"My OpenAI Provider","providerName":"openai","input":{"apiKey":"sk-test-key-1234"}}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
  }

  test("createProvider with Azure OpenAI1") {
    val (client, echo) = testClient()
    val future = client.createProvider(
      providerAuthenticationCreate = ProviderAuthenticationCreate(
        name = "My Azure Provider",
        providerName = ProviderName.withName("azure_openai"),
        input = AzureOpenAIProviderInputInput(
          apiKey = "az-test-key-5678",
          azureEndpoint = "https://my-resource.openai.azure.com",
          azureDeployment = "gpt-4o"
        )
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/providers")
    assert(res.method == "POST")
    val expectedBody = parse(
      """{"name":"My Azure Provider","providerName":"azure_openai","input":{"apiKey":"az-test-key-5678","azureEndpoint":"https://my-resource.openai.azure.com","azureDeployment":"gpt-4o"}}"""
    )
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
  }

  test("createSecretKey with minimal parameters") {
    val (client, echo) = testClient()
    val future = client.createSecretKey(
      secretKeyCreate = SecretKeyCreate(
        name = "my-secret-key"
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/secret-keys")
    assert(res.method == "POST")
    val expectedBody = parse("""{"name":"my-secret-key"}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
  }

  test("createSecretKey with agent IDs1") {
    val (client, echo) = testClient()
    val future = client.createSecretKey(
      secretKeyCreate = SecretKeyCreate(
        name = "scoped-key",
        agentIds = Some(Seq("785b14e4-61a8-4c03-8028-bf2ba3ae85ff"))
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/secret-keys")
    assert(res.method == "POST")
    val expectedBody = parse("""{"name":"scoped-key","agentIds":["785b14e4-61a8-4c03-8028-bf2ba3ae85ff"]}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
  }

  test("allow del method for a custom path with minimal parameters") {
    val (client, echo) = testClient()
    val future = client.customDelete[JObject](
      path = "test/minimal"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/test/minimal")
    assert(res.method == "DELETE")
    assert(res.body.isEmpty)
  }

  test("allow del method for a custom path with all parameters1") {
    val (client, echo) = testClient()
    val future = client.customDelete[JObject](
      path = "test/all",
      parameters = Some(Map("query" -> "parameters"))
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/test/all")
    assert(res.method == "DELETE")
    assert(res.body.isEmpty)
    val expectedQuery = parse("""{"query":"parameters"}""").asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
  }

  test("allow get method for a custom path with minimal parameters") {
    val (client, echo) = testClient()
    val future = client.customGet[JObject](
      path = "test/minimal"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/test/minimal")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("allow get method for a custom path with all parameters1") {
    val (client, echo) = testClient()
    val future = client.customGet[JObject](
      path = "test/all",
      parameters = Some(Map("query" -> "parameters with space"))
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/test/all")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
    val expectedQuery = parse("""{"query":"parameters%20with%20space"}""").asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
  }

  test("requestOptions should be escaped too2") {
    val (client, echo) = testClient()
    val future = client.customGet[JObject](
      path = "test/all",
      parameters = Some(Map("query" -> "to be overridden")),
      requestOptions = Some(
        RequestOptions
          .builder()
          .withQueryParameter("query", "parameters with space")
          .withQueryParameter("and an array", Seq("array", "with spaces"))
          .withHeader("x-header-1", "spaces are left alone")
          .build()
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/test/all")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
    val expectedQuery = parse("""{"query":"parameters%20with%20space","and%20an%20array":"array%2Cwith%20spaces"}""")
      .asInstanceOf[JObject]
      .obj
      .toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
    val expectedHeaders = parse("""{"x-header-1":"spaces are left alone"}""").asInstanceOf[JObject].obj.toMap
    val actualHeaders = res.headers
    for ((k, v) <- expectedHeaders) {
      assert(actualHeaders.contains(k))
      assert(actualHeaders(k) == v.asInstanceOf[JString].s)
    }
  }

  test("allow post method for a custom path with minimal parameters") {
    val (client, echo) = testClient()
    val future = client.customPost[JObject](
      path = "test/minimal"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/test/minimal")
    assert(res.method == "POST")
    val expectedBody = parse("""{}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
  }

  test("allow post method for a custom path with all parameters1") {
    val (client, echo) = testClient()
    val future = client.customPost[JObject](
      path = "test/all",
      parameters = Some(Map("query" -> "parameters")),
      body = Some(JObject(List(JField("body", JString("parameters")))))
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/test/all")
    assert(res.method == "POST")
    val expectedBody = parse("""{"body":"parameters"}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
    val expectedQuery = parse("""{"query":"parameters"}""").asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
  }

  test("requestOptions can override default query parameters2") {
    val (client, echo) = testClient()
    val future = client.customPost[JObject](
      path = "test/requestOptions",
      parameters = Some(Map("query" -> "parameters")),
      body = Some(JObject(List(JField("facet", JString("filters"))))),
      requestOptions = Some(
        RequestOptions
          .builder()
          .withQueryParameter("query", "myQueryParameter")
          .build()
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/test/requestOptions")
    assert(res.method == "POST")
    val expectedBody = parse("""{"facet":"filters"}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
    val expectedQuery = parse("""{"query":"myQueryParameter"}""").asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
  }

  test("requestOptions merges query parameters with default ones3") {
    val (client, echo) = testClient()
    val future = client.customPost[JObject](
      path = "test/requestOptions",
      parameters = Some(Map("query" -> "parameters")),
      body = Some(JObject(List(JField("facet", JString("filters"))))),
      requestOptions = Some(
        RequestOptions
          .builder()
          .withQueryParameter("query2", "myQueryParameter")
          .build()
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/test/requestOptions")
    assert(res.method == "POST")
    val expectedBody = parse("""{"facet":"filters"}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
    val expectedQuery = parse("""{"query":"parameters","query2":"myQueryParameter"}""").asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
  }

  test("requestOptions can override default headers4") {
    val (client, echo) = testClient()
    val future = client.customPost[JObject](
      path = "test/requestOptions",
      parameters = Some(Map("query" -> "parameters")),
      body = Some(JObject(List(JField("facet", JString("filters"))))),
      requestOptions = Some(
        RequestOptions
          .builder()
          .withHeader("x-algolia-api-key", "ALGOLIA_API_KEY")
          .build()
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/test/requestOptions")
    assert(res.method == "POST")
    val expectedBody = parse("""{"facet":"filters"}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
    val expectedQuery = parse("""{"query":"parameters"}""").asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
    val expectedHeaders = parse("""{"x-algolia-api-key":"ALGOLIA_API_KEY"}""").asInstanceOf[JObject].obj.toMap
    val actualHeaders = res.headers
    for ((k, v) <- expectedHeaders) {
      assert(actualHeaders.contains(k))
      assert(actualHeaders(k) == v.asInstanceOf[JString].s)
    }
  }

  test("requestOptions merges headers with default ones5") {
    val (client, echo) = testClient()
    val future = client.customPost[JObject](
      path = "test/requestOptions",
      parameters = Some(Map("query" -> "parameters")),
      body = Some(JObject(List(JField("facet", JString("filters"))))),
      requestOptions = Some(
        RequestOptions
          .builder()
          .withHeader("x-algolia-api-key", "ALGOLIA_API_KEY")
          .build()
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/test/requestOptions")
    assert(res.method == "POST")
    val expectedBody = parse("""{"facet":"filters"}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
    val expectedQuery = parse("""{"query":"parameters"}""").asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
    val expectedHeaders = parse("""{"x-algolia-api-key":"ALGOLIA_API_KEY"}""").asInstanceOf[JObject].obj.toMap
    val actualHeaders = res.headers
    for ((k, v) <- expectedHeaders) {
      assert(actualHeaders.contains(k))
      assert(actualHeaders(k) == v.asInstanceOf[JString].s)
    }
  }

  test("requestOptions queryParameters accepts booleans6") {
    val (client, echo) = testClient()
    val future = client.customPost[JObject](
      path = "test/requestOptions",
      parameters = Some(Map("query" -> "parameters")),
      body = Some(JObject(List(JField("facet", JString("filters"))))),
      requestOptions = Some(
        RequestOptions
          .builder()
          .withQueryParameter("isItWorking", true)
          .build()
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/test/requestOptions")
    assert(res.method == "POST")
    val expectedBody = parse("""{"facet":"filters"}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
    val expectedQuery = parse("""{"query":"parameters","isItWorking":"true"}""").asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
  }

  test("requestOptions queryParameters accepts integers7") {
    val (client, echo) = testClient()
    val future = client.customPost[JObject](
      path = "test/requestOptions",
      parameters = Some(Map("query" -> "parameters")),
      body = Some(JObject(List(JField("facet", JString("filters"))))),
      requestOptions = Some(
        RequestOptions
          .builder()
          .withQueryParameter("myParam", 2)
          .build()
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/test/requestOptions")
    assert(res.method == "POST")
    val expectedBody = parse("""{"facet":"filters"}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
    val expectedQuery = parse("""{"query":"parameters","myParam":"2"}""").asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
  }

  test("requestOptions queryParameters accepts list of string8") {
    val (client, echo) = testClient()
    val future = client.customPost[JObject](
      path = "test/requestOptions",
      parameters = Some(Map("query" -> "parameters")),
      body = Some(JObject(List(JField("facet", JString("filters"))))),
      requestOptions = Some(
        RequestOptions
          .builder()
          .withQueryParameter("myParam", Seq("b and c", "d"))
          .build()
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/test/requestOptions")
    assert(res.method == "POST")
    val expectedBody = parse("""{"facet":"filters"}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
    val expectedQuery = parse("""{"query":"parameters","myParam":"b%20and%20c%2Cd"}""").asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
  }

  test("requestOptions queryParameters accepts list of booleans9") {
    val (client, echo) = testClient()
    val future = client.customPost[JObject](
      path = "test/requestOptions",
      parameters = Some(Map("query" -> "parameters")),
      body = Some(JObject(List(JField("facet", JString("filters"))))),
      requestOptions = Some(
        RequestOptions
          .builder()
          .withQueryParameter("myParam", Seq(true, true, false))
          .build()
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/test/requestOptions")
    assert(res.method == "POST")
    val expectedBody = parse("""{"facet":"filters"}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
    val expectedQuery =
      parse("""{"query":"parameters","myParam":"true%2Ctrue%2Cfalse"}""").asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
  }

  test("requestOptions queryParameters accepts list of integers10") {
    val (client, echo) = testClient()
    val future = client.customPost[JObject](
      path = "test/requestOptions",
      parameters = Some(Map("query" -> "parameters")),
      body = Some(JObject(List(JField("facet", JString("filters"))))),
      requestOptions = Some(
        RequestOptions
          .builder()
          .withQueryParameter("myParam", Seq(1, 2))
          .build()
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/test/requestOptions")
    assert(res.method == "POST")
    val expectedBody = parse("""{"facet":"filters"}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
    val expectedQuery = parse("""{"query":"parameters","myParam":"1%2C2"}""").asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
  }

  test("allow put method for a custom path with minimal parameters") {
    val (client, echo) = testClient()
    val future = client.customPut[JObject](
      path = "test/minimal"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/test/minimal")
    assert(res.method == "PUT")
    val expectedBody = parse("""{}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
  }

  test("allow put method for a custom path with all parameters1") {
    val (client, echo) = testClient()
    val future = client.customPut[JObject](
      path = "test/all",
      parameters = Some(Map("query" -> "parameters")),
      body = Some(JObject(List(JField("body", JString("parameters")))))
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/test/all")
    assert(res.method == "PUT")
    val expectedBody = parse("""{"body":"parameters"}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
    val expectedQuery = parse("""{"query":"parameters"}""").asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
  }

  test("deleteAgent") {
    val (client, echo) = testClient()
    val future = client.deleteAgent(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff")
    assert(res.method == "DELETE")
    assert(res.body.isEmpty)
  }

  test("deleteAgentConversations without filters") {
    val (client, echo) = testClient()
    val future = client.deleteAgentConversations(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations")
    assert(res.method == "DELETE")
    assert(res.body.isEmpty)
  }

  test("deleteAgentConversations with date filters1") {
    val (client, echo) = testClient()
    val future = client.deleteAgentConversations(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
      startDate = Some("2024-01-01"),
      endDate = Some("2024-06-30")
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations")
    assert(res.method == "DELETE")
    assert(res.body.isEmpty)
    val expectedQuery = parse("""{"startDate":"2024-01-01","endDate":"2024-06-30"}""").asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
  }

  test("deleteAllowedDomain") {
    val (client, echo) = testClient()
    val future = client.deleteAllowedDomain(
      domainId = "a1b2c3d4-5678-90ab-cdef-123456789abc",
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(
      res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/allowed-domains/a1b2c3d4-5678-90ab-cdef-123456789abc"
    )
    assert(res.method == "DELETE")
    assert(res.body.isEmpty)
  }

  test("deleteConversation") {
    val (client, echo) = testClient()
    val future = client.deleteConversation(
      conversationId = "test-conversation-id",
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations/test-conversation-id")
    assert(res.method == "DELETE")
    assert(res.body.isEmpty)
  }

  test("deleteProvider") {
    val (client, echo) = testClient()
    val future = client.deleteProvider(
      providerId = "5e33d805-7892-4329-bda7-b524dc3fd04a"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/providers/5e33d805-7892-4329-bda7-b524dc3fd04a")
    assert(res.method == "DELETE")
    assert(res.body.isEmpty)
  }

  test("deleteSecretKey") {
    val (client, echo) = testClient()
    val future = client.deleteSecretKey(
      secretKeyId = "a1b2c3d4-5678-90ab-cdef-123456789abc"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/secret-keys/a1b2c3d4-5678-90ab-cdef-123456789abc")
    assert(res.method == "DELETE")
    assert(res.body.isEmpty)
  }

  test("deleteUserData") {
    val (client, echo) = testClient()
    val future = client.deleteUserData(
      userToken = "test-user-token"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/user-data/test-user-token")
    assert(res.method == "DELETE")
    assert(res.body.isEmpty)
  }

  test("exportConversations without filters") {
    val (client, echo) = testClient()
    val future = client.exportConversations(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations/export")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("exportConversations with date filters1") {
    val (client, echo) = testClient()
    val future = client.exportConversations(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
      startDate = Some("2024-01-01"),
      endDate = Some("2024-12-31")
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations/export")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
    val expectedQuery = parse("""{"startDate":"2024-01-01","endDate":"2024-12-31"}""").asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
  }

  test("e2e export conversations2") {
    val (client, echo) = testClient()
    val future = client.exportConversations(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations/export")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("getAgent") {
    val (client, echo) = testClient()
    val future = client.getAgent(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("e2e get agent1") {
    val (client, echo) = testClient()
    val future = client.getAgent(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("getAllowedDomain") {
    val (client, echo) = testClient()
    val future = client.getAllowedDomain(
      domainId = "a1b2c3d4-5678-90ab-cdef-123456789abc",
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(
      res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/allowed-domains/a1b2c3d4-5678-90ab-cdef-123456789abc"
    )
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("e2e get allowed domain1") {
    val (client, echo) = testClient()
    val future = client.getAllowedDomain(
      domainId = "6486b782-6b4c-4c93-bbba-04849ae4d101",
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(
      res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/allowed-domains/6486b782-6b4c-4c93-bbba-04849ae4d101"
    )
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("getConfiguration") {
    val (client, echo) = testClient()
    val future = client.getConfiguration(
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/configuration")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("e2e getConfiguration1") {
    val (client, echo) = testClient()
    val future = client.getConfiguration(
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/configuration")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("getConversation") {
    val (client, echo) = testClient()
    val future = client.getConversation(
      conversationId = "test-conversation-id",
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations/test-conversation-id")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("e2e get conversation1") {
    val (client, echo) = testClient()
    val future = client.getConversation(
      conversationId = "dashboard-eacdd4aa-9a80-4f5b-b657-f04b7fd34082",
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(
      res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations/dashboard-eacdd4aa-9a80-4f5b-b657-f04b7fd34082"
    )
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("getProvider") {
    val (client, echo) = testClient()
    val future = client.getProvider(
      providerId = "5e33d805-7892-4329-bda7-b524dc3fd04a"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/providers/5e33d805-7892-4329-bda7-b524dc3fd04a")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("e2e get provider1") {
    val (client, echo) = testClient()
    val future = client.getProvider(
      providerId = "5e33d805-7892-4329-bda7-b524dc3fd04a"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/providers/5e33d805-7892-4329-bda7-b524dc3fd04a")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("getSecretKey") {
    val (client, echo) = testClient()
    val future = client.getSecretKey(
      secretKeyId = "a1b2c3d4-5678-90ab-cdef-123456789abc"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/secret-keys/a1b2c3d4-5678-90ab-cdef-123456789abc")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("e2e get secret key1") {
    val (client, echo) = testClient()
    val future = client.getSecretKey(
      secretKeyId = "f730dda4-9649-4cfb-9d88-b7e992fb89c9"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/secret-keys/f730dda4-9649-4cfb-9d88-b7e992fb89c9")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("getUserData") {
    val (client, echo) = testClient()
    val future = client.getUserData(
      userToken = "test-user-token"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/user-data/test-user-token")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("invalidateAgentCache without before") {
    val (client, echo) = testClient()
    val future = client.invalidateAgentCache(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/cache")
    assert(res.method == "DELETE")
    assert(res.body.isEmpty)
  }

  test("invalidateAgentCache with before date1") {
    val (client, echo) = testClient()
    val future = client.invalidateAgentCache(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
      before = Some("2024-12-01")
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/cache")
    assert(res.method == "DELETE")
    assert(res.body.isEmpty)
    val expectedQuery = parse("""{"before":"2024-12-01"}""").asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
  }

  test("listAgentAllowed-Domains") {
    val (client, echo) = testClient()
    val future = client.listAgentAllowedDomains(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/allowed-domains")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("e2e list agent allowed domains1") {
    val (client, echo) = testClient()
    val future = client.listAgentAllowedDomains(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/allowed-domains")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("listAgentConversations with minimal parameters") {
    val (client, echo) = testClient()
    val future = client.listAgentConversations(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("listAgentConversations with all parameters1") {
    val (client, echo) = testClient()
    val future = client.listAgentConversations(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
      startDate = Some("2024-01-01"),
      endDate = Some("2024-12-31"),
      includeFeedback = Some(true),
      feedbackVote = Some(1),
      page = Some(2),
      limit = Some(10),
      xAlgoliaSecureUserToken = None
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
    val expectedQuery = parse(
      """{"startDate":"2024-01-01","endDate":"2024-12-31","includeFeedback":"true","feedbackVote":"1","page":"2","limit":"10"}"""
    ).asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
  }

  test("e2e list agent conversations2") {
    val (client, echo) = testClient()
    val future = client.listAgentConversations(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/conversations")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("list agents with no params") {
    val (client, echo) = testClient()
    val future = client.listAgents(
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("list agents with all parameters1") {
    val (client, echo) = testClient()
    val future = client.listAgents(
      page = Some(2),
      limit = Some(5),
      providerId = Some("5e33d805-7892-4329-bda7-b524dc3fd04a")
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
    val expectedQuery = parse("""{"page":"2","limit":"5","providerId":"5e33d805-7892-4329-bda7-b524dc3fd04a"}""")
      .asInstanceOf[JObject]
      .obj
      .toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
  }

  test("e2e list agents2") {
    val (client, echo) = testClient()
    val future = client.listAgents(
      page = Some(1),
      limit = Some(2),
      providerId = None
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
    val expectedQuery = parse("""{"page":"1","limit":"2"}""").asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
  }

  test("listModels") {
    val (client, echo) = testClient()
    val future = client.listModels(
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/providers/models")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("e2e list models1") {
    val (client, echo) = testClient()
    val future = client.listModels(
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/providers/models")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("listProviderModels") {
    val (client, echo) = testClient()
    val future = client.listProviderModels(
      providerId = "5e33d805-7892-4329-bda7-b524dc3fd04a"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/providers/5e33d805-7892-4329-bda7-b524dc3fd04a/models")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("e2e list provider models1") {
    val (client, echo) = testClient()
    val future = client.listProviderModels(
      providerId = "5e33d805-7892-4329-bda7-b524dc3fd04a"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/providers/5e33d805-7892-4329-bda7-b524dc3fd04a/models")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("listProviders with no params") {
    val (client, echo) = testClient()
    val future = client.listProviders(
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/providers")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("listProviders with pagination1") {
    val (client, echo) = testClient()
    val future = client.listProviders(
      page = Some(2),
      limit = Some(5)
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/providers")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
    val expectedQuery = parse("""{"page":"2","limit":"5"}""").asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
  }

  test("e2e list providers2") {
    val (client, echo) = testClient()
    val future = client.listProviders(
      page = Some(1),
      limit = Some(2)
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/providers")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
    val expectedQuery = parse("""{"page":"1","limit":"2"}""").asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
  }

  test("listSecretKeys with no params") {
    val (client, echo) = testClient()
    val future = client.listSecretKeys(
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/secret-keys")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
  }

  test("listSecretKeys with pagination1") {
    val (client, echo) = testClient()
    val future = client.listSecretKeys(
      page = Some(2),
      limit = Some(5)
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/secret-keys")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
    val expectedQuery = parse("""{"page":"2","limit":"5"}""").asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
  }

  test("e2e list secret keys2") {
    val (client, echo) = testClient()
    val future = client.listSecretKeys(
      page = Some(1),
      limit = Some(10)
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/secret-keys")
    assert(res.method == "GET")
    assert(res.body.isEmpty)
    val expectedQuery = parse("""{"page":"1","limit":"10"}""").asInstanceOf[JObject].obj.toMap
    val actualQuery = res.queryParameters
    assert(actualQuery.size == expectedQuery.size)
    for ((k, v) <- actualQuery) {
      assert(expectedQuery.contains(k))
      assert(expectedQuery(k).values == v)
    }
  }

  test("publishAgent") {
    val (client, echo) = testClient()
    val future = client.publishAgent(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/publish")
    assert(res.method == "POST")
    assert(res.body.contains("{}"))
  }

  test("unpublishAgent") {
    val (client, echo) = testClient()
    val future = client.unpublishAgent(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff"
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff/unpublish")
    assert(res.method == "POST")
    assert(res.body.contains("{}"))
  }

  test("updateAgent with minimal parameters") {
    val (client, echo) = testClient()
    val future = client.updateAgent(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
      agentConfigUpdate = AgentConfigUpdate(
        name = Some("updated-agent-name")
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff")
    assert(res.method == "PATCH")
    val expectedBody = parse("""{"name":"updated-agent-name"}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
  }

  test("updateAgent with all parameters1") {
    val (client, echo) = testClient()
    val future = client.updateAgent(
      agentId = "785b14e4-61a8-4c03-8028-bf2ba3ae85ff",
      agentConfigUpdate = AgentConfigUpdate(
        name = Some("updated-agent"),
        description = Some("Updated description"),
        providerId = Some("new-provider-id"),
        model = Some("gpt-4o"),
        instructions = Some("Updated instructions."),
        config = Some(Map("temperature" -> 0.5)),
        tools = Some(
          Seq(
            AlgoliaDisplayResultsToolConfig(
              `type` = "start"
            )
          )
        )
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/agents/785b14e4-61a8-4c03-8028-bf2ba3ae85ff")
    assert(res.method == "PATCH")
    val expectedBody = parse(
      """{"name":"updated-agent","description":"Updated description","providerId":"new-provider-id","model":"gpt-4o","instructions":"Updated instructions.","config":{"temperature":0.5},"tools":[{"type":"start"}]}"""
    )
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
  }

  test("updateConfiguration") {
    val (client, echo) = testClient()
    val future = client.updateConfiguration(
      applicationConfigPatch = ApplicationConfigPatch(
        maxRetentionDays = Some(30)
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/configuration")
    assert(res.method == "PATCH")
    val expectedBody = parse("""{"maxRetentionDays":30}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
  }

  test("updateProvider") {
    val (client, echo) = testClient()
    val future = client.updateProvider(
      providerId = "5e33d805-7892-4329-bda7-b524dc3fd04a",
      providerAuthenticationPatch = ProviderAuthenticationPatch(
        name = Some("Updated Provider Name")
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/providers/5e33d805-7892-4329-bda7-b524dc3fd04a")
    assert(res.method == "PATCH")
    val expectedBody = parse("""{"name":"Updated Provider Name"}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
  }

  test("updateProvider with input1") {
    val (client, echo) = testClient()
    val future = client.updateProvider(
      providerId = "5e33d805-7892-4329-bda7-b524dc3fd04a",
      providerAuthenticationPatch = ProviderAuthenticationPatch(
        name = Some("Updated Provider"),
        input = Some(
          OpenAIProviderInputInput(
            apiKey = "sk-new-key-5678"
          )
        )
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/providers/5e33d805-7892-4329-bda7-b524dc3fd04a")
    assert(res.method == "PATCH")
    val expectedBody = parse("""{"name":"Updated Provider","input":{"apiKey":"sk-new-key-5678"}}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
  }

  test("updateSecretKey") {
    val (client, echo) = testClient()
    val future = client.updateSecretKey(
      secretKeyId = "a1b2c3d4-5678-90ab-cdef-123456789abc",
      secretKeyPatch = SecretKeyPatch(
        name = Some("renamed-key"),
        agentIds = Some(Seq("785b14e4-61a8-4c03-8028-bf2ba3ae85ff"))
      )
    )

    Await.ready(future, Duration.Inf)
    val res = echo.lastResponse.get

    assert(res.path == "/agent-studio/1/secret-keys/a1b2c3d4-5678-90ab-cdef-123456789abc")
    assert(res.method == "PATCH")
    val expectedBody = parse("""{"name":"renamed-key","agentIds":["785b14e4-61a8-4c03-8028-bf2ba3ae85ff"]}""")
    val actualBody = parse(res.body.get)
    assert(actualBody == expectedBody)
  }

}
