# query
Attribute:
  in: query
  name: attribute
  description: The exact name of the attribute.
  required: true
  schema:
    type: string

Limit:
  in: query
  name: limit
  description: How many items to fetch.
  schema:
    type: integer
    default: 10

Search:
  in: query
  name: search
  description: The query term. Must match the exact user input.
  required: true
  schema:
    type: string

Offset:
  in: query
  name: offset
  description: From which position to start retrieving results.
  schema:
    type: integer
    default: 0

Tags:
  name: tags
  in: query
  description: Filter metrics on the provided tags. Each tag must correspond to an analyticsTags set at search time. Multiple tags can be combined with the operators OR and AND. If a tag contains characters like spaces or parentheses, it should be URL encoded.
  schema:
    type: string

# misc
average:
  type: number
  format: double
  description: The average of all the click count event.

clickCount:
  type: integer
  description: The number of click event.

date:
  type: string
  format: date-time
  description: Date of the event.

rate:
  type: number
  format: double
  description: The click-through rate.

trackedSearchCount:
  type: integer
  description: The number of tracked search click.

conversionCount:
  type: integer
  description: The number of converted clicks.

updatedAt:
  $ref: '../../../common/parameters.yml#/updatedAt'

attribute:
  description: The attribute.
  type: string

operator:
  description: The operator.
  type: string

value:
  description: The value of the attribute.
  type: string
