userID:
  name: X-Algolia-User-ID
  description: userID to assign.
  in: query
  required: true
  schema:
    type: string
    pattern: '^[a-zA-Z0-9 \-\*\.]+$'

users:
  name: users
  required: true
  schema:
    type: array
    items:
      type: string

page:
  name: page
  in: query
  schema:
    $ref: './schemas/SearchParams.yml#/baseSearchParams/properties/page'

hitsPerPage:
  name: hitsPerPage
  in: query
  schema:
    $ref: './schemas/IndexSettings.yml#/indexSettingsAsSearchParams/properties/hitsPerPage'
