# query
HitsPerPage:
  name: hitsPerPage
  description: Number of users to retrieve per page.
  in: query
  schema:
    type: integer
    description: Number of hits per page.
    default: 20

# headers
UserIDInHeader:
  name: X-Algolia-User-ID
  description: Unique identifier of the user who makes the search request.
  in: header
  required: true
  schema:
    $ref: '#/userID'

# path
UserIDInPath:
  name: userID
  description: Unique identifier of the user who makes the search request.
  in: path
  required: true
  schema:
    $ref: '#/userID'

# misc
userID:
  type: string
  pattern: '^[a-zA-Z0-9 \-*.]+$'
  description: Unique identifier of the user who makes the search request.
  example: user1
