AppId:
  name: X-Algolia-Application-Id
  in: header
  description: Algolia appID
  required: true
  schema:
    type: string
    pattern: '^(?:beta|testing)?[A-Z0-9]{10}$'
    example: 'DJNVGS47DK'
ApiKey:
  name: X-Algolia-API-Key
  in: header
  description: Algolia API key
  required: true
  schema:
    type: string
    pattern: '^[a-f0-9]{32}$'
    example: '43b15df305339e827f0ac0bdc5ebcaa7'
IndexName:
  name: indexName
  in: path
  description: The index in which to perform the request
  required: true
  schema:
    type: string
    example: 'myIndexName'
