# import apis
from algoliasearch.recommend.recommend_client import RecommendClient


# import models
from algoliasearch.recommend.advanced_syntax_features import AdvancedSyntaxFeatures
from algoliasearch.recommend.alternatives_as_exact import AlternativesAsExact
from algoliasearch.recommend.anchoring import Anchoring
from algoliasearch.recommend.around_precision import AroundPrecision
from algoliasearch.recommend.around_precision_from_value_inner import (
    AroundPrecisionFromValueInner,
)
from algoliasearch.recommend.around_radius import AroundRadius
from algoliasearch.recommend.around_radius_all import AroundRadiusAll
from algoliasearch.recommend.automatic_facet_filter import AutomaticFacetFilter
from algoliasearch.recommend.automatic_facet_filters import AutomaticFacetFilters
from algoliasearch.recommend.base_recommend_request import BaseRecommendRequest
from algoliasearch.recommend.base_recommendations_query import BaseRecommendationsQuery
from algoliasearch.recommend.base_search_params import BaseSearchParams
from algoliasearch.recommend.base_search_params_without_query import (
    BaseSearchParamsWithoutQuery,
)
from algoliasearch.recommend.base_search_response import BaseSearchResponse
from algoliasearch.recommend.base_trending_facets_query import BaseTrendingFacetsQuery
from algoliasearch.recommend.base_trending_items_query import BaseTrendingItemsQuery
from algoliasearch.recommend.condition import Condition
from algoliasearch.recommend.consequence import Consequence
from algoliasearch.recommend.consequence_hide import ConsequenceHide
from algoliasearch.recommend.consequence_params import ConsequenceParams
from algoliasearch.recommend.consequence_query import ConsequenceQuery
from algoliasearch.recommend.consequence_query_object import ConsequenceQueryObject
from algoliasearch.recommend.deleted_at_response import DeletedAtResponse
from algoliasearch.recommend.distinct import Distinct
from algoliasearch.recommend.edit import Edit
from algoliasearch.recommend.edit_type import EditType
from algoliasearch.recommend.error_base import ErrorBase
from algoliasearch.recommend.exact_on_single_word_query import ExactOnSingleWordQuery
from algoliasearch.recommend.exhaustive import Exhaustive
from algoliasearch.recommend.facet_filters import FacetFilters
from algoliasearch.recommend.facet_ordering import FacetOrdering
from algoliasearch.recommend.facets import Facets
from algoliasearch.recommend.facets_stats import FacetsStats
from algoliasearch.recommend.get_recommend_task_response import GetRecommendTaskResponse
from algoliasearch.recommend.get_recommendations_params import GetRecommendationsParams
from algoliasearch.recommend.get_recommendations_response import (
    GetRecommendationsResponse,
)
from algoliasearch.recommend.highlight_result import HighlightResult
from algoliasearch.recommend.highlight_result_option import HighlightResultOption
from algoliasearch.recommend.ignore_plurals import IgnorePlurals
from algoliasearch.recommend.index_settings_as_search_params import (
    IndexSettingsAsSearchParams,
)
from algoliasearch.recommend.match_level import MatchLevel
from algoliasearch.recommend.matched_geo_location import MatchedGeoLocation
from algoliasearch.recommend.mixed_search_filters import MixedSearchFilters
from algoliasearch.recommend.mode import Mode
from algoliasearch.recommend.numeric_filters import NumericFilters
from algoliasearch.recommend.optional_filters import OptionalFilters
from algoliasearch.recommend.params import Params
from algoliasearch.recommend.personalization import Personalization
from algoliasearch.recommend.promote import Promote
from algoliasearch.recommend.promote_object_id import PromoteObjectID
from algoliasearch.recommend.promote_object_ids import PromoteObjectIDs
from algoliasearch.recommend.query_type import QueryType
from algoliasearch.recommend.ranking_info import RankingInfo
from algoliasearch.recommend.re_ranking_apply_filter import ReRankingApplyFilter
from algoliasearch.recommend.recommend_hit import RecommendHit
from algoliasearch.recommend.recommend_hits import RecommendHits
from algoliasearch.recommend.recommend_models import RecommendModels
from algoliasearch.recommend.recommendation_models import RecommendationModels
from algoliasearch.recommend.recommendations_query import RecommendationsQuery
from algoliasearch.recommend.recommendations_request import RecommendationsRequest
from algoliasearch.recommend.recommendations_response import RecommendationsResponse
from algoliasearch.recommend.redirect import Redirect
from algoliasearch.recommend.redirect_rule_index_metadata import (
    RedirectRuleIndexMetadata,
)
from algoliasearch.recommend.redirect_rule_index_metadata_data import (
    RedirectRuleIndexMetadataData,
)
from algoliasearch.recommend.remove_stop_words import RemoveStopWords
from algoliasearch.recommend.remove_words_if_no_results import RemoveWordsIfNoResults
from algoliasearch.recommend.rendering_content import RenderingContent
from algoliasearch.recommend.rule_response import RuleResponse
from algoliasearch.recommend.rule_response_metadata import RuleResponseMetadata
from algoliasearch.recommend.search_params_object import SearchParamsObject
from algoliasearch.recommend.search_params_query import SearchParamsQuery
from algoliasearch.recommend.search_recommend_rules_params import (
    SearchRecommendRulesParams,
)
from algoliasearch.recommend.search_recommend_rules_response import (
    SearchRecommendRulesResponse,
)
from algoliasearch.recommend.semantic_search import SemanticSearch
from algoliasearch.recommend.snippet_result import SnippetResult
from algoliasearch.recommend.snippet_result_option import SnippetResultOption
from algoliasearch.recommend.sort_remaining_by import SortRemainingBy
from algoliasearch.recommend.tag_filters import TagFilters
from algoliasearch.recommend.task_status import TaskStatus
from algoliasearch.recommend.trending_facets_model import TrendingFacetsModel
from algoliasearch.recommend.trending_facets_query import TrendingFacetsQuery
from algoliasearch.recommend.trending_items_model import TrendingItemsModel
from algoliasearch.recommend.trending_items_query import TrendingItemsQuery
from algoliasearch.recommend.typo_tolerance import TypoTolerance
from algoliasearch.recommend.typo_tolerance_enum import TypoToleranceEnum
from algoliasearch.recommend.value import Value
