get:
  tags:
    - sources
  summary: List sources.
  description: Retrieves a list of sources.
  operationId: getSources
  x-acl:
    - addObject
    - deleteIndex
    - editSettings
  parameters:
    - $ref: '../../common/parameters.yml#/itemsPerPage'
    - $ref: '../../common/parameters.yml#/page'
    - $ref: '../../common/sourceParameters.yml#/type'
    - $ref: '../../common/sourceParameters.yml#/authenticationID'
    - $ref: '../../common/sourceParameters.yml#/sort'
    - $ref: '../../common/parameters.yml#/order'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            title: listSourcesResponse
            type: object
            additionalProperties: false
            properties:
              sources:
                type: array
                items:
                  $ref: '../../common/schemas/source.yml#/Source'
              pagination:
                $ref: '../../common/schemas/pagination.yml#/Pagination'
            required:
              - sources
              - pagination
    '400':
      $ref: '../../../common/responses/BadRequest.yml'

post:
  tags:
    - sources
  summary: Create a source.
  description: Creates a new source.
  operationId: createSource
  x-acl:
    - addObject
    - deleteIndex
    - editSettings
  requestBody:
    description: ''
    content:
      application/json:
        schema:
          $ref: '../../common/schemas/source.yml#/SourceCreate'
    required: true
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../../common/schemas/source.yml#/SourceCreateResponse'
    '400':
      $ref: '../../../common/responses/BadRequest.yml'
