openapi: 3.0.2
info:
  title: Algolia Monitoring API
  description: |
    The Monitoring API lets you check the status of your Algolia infrastructure.

    ## Base URLs

    The base URL for requests to the Monitoring API is:

    - `https://status.algolia.com`

    **All requests must use HTTPS.**

    ## Availability and authentication

    Access to the Infrastructure endpoints
    is available as part of the [Premium or Elevate plans](https://www.algolia.com/pricing).

    To authenticate requests to the Infrastructure endpoints, add these headers:

    - `x-algolia-application-id`. Your Algolia application ID.
    - `x-algolia-api-key`. Your Monitoring API key.

    You can find your application ID and API key in the [Algolia dashboard](https://dashboard.algolia.com/account/api-keys).

    Other endpoints don't require authentication.

    ## Response status and errors

    The Monitoring API returns JSON responses.
    Since JSON doesn't guarantee any specific ordering, don't rely on the order of attributes in the API response.

    Successful responses return a `2xx` status. Client errors return a `4xx` status. Server errors are indicated by a `5xx` status.
    Error responses have a `message` property with more information.

    ## Version

    The current version of the Monitoring API is version 1, as indicated by the `/1/` in each endpoint's URL.
  version: 1.0.0
servers:
  - url: https://status.algolia.com
components:
  securitySchemes:
    appId:
      type: apiKey
      in: header
      name: X-Algolia-Application-Id
      description: Your Algolia application ID.
    apiKey:
      type: apiKey
      in: header
      name: X-Algolia-API-Key
      description: Your Algolia Monitoring API key.
tags:
  - name: incidents
    description: List the known incidents.
    x-displayName: Incidents
  - name: infrastructure
    description: Return information about the Algolia infrastructure used by your application.
    x-displayName: Infrastructure
  - name: monitoring-tag
    description: Report search and indexing times for your clusters, and get a list of servers.
    x-displayName: Monitoring
  - name: status
    description: Report the status of Algolia clusters.
    x-displayName: Status
x-tagGroups:
  - name: General
    tags:
      - status
      - incidents
      - infrastructure
      - monitoring-tag
paths:
  # ######################
  # ### Custom request ###
  # ######################
  /{path}:
    $ref: '../common/paths/customRequest.yml'

  /1/status:
    $ref: 'paths/getStatus.yml'
  /1/status/{clusters}:
    $ref: 'paths/getClusterStatus.yml'
  /1/incidents:
    $ref: 'paths/getIncidents.yml'
  /1/incidents/{clusters}:
    $ref: 'paths/getClusterIncidents.yml'
  /1/inventory/servers:
    $ref: 'paths/getServers.yml'
  /1/latency/{clusters}:
    $ref: 'paths/getLatency.yml'
  /1/indexing/{clusters}:
    $ref: 'paths/getIndexingTime.yml'
  /1/reachability/{clusters}/probes:
    $ref: 'paths/getReachability.yml'
  /1/infrastructure/{metric}/period/{period}:
    $ref: 'paths/getMetrics.yml'

  # ###############
  # ### Helpers ###
  # ###############
  /setClientApiKey:
    $ref: '../common/helpers/setClientApiKey.yml#/method'
