name: client_javascript

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: ['16']
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Install Dependencies
        run: yarn install

      - name: Generate search client
        run: yarn generate:js:search

      - name: Build search client
        run: yarn client:build-js:search

      - name: Generate recommend client
        run: yarn generate:js:recommend

      - name: Build recommend client
        run: yarn client:build-js:recommend

      - name: Lint
        run: yarn prettier --check clients/algoliasearch-client-javascript
