name: client_javascript

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: './.github/setup/action.yml'

      - name: Generate search client
        run: yarn generate:js:search

      - name: Build search client
        run: yarn client:build-js:search

      - name: Generate recommend client
        run: yarn generate:js:recommend

      - name: Build recommend client
        run: yarn client:build-js:recommend

      - name: Generate personalization client
        run: yarn generate:js:personalization

      - name: Build personalization client
        run: yarn client:build-js:personalization

      - name: Lint
        run: yarn lint
