name: Codegen

on:
  pull_request_target:
    types: [opened, synchronize, closed]

jobs:
  notification:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    if: (github.event.action == 'opened' || github.event.action == 'synchronize') && github.event.number
    permissions:
      pull-requests: write
    steps:
      - name: debugging - dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v4

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ### 🔨 The codegen job will run at the end of the CI.

            _Make sure your last commit does not contain generated code, it will be automatically pushed by our CI._

  cleanup:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    if: github.event.action == 'closed'
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - run: git push -d origin generated/${{ github.head_ref }} || true
