name: Codegen cleanup

on:
  pull_request:
    types: [closed]

jobs:
  codegen:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - name: Setup
        uses: ./.github/actions/setup

      - name: Spread generation to each repository
        run: yarn workspace scripts spreadGeneration $${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_RELEASE_BOT }}

      - name: Clean previously generated branch
        run: yarn workspace scripts cleanGeneratedBranch ${{ github.head_ref }}
