name: Process release
on:
  pull_request:
    types:
      - closed
    branches:
      - release
jobs:
  build:
    name: Release
    runs-on: ubuntu-20.04
    if: github.event.pull_request.merged == true && github.head_ref == 'main'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        id: setup
        uses: ./.github/actions/setup

      - run: ./scripts/release/process-release-commit.js
        env:
          PR_NUMBER: $${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
