name: Push generated files to the given repository

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'the name of the repository to push files to'
        required: true
        type: choice
        options:
          - AlgoliaWeb
          - mcp-node
          - docs-new
          - n8n-nodes-algolia
          - api-clients-mcp

jobs:
  push:
    name: Push generated files to the given repository
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: main

      - name: Setup
        id: setup
        uses: ./.github/actions/setup
        with:
          type: minimal

      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.ALGOLIA_BOT_CLIENT_ID }}
          private-key: ${{ secrets.ALGOLIA_BOT_PRIVATE_KEY }}
          owner: algolia
          repositories: ${{ inputs.name }}

      - run: yarn workspace scripts pushToRepository ${{ inputs.name }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          FORCE: true
