name: Renovate

on:
  schedule:
    - cron: '0 14 * * 5' # At 14:00 on Friday.
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.ALGOLIA_BOT_CLIENT_ID }}
          private-key: ${{ secrets.ALGOLIA_BOT_PRIVATE_KEY }}

      - name: Renovate Automatic Branch
        uses: bodinsamuel/renovate-automatic-branch@v1.0.13
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          repo-owner: algolia
          repo-name: api-clients-automation
          pull-request-title: 'chore(deps): dependencies'
          pull-request-body: |
            Weekly dependencies update.
            Contribute to #532
