name: Scheduled SLA refresh

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
    inputs:
      fake_input:
        description: input needed to satisfy the yaml linter
        required: false

jobs:
  release:
    name: Scheduled SLA refresh
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Setup
        id: setup
        uses: ./.github/actions/setup
        with:
          type: minimal

      - run: yarn cli release --sla-only
        env:
          GITHUB_TOKEN: ${{ secrets.ALGOLIA_BOT_TOKEN }}

      - name: Push specs to algolia documentation
        run: yarn workspace scripts pushToAlgoliaDoc
        env:
          GITHUB_TOKEN: ${{ secrets.ALGOLIA_BOT_TOKEN }}
