name: Scheduled Release

on:
  schedule:
    - cron: '0 9 * * 2'

jobs:
  renovate:
    name: Scheduled Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        id: setup
        uses: ./.github/actions/setup
        with:
          type: minimal

      - run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_RELEASE_BOT }}
