name: specs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build:spec

      - name: Validate
        run: yarn validate

      - name: Lint
        run: yamllint specs
