name: Codegen cleanup

on:
  push:
    branches:
      - main

jobs:
  codegen:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - name: Setup
        uses: ./.github/actions/setup

      - name: Spread generation to each repository
        run: yarn workspace scripts spreadGeneration
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_RELEASE_BOT }}
