name: Pull-request
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  build:
    name: Validate title
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        id: setup
        uses: ./.github/actions/setup

      - run: yarn ts-node ./scripts/ci/validate-pr-title.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
