allowCompressionOfIntegerArray:
  type: boolean
  description: Enables compression of large integer arrays.
  default: false

attributeForDistinct:
  type: string
  description: Name of the de-duplication attribute to be used with the distinct feature.
  default: null

attributesToTransliterate:
  type: array
  items:
    type: string
  description: Specify on which attributes to apply transliteration.

camelCaseAttributes:
  type: array
  items:
    type: string
  description: List of attributes on which to do a decomposition of camel case words.
  default: []

customNormalization:
  type: object
  additionalProperties: true
  description: Override the default normalization handled by the engine.
  default: {}

decompoundedAttributes:
  type: object
  additionalProperties: true
  description: Specify on which attributes in your index Algolia should apply word segmentation, also known as decompounding.
  default: {}

disablePrefixOnAttributes:
  type: array
  items:
    type: string
  description: List of attributes on which you want to disable prefix matching.
  default: []

disableTypoToleranceOnWords:
  type: array
  items:
    type: string
  description: A list of words for which you want to turn off typo tolerance.
  default: []

filterPromotes:
  type: boolean
  description: Whether promoted results should match the filters of the current search, except for geographic filters.
  default: false

indexLanguages:
  type: array
  items:
    type: string
  description: Sets the languages at the index level for language-specific processing such as tokenization and normalization.
  default: []

numericAttributesForFiltering:
  type: array
  items:
    type: string
  description: List of numeric attributes that can be used as numerical filters.
  default: null

paginationLimitedTo:
  type: integer
  description: Set the maximum number of hits accessible via pagination.
  default: 1000

userData:
  type: object
  additionalProperties: true
  description: Lets you store custom data in your indices.
  default: {}

replicas:
  type: array
  items:
    type: string
  description: Creates replicas, exact copies of an index.
  default: []
