version: "2"
run:
  concurrency: 2
linters:
  default: all
  disable:
    - canonicalheader
    - containedctx
    - copyloopvar
    - cyclop
    - depguard
    - dupl
    - dupword
    - err113
    - exhaustive
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - gocyclo
    - inamedparam
    - intrange
    - lll
    - maintidx
    - mnd
    - nestif
    - nilnil
    - nonamedreturns
    - perfsprint
    - recvcheck
    - tagliatelle
    - varnamelen
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    revive:
      rules:
        - name: var-naming
          disabled: true
    staticcheck:
      checks: ["all", "-ST1005", "-ST1016"]
  exclusions:
    generated: disable
    presets:
      - comments
      - std-error-handling
    # old client is not linted
    paths-except:
      - algolia/abtesting
      - algolia/analytics
      - algolia/composition
      - algolia/ingestion
      - algolia/insights
      - algolia/monitoring
      - algolia/personalization
      - algolia/query-suggestions
      - algolia/recommend
      - algolia/search
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      max-len: 150
  exclusions:
    generated: disable
    # old client is not formatted
    paths:
      - algolia/abtesting
      - algolia/analytics
      - algolia/composition
      - algolia/ingestion
      - algolia/insights
      - algolia/monitoring
      - algolia/personalization
      - algolia/query-suggestions
      - algolia/recommend
      - algolia/search
