openapi: 3.0.2
info:
  title: Ingestion API
  description: >-
    [Documentation](https://docs.google.com/document/d/13UnFi4Osfw4vOJr5iN4P4RJDZdslpFs4OgM4F1VBwQc/edit#heading=h.kp12qj1w1lig)
  version: '1.0'
components:
  securitySchemes:
    appId:
      $ref: '../common/securitySchemes.yml#/appId'
    apiKey:
      $ref: '../common/securitySchemes.yml#/apiKey'
servers:
  - url: https://data.{region}.algolia.com
    variables:
      region:
        enum:
          - us
        default: us
security:
  - appId: []
    apiKey: []
tags:
  - name: authentications
    x-displayName: Authentications
    description: Authentications describe the way we connect to Algolia, or any platform.
  - name: destinations
    x-displayName: Destinations
    description: Destinations refers to an Algolia product (Search, Insight, Recommend, ...).
  - name: sources
    x-displayName: Sources
    description: Sources describe the platform informations.
  - name: tasks
    x-displayName: Tasks
    description: Tasks refers to all type on Ingestion we can do (Reindex, On demand update, ...).
paths:
  /1/authentications:
    $ref: 'paths/authentications/authentications.yml'
  /1/authentications/{authenticationID}:
    $ref: 'paths/authentications/authenticationID.yml'
  /1/destinations:
    $ref: 'paths/destinations/destinations.yml'
  /1/destinations/{destinationID}:
    $ref: 'paths/destinations/destinationID.yml'
  /1/sources:
    $ref: 'paths/sources/sources.yml'
  /1/sources/{sourceID}:
    $ref: 'paths/sources/sourceID.yml'
  /1/tasks:
    $ref: 'paths/tasks/tasks.yml'
  /1/tasks/{taskID}:
    $ref: 'paths/tasks/taskID.yml'
  /1/tasks/{taskID}/run:
    $ref: 'paths/tasks/runTask.yml'
  /1/tasks/{taskID}/enable:
    $ref: 'paths/tasks/enableTask.yml'
  /1/tasks/{taskID}/disable:
    $ref: 'paths/tasks/disableTask.yml'
